#!/usr/bin/env python3
"""Generates the source of ZZXXMLA1_CL_MDX_FUNTABLE, Mondrian's built-in function table and the user-defined functions
every schema has (GlobalFunTable: IN, MATCHES, ...), from eMondrian's jar.

    python scripts/generate-funtable.py out/zzxxmla1_cl_mdx_funtable.clas.abap

Copies scripts/funtable/DumpFunTable.java into the eMondrian container, runs it against the jars of the web app and
turns its output (one resolver per line, see the Java file) into the class: the resolvers in Mondrian's order (the
order of a JVM run; only the order of resolvers of the same name matters) with
their signatures as categories, the reserved words and the signature texts. Write the result into SAP with the ABAP
FS tools (the class is not edited by hand), then `scripts/sap-sync.sh pull`.
"""
import argparse
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTAINER = "emondrian"
LIB = "/usr/local/tomcat/webapps/emondrian/WEB-INF/lib"
SEPARATOR = "#"
MAX_LITERAL = 180

LICENSE_HEADER = (ROOT / "scripts" / "abap-license-header.txt").read_text(encoding="utf-8")

HEADER = LICENSE_HEADER + '''"! The reference's built-in function table (olap.fun.BuiltinFunTable as indexed by FunTableImpl) and the
"! user-defined functions of GlobalFunTable (UdfResolver, e.g. IN and MATCHES), generated by
"! scripts/generate-funtable.py from the reference server's jar: do not edit by hand. A resolver has the name and syntax of its
"! functions, the resolver class (SimpleResolver and ReflectiveMultiResolver resolve by their signatures, the others
"! have resolution logic of their own), its signatures as categories (olap.Category, possibly with the
"! Constant flag 64), its reserved words and its signature text. get_resolvers returns the resolvers of a name and a
"! syntax in the reference's order; is_property and is_reserved are FunTable.isProperty and FunTable.isReserved.
CLASS zzxxmla1_cl_mdx_funtable DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
    TYPES ty_t_category TYPE STANDARD TABLE OF i WITH EMPTY KEY.
    TYPES:
      BEGIN OF ty_signature,
        return_category      TYPE i,
        parameter_categories TYPE ty_t_category,
      END OF ty_signature,
      ty_t_signature TYPE STANDARD TABLE OF ty_signature WITH EMPTY KEY.
    TYPES:
      BEGIN OF ty_resolver,
        id             TYPE i,        " position in the reference's table
        kind           TYPE string,   " resolver class, e.g. SimpleResolver or CrossJoinFunDef$ResolverImpl
        name           TYPE string,
        syntax         TYPE string,   " as zzxxmla1_cl_mdx_node=>c_syntax
        signatures     TYPE ty_t_signature,
        reserved_words TYPE string_table,
        signature_text TYPE string,   " Resolver.getSignature
      END OF ty_resolver,
      ty_t_resolver TYPE STANDARD TABLE OF ty_resolver WITH EMPTY KEY.

    CLASS-METHODS instance
      RETURNING VALUE(result) TYPE REF TO zzxxmla1_cl_mdx_funtable.
    "! FunTable.getResolvers(name, syntax): the name compares in upper case.
    METHODS get_resolvers
      IMPORTING name          TYPE string
                syntax        TYPE string
      RETURNING VALUE(result) TYPE ty_t_resolver.
    METHODS get_all
      RETURNING VALUE(result) TYPE ty_t_resolver.
    METHODS is_property
      IMPORTING name          TYPE string
      RETURNING VALUE(result) TYPE abap_bool.
    METHODS is_reserved
      IMPORTING name          TYPE string
      RETURNING VALUE(result) TYPE abap_bool.

  PRIVATE SECTION.
    TYPES:
      BEGIN OF ty_key,
        key TYPE string,
        ids TYPE ty_t_category,
      END OF ty_key.
    CLASS-DATA singleton TYPE REF TO zzxxmla1_cl_mdx_funtable.
    DATA resolvers      TYPE ty_t_resolver.
    DATA keys           TYPE HASHED TABLE OF ty_key WITH UNIQUE KEY key.
    DATA property_words TYPE HASHED TABLE OF string WITH UNIQUE KEY table_line.
    DATA reserved_words TYPE HASHED TABLE OF string WITH UNIQUE KEY table_line.

    METHODS constructor.
    "! The resolvers as generated: kind#name#syntax#signatures#reserved words#signature text.
    CLASS-METHODS definitions
      RETURNING VALUE(result) TYPE string_table.
ENDCLASS.

CLASS zzxxmla1_cl_mdx_funtable IMPLEMENTATION.

  METHOD instance.
    IF singleton IS NOT BOUND.
      singleton = NEW #( ).
    ENDIF.
    result = singleton.
  ENDMETHOD.

  METHOD constructor.
    LOOP AT definitions( ) INTO DATA(definition).
      SPLIT definition AT `#` INTO DATA(kind) DATA(name) DATA(syntax) DATA(signatures) DATA(reserved) DATA(text).
      DATA(resolver) = VALUE ty_resolver( id = sy-tabix kind = kind name = name syntax = syntax signature_text = text ).
      IF signatures IS NOT INITIAL.
        SPLIT signatures AT `;` INTO TABLE DATA(signature_list).
        LOOP AT signature_list INTO DATA(signature).
          SPLIT signature AT `:` INTO DATA(return_category) DATA(parameters).
          DATA(entry) = VALUE ty_signature( return_category = CONV i( return_category ) ).
          IF parameters IS NOT INITIAL.
            SPLIT parameters AT `,` INTO TABLE DATA(parameter_list).
            entry-parameter_categories = VALUE #( FOR parameter IN parameter_list ( CONV i( parameter ) ) ).
          ENDIF.
          APPEND entry TO resolver-signatures.
        ENDLOOP.
      ENDIF.
      IF reserved IS NOT INITIAL.
        SPLIT reserved AT `,` INTO TABLE resolver-reserved_words.
        LOOP AT resolver-reserved_words INTO DATA(word).
          INSERT to_upper( word ) INTO TABLE reserved_words.
        ENDLOOP.
      ENDIF.
      IF syntax = `Property`.
        INSERT to_upper( name ) INTO TABLE property_words.
      ENDIF.
      APPEND resolver TO resolvers.
      DATA(key) = |{ to_upper( name ) }#{ syntax }|.
      ASSIGN keys[ key = key ] TO FIELD-SYMBOL(<key>).
      IF sy-subrc <> 0.
        INSERT VALUE #( key = key ) INTO TABLE keys ASSIGNING <key>.
      ENDIF.
      APPEND resolver-id TO <key>-ids.
    ENDLOOP.
  ENDMETHOD.

  METHOD get_resolvers.
    DATA(key) = |{ to_upper( name ) }#{ syntax }|.
    IF line_exists( keys[ key = key ] ).
      result = VALUE #( FOR id IN keys[ key = key ]-ids ( resolvers[ id ] ) ).
    ENDIF.
  ENDMETHOD.

  METHOD get_all.
    result = resolvers.
  ENDMETHOD.

  METHOD is_property.
    result = xsdbool( line_exists( property_words[ table_line = to_upper( name ) ] ) ).
  ENDMETHOD.

  METHOD is_reserved.
    result = xsdbool( line_exists( reserved_words[ table_line = to_upper( name ) ] ) ).
  ENDMETHOD.

  METHOD definitions.
'''

FOOTER = '''  ENDMETHOD.

ENDCLASS.
'''


def dump():
    java = ROOT / "scripts" / "funtable" / "DumpFunTable.java"
    subprocess.run(["docker", "cp", str(java), f"{CONTAINER}:/tmp/DumpFunTable.java"], check=True)
    result = subprocess.run(
        ["docker", "exec", CONTAINER, "sh", "-c", f"cd /tmp && java -cp '{LIB}/*:.' DumpFunTable.java 2>/dev/null"],
        check=True, capture_output=True, text=True, encoding="utf-8")
    return [line.split("\t") for line in result.stdout.splitlines() if line.strip()]


def literal(text):
    """A string template-free ABAP literal, split into pieces joined by && when long."""
    pieces = [text[i:i + MAX_LITERAL] for i in range(0, len(text), MAX_LITERAL)] or [""]
    return "\n               && ".join("`" + p.replace("`", "``") + "`" for p in pieces)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("output")
    args = parser.parse_args()
    rows = dump()
    lines = []
    for kind, name, syntax, signatures, reserved, text in rows:
        definition = SEPARATOR.join([kind, name, syntax, signatures, reserved, text])
        assert definition.count(SEPARATOR) == 5, definition
        lines.append(f"    APPEND {literal(definition)} TO result.")
    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(HEADER + "\n".join(lines) + "\n" + FOOTER, encoding="utf-8", newline="\n")
    print(f"{out}: {len(rows)} resolvers")


if __name__ == "__main__":
    main()
