#!/usr/bin/env python3
"""Generates src/zzxxmla1_cl_xmla_mdschema.clas.abap: the constant xsd:schema block of an Execute answer (Content
SchemaData), taken from a captured answer of the reference server (reference/execute_one_measure/response.xml). The block is the same
for every query, so it is static knowledge of the engine like the other ZZXXMLA1_CL_XMLA_* lists."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
answer = (ROOT / "reference/execute_one_measure/response.xml").read_text(encoding="utf-8")
block = re.search(r"^ *<xsd:schema.*?</xsd:schema>", answer, re.S | re.M).group(0)
lines = [l.rstrip() for l in block.splitlines()]
assert not any("`" in l for l in lines)


def chunks(line, size=150):
    """A literal is limited to 255 characters per source line: long lines become several literals."""
    parts = []
    while len(line) > size:
        cut = line.rfind(" ", 0, size)
        parts.append(line[:cut])
        line = line[cut:]
    return parts + [line]


header = (ROOT / "scripts" / "abap-license-header.txt").read_text(encoding="utf-8").splitlines()
out = header + ['"! The xsd:schema element that opens the answer of an Execute request with Content SchemaData: the same for every query,',
       '"! taken from the answer of the reference server (generated by scripts/generate-mddataset-schema.py, do not edit).',
       'CLASS zzxxmla1_cl_xmla_mdschema DEFINITION', '  PUBLIC', '  FINAL', '  CREATE PUBLIC.', '',
       '  PUBLIC SECTION.', '    CLASS-METHODS get RETURNING VALUE(result) TYPE string.', 'ENDCLASS.', '',
       'CLASS zzxxmla1_cl_xmla_mdschema IMPLEMENTATION.', '  METHOD get.',
       '    DATA(lines) = VALUE string_table(']
for l in lines:
    parts = chunks(l)
    out.append("      ( " + "`" + parts[0] + "`" + (" &&" if len(parts) > 1 else " )"))
    for n, part in enumerate(parts[1:], 1):
        out.append("        `" + part + "`" + (" &&" if n < len(parts) - 1 else " )"))
out += ['    ).', '    result = concat_lines_of( table = lines sep = cl_abap_char_utilities=>newline ) && cl_abap_char_utilities=>newline.',
        '  ENDMETHOD.', 'ENDCLASS.', '']
(ROOT / "src/zzxxmla1_cl_xmla_mdschema.clas.abap").write_text("\n".join(out), encoding="utf-8", newline="\n")
xml = (ROOT / "src/zzxxmla1_cl_xmla_static.clas.xml").read_text(encoding="utf-8")
xml = xml.replace("ZZXXMLA1_CL_XMLA_STATIC", "ZZXXMLA1_CL_XMLA_MDSCHEMA").replace("Static XMLA rowsets", "Schema block of an XMLA Execute answer")
(ROOT / "src/zzxxmla1_cl_xmla_mdschema.clas.xml").write_text(xml, encoding="utf-8", newline="\n")
print(len(lines), "lines")
