#!/usr/bin/env python3
"""Generates the ABAP class ZZXXMLA1_CL_WEB_APP_FILES from web/schema/: the schema builder's files as code of the
package, which ZZXXMLA1_CL_WEB_APP serves under /zzxxmla1/schema/, so a system needs nothing but the package and the
app changes with it. Run it after every change of web/schema/, then write the class to SAP:

    python scripts/generate-web-app-abap.py
    "$LOCALAPPDATA/pipx/pipx/venvs/sapcli/Scripts/python.exe" scripts/sap-write.py zzxxmla1_cl_web_app_files

Each file is one method named after it (app_js, console_html, ...; file( ) picks it by the path, so a request builds
only its own file) that appends string templates (|...|) to a table and joins them: a template keeps every
character as it is once \\ | { } are escaped, the line feeds are written as \\n, and an ABAP source line stays below 255
characters. The source is ASCII only: a character outside ASCII (the icons, an ellipsis) is an embedded expression
cl_abap_conv_in_ce=>uccp( ), because another system that imports the class would otherwise show it as '?'. The files
are served as UTF-8 with LF line ends.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "web" / "schema"
SERVER_FOLDER = "/schema"
CLASS = "zzxxmla1_cl_web_app_files"
CHUNK = 180  # escaped characters per template, so that a source line stays below 255 characters
HEADER = (ROOT / "scripts" / "abap-license-header.txt").read_text(encoding="utf-8").rstrip("\n")


def escape(text):
    """The text as pieces of string template content, none longer than CHUNK and no escape sequence split."""
    pieces, current = [], ""
    for char in text:
        if char == "\r":
            continue
        if ord(char) > 127:
            # The source stays ASCII: a character outside it is built at runtime from its UTF-16 code units, since
            # moving source to another system (abapGit, a transport, a code page without it) turns it into '?'.
            units = char.encode("utf-16-be")
            token = "".join("{ cl_abap_conv_in_ce=>uccp( '" + units[i:i + 2].hex().upper() + "' ) }"
                            for i in range(0, len(units), 2))
        else:
            token = {"\\": "\\\\", "|": "\\|", "{": "\\{", "}": "\\}", "\n": "\\n", "\t": "\\t"}.get(char, char)
        if len(current) + len(token) > CHUNK:
            pieces.append(current)
            current = ""
        current += token
    if current or not pieces:
        pieces.append(current)
    return pieces


def method_name(path, taken):
    """An ABAP method name for a file: its name in lower case, other characters as _, at most 30 characters, unique."""
    base = re.sub(r"[^a-z0-9]+", "_", path.name.lower()).strip("_")[:30] or "file"
    if base[0].isdigit():
        base = ("f_" + base)[:30]
    name, number = base, 1
    while name in taken:
        number += 1
        name = f"{base[:30 - len(str(number)) - 1]}_{number}"
    taken.add(name)
    return name


def main():
    files = sorted(p for p in APP.rglob("*") if p.is_file())
    if not files:
        sys.exit(f"error: no files in {APP}")
    methods, taken = [], {"file"}
    for path in files:
        text = path.read_bytes().decode("utf-8").replace("\r\n", "\n")
        server_path = SERVER_FOLDER + "/" + path.relative_to(APP).as_posix()
        methods.append((method_name(path, taken), server_path, text))

    source = [HEADER,
              f'"! The files of the schema builder (web/schema/), generated by scripts/generate-web-app-abap.py: do not',
              f'"! edit, change web/schema/ and generate again. ZZXXMLA1_CL_WEB_APP serves them below {SERVER_FOLDER}/.',
              f"CLASS {CLASS} DEFINITION",
              "  PUBLIC",
              "  FINAL",
              "  CREATE PUBLIC.",
              "",
              "  PUBLIC SECTION.",
              "    TYPES:",
              "      BEGIN OF ty_file,",
              "        path    TYPE string,",
              "        content TYPE string,",
              "      END OF ty_file.",
              "",
              f"    \"! The file of a path below the ICF node ({SERVER_FOLDER}/app.js); initial if the app has none.",
              "    CLASS-METHODS file",
              "      IMPORTING !path         TYPE string",
              "      RETURNING VALUE(result) TYPE ty_file.",
              "  PROTECTED SECTION.",
              "  PRIVATE SECTION."]
    for name, server_path, _ in methods:
        source += [f"    \"! {server_path}",
                   f"    CLASS-METHODS {name}",
                   "      RETURNING VALUE(result) TYPE string."]
    source += ["ENDCLASS.", "", "", "", f"CLASS {CLASS} IMPLEMENTATION.", "", "  METHOD file.",
               "    result-path = path.", "    CASE path."]
    for name, server_path, _ in methods:
        source += [f"      WHEN `{server_path}`.", f"        result-content = {name}( )."]
    source += ["      WHEN OTHERS.", "        CLEAR result.", "    ENDCASE.", "  ENDMETHOD."]
    for name, _, text in methods:
        source += ["", f"  METHOD {name}.", "    DATA parts TYPE string_table."]
        source += [f"    APPEND |{piece}| TO parts." for piece in escape(text)]
        source += ["    result = concat_lines_of( parts ).", "  ENDMETHOD."]
    source += ["", "ENDCLASS.", ""]

    out = ROOT / "src" / f"{CLASS}.clas.abap"
    out.write_bytes("\r\n".join(source).encode("utf-8"))
    (ROOT / "src" / f"{CLASS}.clas.xml").write_bytes("\r\n".join([
        '<?xml version="1.0" encoding="utf-8"?>',
        '<abapGit version="v1.0.0" serializer="LCL_OBJECT_CLAS" serializer_version="v1.0.0">',
        ' <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">',
        "  <asx:values>",
        "   <VSEOCLASS>",
        f"    <CLSNAME>{CLASS.upper()}</CLSNAME>",
        "    <LANGU>E</LANGU>",
        "    <DESCRIPT>The schema builder&apos;s files (generated)</DESCRIPT>",
        "    <STATE>1</STATE>",
        "    <CLSCCINCL>X</CLSCCINCL>",
        "    <FIXPT>X</FIXPT>",
        "    <UNICODE>X</UNICODE>",
        "   </VSEOCLASS>",
        "  </asx:values>",
        " </asx:abap>",
        "</abapGit>",
        ""]).encode("utf-8"))
    lines = "\n".join(source).split("\n")
    longest = max(len(line) for line in lines)
    print(f"{out.relative_to(ROOT)}: {len(methods)} files, {len(lines)} lines, longest {longest} characters")


if __name__ == "__main__":
    main()
