#!/usr/bin/env python3
"""Generates the ABAP class ZZXXMLA1_CL_WEB_APP_FILES from web/schema/: the schema builder's files inside the package,
so ZZXXMLA1_CL_SETUP (program ZZXXMLA1_SETUP) writes them to the server's files (ZZXXMLA1_FILE) below /schema/ and a
system needs nothing but the package. Run it after every change of web/schema/, then write the class to SAP:

    python scripts/generate-web-app-abap.py
    "$LOCALAPPDATA/pipx/pipx/venvs/sapcli/Scripts/python.exe" scripts/sap-write.py zzxxmla1_cl_web_app_files

Each file is one method that appends string templates (|...|) to a table and joins them: a template keeps every
character as it is once \\ | { } are escaped, the line feeds are written as \\n, and an ABAP source line stays below 255
characters. The files are UTF-8 with LF line ends, as scripts/sap-files.py app writes them.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "web" / "schema"
SERVER_FOLDER = "/schema"
CLASS = "zzxxmla1_cl_web_app_files"
CHUNK = 180  # escaped characters per template, so that a source line stays below 255 characters
HEADER = (ROOT / "scripts" / "abap-license-header.txt").read_text(encoding="utf-8").rstrip("\n")


def escape(text):
    """The text as pieces of string template content, none longer than CHUNK and no escape sequence split."""
    pieces, current = [], ""
    for char in text:
        token = {"\\": "\\\\", "|": "\\|", "{": "\\{", "}": "\\}", "\n": "\\n", "\t": "\\t"}.get(char, char)
        if char == "\r":
            continue
        if len(current) + len(token) > CHUNK:
            pieces.append(current)
            current = ""
        current += token
    if current or not pieces:
        pieces.append(current)
    return pieces


def main():
    files = sorted(p for p in APP.rglob("*") if p.is_file())
    if not files:
        sys.exit(f"error: no files in {APP}")
    methods = []
    for index, path in enumerate(files, start=1):
        text = path.read_bytes().decode("utf-8").replace("\r\n", "\n")
        server_path = SERVER_FOLDER + "/" + path.relative_to(APP).as_posix()
        methods.append((f"file_{index}", server_path, text))

    source = [HEADER,
              f'"! The files of the schema builder (web/schema/), generated by scripts/generate-web-app-abap.py: do not',
              f'"! edit, change web/schema/ and generate again. ZZXXMLA1_CL_SETUP writes them below {SERVER_FOLDER}/.',
              f"CLASS {CLASS} DEFINITION",
              "  PUBLIC",
              "  FINAL",
              "  CREATE PUBLIC.",
              "",
              "  PUBLIC SECTION.",
              "    TYPES:",
              "      BEGIN OF ty_file,",
              "        path    TYPE string,",
              "        content TYPE string,",
              "      END OF ty_file,",
              "      ty_t_file TYPE STANDARD TABLE OF ty_file WITH EMPTY KEY.",
              "",
              "    \"! The files with their paths on the server.",
              "    CLASS-METHODS files",
              "      RETURNING VALUE(result) TYPE ty_t_file.",
              "  PROTECTED SECTION.",
              "  PRIVATE SECTION."]
    for name, server_path, _ in methods:
        source += [f"    \"! {server_path}",
                   f"    CLASS-METHODS {name}",
                   "      RETURNING VALUE(result) TYPE string."]
    source += ["ENDCLASS.", "", "", "", f"CLASS {CLASS} IMPLEMENTATION.", "", "  METHOD files.",
               "    result = VALUE #("]
    source += [f"      ( path = `{server_path}` content = {name}( ) )" for name, server_path, _ in methods]
    source[-1] += " )."
    source += ["  ENDMETHOD."]
    for name, _, text in methods:
        source += ["", f"  METHOD {name}.", "    DATA parts TYPE string_table."]
        source += [f"    APPEND |{piece}| TO parts." for piece in escape(text)]
        source += ["    result = concat_lines_of( parts ).", "  ENDMETHOD."]
    source += ["", "ENDCLASS.", ""]

    out = ROOT / "src" / f"{CLASS}.clas.abap"
    out.write_bytes("\r\n".join(source).encode("utf-8"))
    (ROOT / "src" / f"{CLASS}.clas.xml").write_bytes("\r\n".join([
        '<?xml version="1.0" encoding="utf-8"?>',
        '<abapGit version="v1.0.0" serializer="LCL_OBJECT_CLAS" serializer_version="v1.0.0">',
        ' <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">',
        "  <asx:values>",
        "   <VSEOCLASS>",
        f"    <CLSNAME>{CLASS.upper()}</CLSNAME>",
        "    <LANGU>E</LANGU>",
        "    <DESCRIPT>The schema builder&apos;s files (generated)</DESCRIPT>",
        "    <STATE>1</STATE>",
        "    <CLSCCINCL>X</CLSCCINCL>",
        "    <FIXPT>X</FIXPT>",
        "    <UNICODE>X</UNICODE>",
        "   </VSEOCLASS>",
        "  </asx:values>",
        " </asx:abap>",
        "</abapGit>",
        ""]).encode("utf-8"))
    longest = max(len(line) for line in source)
    print(f"{out.relative_to(ROOT)}: {len(methods)} files, {len(source)} lines, longest {longest} characters")


if __name__ == "__main__":
    main()
