*----------------------------------------------------------------------------------------------------------------------*
* olap4abap - XMLA server with an MDX engine for SAP BW               https://github.com/arcanist123/olap4abap
* Copyright (c) 2026 the olap4abap authors
*
* This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0,
* which is available at https://www.eclipse.org/legal/epl-2.0/
* SPDX-License-Identifier: EPL-2.0
*
* olap4abap contains code derived from Mondrian (Eclipse Public License 1.0): Copyright (C) 1998-2005 Julian Hyde,
* Copyright (C) 2005-2021 Hitachi Vantara and others, Copyright (C) 2021-2025 Sergei Semenkov. See the NOTICE file.
*----------------------------------------------------------------------------------------------------------------------*
"! The reference's built-in function table (olap.fun.BuiltinFunTable as indexed by FunTableImpl) and the
"! user-defined functions of GlobalFunTable (UdfResolver, e.g. IN and MATCHES), generated by
"! scripts/generate-funtable.py from the reference server's jar: do not edit by hand. A resolver has the name and syntax of its
"! functions, the resolver class (SimpleResolver and ReflectiveMultiResolver resolve by their signatures, the others
"! have resolution logic of their own), its signatures as categories (olap.Category, possibly with the
"! Constant flag 64), its reserved words and its signature text. get_resolvers returns the resolvers of a name and a
"! syntax in the reference's order; is_property and is_reserved are FunTable.isProperty and FunTable.isReserved.
CLASS zzxxmla1_cl_mdx_funtable DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
    TYPES ty_t_category TYPE STANDARD TABLE OF i WITH EMPTY KEY.
    TYPES:
      BEGIN OF ty_signature,
        return_category      TYPE i,
        parameter_categories TYPE ty_t_category,
      END OF ty_signature,
      ty_t_signature TYPE STANDARD TABLE OF ty_signature WITH EMPTY KEY.
    TYPES:
      BEGIN OF ty_resolver,
        id             TYPE i,        " position in the reference's table
        kind           TYPE string,   " resolver class, e.g. SimpleResolver or CrossJoinFunDef$ResolverImpl
        name           TYPE string,
        syntax         TYPE string,   " as zzxxmla1_cl_mdx_node=>c_syntax
        signatures     TYPE ty_t_signature,
        reserved_words TYPE string_table,
        signature_text TYPE string,   " Resolver.getSignature
      END OF ty_resolver,
      ty_t_resolver TYPE STANDARD TABLE OF ty_resolver WITH EMPTY KEY.

    CLASS-METHODS instance
      RETURNING VALUE(result) TYPE REF TO zzxxmla1_cl_mdx_funtable.
    "! FunTable.getResolvers(name, syntax): the name compares in upper case.
    METHODS get_resolvers
      IMPORTING name          TYPE string
                syntax        TYPE string
      RETURNING VALUE(result) TYPE ty_t_resolver.
    METHODS get_all
      RETURNING VALUE(result) TYPE ty_t_resolver.
    METHODS is_property
      IMPORTING name          TYPE string
      RETURNING VALUE(result) TYPE abap_bool.
    METHODS is_reserved
      IMPORTING name          TYPE string
      RETURNING VALUE(result) TYPE abap_bool.

  PRIVATE SECTION.
    TYPES:
      BEGIN OF ty_key,
        key TYPE string,
        ids TYPE ty_t_category,
      END OF ty_key.
    CLASS-DATA singleton TYPE REF TO zzxxmla1_cl_mdx_funtable.
    DATA resolvers      TYPE ty_t_resolver.
    DATA keys           TYPE HASHED TABLE OF ty_key WITH UNIQUE KEY key.
    DATA property_words TYPE HASHED TABLE OF string WITH UNIQUE KEY table_line.
    DATA reserved_words TYPE HASHED TABLE OF string WITH UNIQUE KEY table_line.

    METHODS constructor.
    "! The resolvers as generated: kind#name#syntax#signatures#reserved words#signature text.
    CLASS-METHODS definitions
      RETURNING VALUE(result) TYPE string_table.
ENDCLASS.

CLASS zzxxmla1_cl_mdx_funtable IMPLEMENTATION.

  METHOD instance.
    IF singleton IS NOT BOUND.
      singleton = NEW #( ).
    ENDIF.
    result = singleton.
  ENDMETHOD.

  METHOD constructor.
    LOOP AT definitions( ) INTO DATA(definition).
      SPLIT definition AT `#` INTO DATA(kind) DATA(name) DATA(syntax) DATA(signatures) DATA(reserved) DATA(text).
      DATA(resolver) = VALUE ty_resolver( id = sy-tabix kind = kind name = name syntax = syntax signature_text = text ).
      IF signatures IS NOT INITIAL.
        SPLIT signatures AT `;` INTO TABLE DATA(signature_list).
        LOOP AT signature_list INTO DATA(signature).
          SPLIT signature AT `:` INTO DATA(return_category) DATA(parameters).
          DATA(entry) = VALUE ty_signature( return_category = CONV i( return_category ) ).
          IF parameters IS NOT INITIAL.
            SPLIT parameters AT `,` INTO TABLE DATA(parameter_list).
            entry-parameter_categories = VALUE #( FOR parameter IN parameter_list ( CONV i( parameter ) ) ).
          ENDIF.
          APPEND entry TO resolver-signatures.
        ENDLOOP.
      ENDIF.
      IF reserved IS NOT INITIAL.
        SPLIT reserved AT `,` INTO TABLE resolver-reserved_words.
        LOOP AT resolver-reserved_words INTO DATA(word).
          INSERT to_upper( word ) INTO TABLE reserved_words.
        ENDLOOP.
      ENDIF.
      IF syntax = `Property`.
        INSERT to_upper( name ) INTO TABLE property_words.
      ENDIF.
      APPEND resolver TO resolvers.
      DATA(key) = |{ to_upper( name ) }#{ syntax }|.
      ASSIGN keys[ key = key ] TO FIELD-SYMBOL(<key>).
      IF sy-subrc <> 0.
        INSERT VALUE #( key = key ) INTO TABLE keys ASSIGNING <key>.
      ENDIF.
      APPEND resolver-id TO <key>-ids.
    ENDLOOP.
  ENDMETHOD.

  METHOD get_resolvers.
    DATA(key) = |{ to_upper( name ) }#{ syntax }|.
    IF line_exists( keys[ key = key ] ).
      result = VALUE #( FOR id IN keys[ key = key ]-ids ( resolvers[ id ] ) ).
    ENDIF.
  ENDMETHOD.

  METHOD get_all.
    result = resolvers.
  ENDMETHOD.

  METHOD is_property.
    result = xsdbool( line_exists( property_words[ table_line = to_upper( name ) ] ) ).
  ENDMETHOD.

  METHOD is_reserved.
    result = xsdbool( line_exists( reserved_words[ table_line = to_upper( name ) ] ) ).
  ENDMETHOD.

  METHOD definitions.
    APPEND `SimpleResolver#Member_Caption#Property#9:6##<Member>.Member_Caption` TO result.
    APPEND `SimpleResolver#FormatPercent#Function#9:13##<String> FormatPercent(<Value>)` TO result.
    APPEND `SimpleResolver#FormatPercent#Function#9:13,15##<String> FormatPercent(<Value>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatPercent#Function#9:13,15,15##<String> FormatPercent(<Value>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatPercent#Function#9:13,15,15,15##<String> FormatPercent(<Value>, <Integer>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatPercent#Function#9:13,15,15,15,15##<String> FormatPercent(<Value>, <Integer>, <Integer>, <Integer>, <Integer>)` TO result.
    APPEND `ReflectiveMultiResolver#Count#Function#7:8;7:8,11#INCLUDEEMPTY,EXCLUDEEMPTY#Count(<Set>[, EXCLUDEEMPTY | INCLUDEEMPTY])` TO result.
    APPEND `SimpleResolver#AND#Infix#5:5,5##<Logical Expression> AND <Logical Expression>` TO result.
    APPEND `SimpleResolver#>=#Infix#5:7,7##<Numeric Expression> >= <Numeric Expression>` TO result.
    APPEND `SimpleResolver#>=#Infix#5:9,9##<String> >= <String>` TO result.
    APPEND `SimpleResolver#>#Infix#5:7,7##<Numeric Expression> > <Numeric Expression>` TO result.
    APPEND `SimpleResolver#>#Infix#5:9,9##<String> > <String>` TO result.
    APPEND `SimpleResolver#=#Infix#5:5,5##<Logical Expression> = <Logical Expression>` TO result.
    APPEND `SimpleResolver#=#Infix#5:7,7##<Numeric Expression> = <Numeric Expression>` TO result.
    APPEND `SimpleResolver#=#Infix#5:9,9##<String> = <String>` TO result.
    APPEND `SimpleResolver#<#Infix#5:7,7##<Numeric Expression> < <Numeric Expression>` TO result.
    APPEND `SimpleResolver#<#Infix#5:9,9##<String> < <String>` TO result.
    APPEND `SimpleResolver#Cousin#Function#6:6,6##<Member> Cousin(<Member>, <Member>)` TO result.
    APPEND `SimpleResolver#OR#Infix#5:5,5##<Logical Expression> OR <Logical Expression>` TO result.
    APPEND `SimpleResolver#TupleToStr#Function#9:10##<String> TupleToStr(<Tuple>)` TO result.
    APPEND `ReflectiveMultiResolver#Min#Function#7:8;7:8,7##Min(<Set>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#Tail#Function#8:8;8:8,7##Tail(<Set>[, <Count>])` TO result.
    APPEND `ReflectiveMultiResolver#NonEmpty#Function#8:8;8:8,8##NonEmpty(<Set1>[, <Set2>])` TO result.
    APPEND `SimpleResolver#StrToMember#Function#6:9##<Member> StrToMember(<String>)` TO result.
    APPEND `SimpleResolver#Item#Method#6:10,7##<Member> <Tuple>.Item(<Numeric Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#Item#Method#6:8,7##<Set>.Item(<Index>)` TO result.
    APPEND `SetItemFunDef$1#Item#Method###<Set>.Item(<String> [, ...])` TO result.
    APPEND `SimpleResolver#Space#Function#9:15##<String> Space(<Integer>)` TO result.
    APPEND `ReflectiveMultiResolver#Ancestors#Function#8:6,4;8:6,7##Ancestors(<Member>, {<Level>|<Numeric Expression>})` TO result.
    APPEND `ParameterFunDef$ParamRefResolver#ParamRef#Function#13:73##ParamRef(<Name>)` TO result.
    APPEND `SimpleResolver#LCase#Function#9:9##<String> LCase(<String>)` TO result.
    APPEND `SimpleResolver#CInt#Function#15:13##<Integer> CInt(<Value>)` TO result.
    APPEND `SimpleResolver#Oct#Function#9:13##<String> Oct(<Value>)` TO result.
    APPEND `SimpleResolver#Atanh#Function#7:7##<Numeric Expression> Atanh(<Numeric Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#VisualTotals#Function#8:8;8:8,9##VisualTotals(<Set>[, <Pattern>])` TO result.
    APPEND `ReflectiveMultiResolver#Union#Function#8:8,8;8:8,8,11#ALL,DISTINCT#Union(<Set1>, <Set2>[, ALL])` TO result.
    APPEND `CaseMatchFunDef$ResolverImpl#_CaseMatch#Case###Case <Expression> When <Expression> Then <Expression> [...] [Else <Expression>] End` TO result.
    APPEND `SimpleResolver#WeekdayName#Function#9:15,5,15##<String> WeekdayName(<Integer>, <Logical Expression>, <Integer>)` TO result.
    APPEND `SimpleResolver#Hierarchy#Property#3:4##<Level>.Hierarchy` TO result.
    APPEND `SimpleResolver#Hierarchy#Property#3:6##<Member>.Hierarchy` TO result.
    APPEND `SimpleResolver#Log10#Function#7:7##<Numeric Expression> Log10(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Right#Function#9:9,15##<String> Right(<String>, <Integer>)` TO result.
    APPEND `SimpleResolver#Val#Function#7:9##<Numeric Expression> Val(<String>)` TO result.
    APPEND `SimpleResolver#Str#Function#9:13##<String> Str(<Value>)` TO result.
    APPEND `SimpleResolver#CDbl#Function#7:13##<Numeric Expression> CDbl(<Value>)` TO result.
    APPEND `ReflectiveMultiResolver#IS#Infix#5:6,6;5:4,4;5:3,3;5:2,2;5:10,10##<Expression> IS <Expression>` TO result.
    APPEND `SimpleResolver#XOR#Infix#5:5,5##<Logical Expression> XOR <Logical Expression>` TO result.
    APPEND `SimpleResolver#Abs#Function#7:7##<Numeric Expression> Abs(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#<>#Infix#5:7,7##<Numeric Expression> <> <Numeric Expression>` TO result.
    APPEND `SimpleResolver#<>#Infix#5:9,9##<String> <> <String>` TO result.
    APPEND `SimpleResolver#IIf#Function#2:5,2,2##<Dimension> IIf(<Logical Expression>, <Dimension>, <Dimension>)` TO result.
    APPEND `SimpleResolver#IIf#Function#3:5,3,3##<Hierarchy> IIf(<Logical Expression>, <Hierarchy>, <Hierarchy>)` TO result.
    APPEND `SimpleResolver#IIf#Function#4:5,4,4##<Level> IIf(<Logical Expression>, <Level>, <Level>)` TO result.
    APPEND `SimpleResolver#IIf#Function#5:5,5,5##<Logical Expression> IIf(<Logical Expression>, <Logical Expression>, <Logical Expression>)` TO result.
    APPEND `SimpleResolver#IIf#Function#6:5,6,6##<Member> IIf(<Logical Expression>, <Member>, <Member>)` TO result.
    APPEND `SimpleResolver#IIf#Function#7:5,7,7##<Numeric Expression> IIf(<Logical Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#IIf#Function#8:5,8,8##<Set> IIf(<Logical Expression>, <Set>, <Set>)` TO result.
    APPEND `SimpleResolver#IIf#Function#9:5,9,9##<String> IIf(<Logical Expression>, <String>, <String>)` TO result.
    APPEND `SimpleResolver#IIf#Function#10:5,10,10##<Tuple> IIf(<Logical Expression>, <Tuple>, <Tuple>)` TO result.
    APPEND `SimpleResolver#Log#Function#7:7##<Numeric Expression> Log(<Numeric Expression>)` TO result.
    APPEND `AddCalculatedMembersFunDef$ResolverImpl#AddCalculatedMembers#Function#8:8##<Set> AddCalculatedMembers(<Set>)` TO result.
    APPEND `SimpleResolver#Level#Property#4:6##<Member>.Level` TO result.
    APPEND `SimpleResolver#:#Infix#8:6,6##<Member> : <Member>` TO result.
    APPEND `CaseTestFunDef$ResolverImpl#_CaseTest#Case###Case When <Logical Expression> Then <Expression> [...] [Else <Expression>] End` TO result.
    APPEND `SimpleResolver#DatePart#Function#15:9,18##<Integer> DatePart(<String>, <DateTime>)` TO result.
    APPEND `SimpleResolver#DatePart#Function#15:9,18,15##<Integer> DatePart(<String>, <DateTime>, <Integer>)` TO result.
    APPEND `SimpleResolver#DatePart#Function#15:9,18,15,15##<Integer> DatePart(<String>, <DateTime>, <Integer>, <Integer>)` TO result.
    APPEND `ReflectiveMultiResolver#Lag#Method#6:6,7##<Member>.Lag(<Numeric Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#Var#Function#7:8;7:8,7##Var(<Set>[, <Numeric Expression>])` TO result.
    APPEND `XtdFunDef$ResolverImpl#Wtd#Function#8:;8:6##Wtd([<Member>])` TO result.
    APPEND `ReflectiveMultiResolver#Aggregate#Function#7:8;7:8,7##Aggregate(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Cos#Function#7:7##<Numeric Expression> Cos(<Numeric Expression>)` TO result.
    APPEND `TupleFunDef$ResolverImpl#()#Parentheses###null` TO result.
    APPEND `ReflectiveMultiResolver#Hierarchize#Function#8:8;8:8,11#PRE,POST#Hierarchize(<Set>[, POST])` TO result.
    APPEND `SimpleResolver#Asc#Function#15:9##<Integer> Asc(<String>)` TO result.
    APPEND `SimpleResolver#Replace#Function#9:9,9,9##<String> Replace(<String>, <String>, <String>)` TO result.
    APPEND `SimpleResolver#Replace#Function#9:9,9,9,15##<String> Replace(<String>, <String>, <String>, <Integer>)` TO result.
    APPEND `SimpleResolver#Replace#Function#9:9,9,9,15,15##<String> Replace(<String>, <String>, <String>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#Replace#Function#9:9,9,9,15,15,15##<String> Replace(<String>, <String>, <String>, <Integer>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#StrComp#Function#15:9,9##<Integer> StrComp(<String>, <String>)` TO result.
    APPEND `SimpleResolver#StrComp#Function#15:9,9,15##<Integer> StrComp(<String>, <String>, <Integer>)` TO result.
    APPEND `SimpleResolver#DateSerial#Function#18:15,15,15##<DateTime> DateSerial(<Integer>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#UniqueName#Property#9:2##<Dimension>.UniqueName` TO result.
    APPEND `SimpleResolver#UniqueName#Property#9:3##<Hierarchy>.UniqueName` TO result.
    APPEND `SimpleResolver#UniqueName#Property#9:4##<Level>.UniqueName` TO result.
    APPEND `SimpleResolver#UniqueName#Property#9:6##<Member>.UniqueName` TO result.
    APPEND `TopBottomPercentSumFunDef$ResolverImpl#BottomPercent#Function#8:8,7,7##BottomPercent(<Set>, <Percentage>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#||#Infix#9:9,9##<String> || <String>` TO result.
    APPEND `ReflectiveMultiResolver#Max#Function#7:8;7:8,7##Max(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#TimeValue#Function#18:18##<DateTime> TimeValue(<DateTime>)` TO result.
    APPEND `SimpleResolver#SetToStr#Function#9:8##<String> SetToStr(<Set>)` TO result.
    APPEND `ReflectiveMultiResolver#Stddev#Function#7:8;7:8,7##Stddev(<Set>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#LinRegPoint#Function#7:7,8,7;7:7,8,7,7##LinRegPoint(<Numeric Expression>, <Set>, <Numeric Expression>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#Covariance#Function#7:8,7;7:8,7,7##Covariance(<Set>, <Numeric Expression>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#<=#Infix#5:7,7##<Numeric Expression> <= <Numeric Expression>` TO result.
    APPEND `SimpleResolver#<=#Infix#5:9,9##<String> <= <String>` TO result.
    APPEND `SimpleResolver#SLN#Function#7:7,7,7##<Numeric Expression> SLN(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Year#Function#15:18##<Integer> Year(<DateTime>)` TO result.
    APPEND `SimpleResolver#Round#Function#7:7##<Numeric Expression> Round(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Round#Function#7:7,15##<Numeric Expression> Round(<Numeric Expression>, <Integer>)` TO result.
    APPEND `TopBottomPercentSumFunDef$ResolverImpl#BottomSum#Function#8:8,7,7##BottomSum(<Set>, <Value>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#MIRR#Function#7:1,7,7##<Numeric Expression> MIRR(<Array>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#Avg#Function#7:8;7:8,7##Avg(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Sin#Function#7:7##<Numeric Expression> Sin(<Numeric Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#StdevP#Function#7:8;7:8,7##StdevP(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Parent#Property#6:6##<Member>.Parent` TO result.
    APPEND `ReflectiveMultiResolver#Generate#Function#8:8,8;8:8,8,11##Generate(<Set1>, <Set2>[, ALL])` TO result.
    APPEND `ReflectiveMultiResolver#Generate#Function#9:8,9;9:8,9,9;9:8,7,9##Generate(<Set>, <String>[, <String>])` TO result.
    APPEND `SimpleResolver#AscW#Function#15:9##<Integer> AscW(<String>)` TO result.
    APPEND `SimpleResolver#LTrim#Function#9:9##<String> LTrim(<String>)` TO result.
    APPEND `SimpleResolver#NPer#Function#7:7,7,7,7,5##<Numeric Expression> NPer(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Logical Expression>)` TO result.
    APPEND `SimpleResolver#Timer#Function#7:##<Numeric Expression> Timer()` TO result.
    APPEND `SimpleResolver#PPmt#Function#7:7,7,7,7##<Numeric Expression> PPmt(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#PPmt#Function#7:7,7,7,7,7##<Numeric Expression> PPmt(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#PPmt#Function#7:7,7,7,7,7,5##<Numeric Expression> PPmt(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, `
               && `<Logical Expression>)` TO result.
    APPEND `SimpleResolver#UCase#Function#9:9##<String> UCase(<String>)` TO result.
    APPEND `ExtractFunDef$1#Extract#Function###Extract(<Set>, <Hierarchy>[, <Hierarchy>...])` TO result.
    APPEND `SimpleResolver#DateValue#Function#18:18##<DateTime> DateValue(<DateTime>)` TO result.
    APPEND `OpeningClosingPeriodFunDef$1#OpeningPeriod#Function#6:;6:4;6:4,6##OpeningPeriod([<Level>[, <Member>]])` TO result.
    APPEND `ReflectiveMultiResolver#LinRegIntercept#Function#7:8,7;7:8,7,7##LinRegIntercept(<Set>, <Numeric Expression>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Tan#Function#7:7##<Numeric Expression> Tan(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Pi#Function#7:##<Numeric Expression> Pi()` TO result.
    APPEND `SimpleResolver#Sinh#Function#7:7##<Numeric Expression> Sinh(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#String#Function#9:15,9##<String> String(<Integer>, <String>)` TO result.
    APPEND `SimpleResolver#DDB#Function#7:7,7,7,7##<Numeric Expression> DDB(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#DDB#Function#7:7,7,7,7,7##<Numeric Expression> DDB(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Atn#Function#7:7##<Numeric Expression> Atn(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#FirstChild#Property#6:6##<Member>.FirstChild` TO result.
    APPEND `ReflectiveMultiResolver#Lead#Method#6:6,7##<Member>.Lead(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Hex#Function#9:13##<String> Hex(<Value>)` TO result.
    APPEND `SimpleResolver#SYD#Function#7:7,7,7,7##<Numeric Expression> SYD(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `XtdFunDef$ResolverImpl#Mtd#Function#8:;8:6##Mtd([<Member>])` TO result.
    APPEND `SimpleResolver#Int#Function#15:13##<Integer> Int(<Value>)` TO result.
    APPEND `SimpleResolver#-#Prefix#7:7##- <Numeric Expression>` TO result.
    APPEND `SimpleResolver#-#Prefix#8:8##- <Set>` TO result.
    APPEND `SimpleResolver#Sgn#Function#15:7##<Integer> Sgn(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Exp#Function#7:7##<Numeric Expression> Exp(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Day#Function#15:18##<Integer> Day(<DateTime>)` TO result.
    APPEND `AsFunDef$ResolverImpl#AS#Infix###null` TO result.
    APPEND `SimpleResolver#Sqr#Function#7:7##<Numeric Expression> Sqr(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Len#Function#7:9##<Numeric Expression> Len(<String>)` TO result.
    APPEND `SimpleResolver#Pmt#Function#7:7,7,7,7,5##<Numeric Expression> Pmt(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Logical Expression>)` TO result.
    APPEND `SimpleResolver#Fix#Function#15:13##<Integer> Fix(<Value>)` TO result.
    APPEND `SimpleResolver#Now#Function#18:##<DateTime> Now()` TO result.
    APPEND `SimpleResolver#Count#Property#7:8##<Set>.Count` TO result.
    APPEND `SimpleResolver#Hour#Function#15:18##<Integer> Hour(<DateTime>)` TO result.
    APPEND `SimpleResolver#RTrim#Function#9:9##<String> RTrim(<String>)` TO result.
    APPEND `ReflectiveMultiResolver#IS NULL#Postfix#5:6;5:4;5:3;5:2##<Expression> IS NULL` TO result.
    APPEND `ReflectiveMultiResolver#Variance#Function#7:8;7:8,7##Variance(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Radians#Function#7:7##<Numeric Expression> Radians(<Numeric Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#Head#Function#8:8;8:8,7##Head(<Set>[, < Numeric Expression >])` TO result.
    APPEND `SimpleResolver#PrevMember#Property#6:6##<Member>.PrevMember` TO result.
    APPEND `SimpleResolver#FV#Function#7:7,7,7##<Numeric Expression> FV(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#FV#Function#7:7,7,7,7##<Numeric Expression> FV(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#FV#Function#7:7,7,7,7,5##<Numeric Expression> FV(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Logical Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#NonEmptyCrossJoin#Function#8:8,8##NonEmptyCrossJoin(<Set1>, <Set2>)` TO result.
    APPEND `ReflectiveMultiResolver#IsEmpty#Function#5:9;5:7##IsEmpty(<Value Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#Correlation#Function#7:8,7;7:8,7,7##Correlation(<Set>, <Numeric Expression>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#IPmt#Function#7:7,7,7,7##<Numeric Expression> IPmt(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#IPmt#Function#7:7,7,7,7,7##<Numeric Expression> IPmt(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#IPmt#Function#7:7,7,7,7,7,5##<Numeric Expression> IPmt(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, `
               && `<Logical Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#Unorder#Function#8:8##Unorder(<Set>)` TO result.
    APPEND `SimpleResolver#Level_Number#Property#15:6##<Member>.Level_Number` TO result.
    APPEND `SimpleResolver#NPV#Function#7:7,1##<Numeric Expression> NPV(<Numeric Expression>, <Array>)` TO result.
    APPEND `StrToTupleFunDef$ResolverImpl#StrToTuple#Function#10:9##StrToTuple(<String Expression>)` TO result.
    APPEND `SimpleResolver#Power#Function#7:7,7##<Numeric Expression> Power(<Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#CurrentMember#Property#6:3##<Hierarchy>.CurrentMember` TO result.
    APPEND `SimpleResolver#FirstSibling#Property#6:6##<Member>.FirstSibling` TO result.
    APPEND `SimpleResolver#DateDiff#Function#7:9,18,18##<Numeric Expression> DateDiff(<String>, <DateTime>, <DateTime>)` TO result.
    APPEND `SimpleResolver#DateDiff#Function#7:9,18,18,15##<Numeric Expression> DateDiff(<String>, <DateTime>, <DateTime>, <Integer>)` TO result.
    APPEND `SimpleResolver#DateDiff#Function#7:9,18,18,15,15##<Numeric Expression> DateDiff(<String>, <DateTime>, <DateTime>, <Integer>, <Integer>)` TO result.
    APPEND `TopBottomCountFunDef$1#TopCount#Function#8:8,7,7;8:8,7##TopCount(<Set>, <Count>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#ParallelPeriod#Function#6:;6:4;6:4,7;6:4,7,6##ParallelPeriod([<Level>[, <Numeric Expression>[, <Member>]]])` TO result.
    APPEND `BuiltinFunTable$17#$AggregateChildren#Internal#7:3##$AggregateChildren(<Hierarchy>)` TO result.
    APPEND `ReflectiveMultiResolver#LinRegSlope#Function#7:8,7;7:8,7,7##LinRegSlope(<Set>, <Numeric Expression>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#DrillupLevel#Function#8:8;8:8,4#INCLUDE_CALC_MEMBERS#DrillupLevel(<Set>[, <Level>])` TO result.
    APPEND `ReflectiveMultiResolver#LinRegVariance#Function#7:8,7;7:8,7,7##LinRegVariance(<Set>, <Numeric Expression>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#LastPeriods#Function#8:7;8:7,6##LastPeriods(<Index> [, <Member>])` TO result.
    APPEND `TopBottomPercentSumFunDef$ResolverImpl#TopSum#Function#8:8,7,7##TopSum(<Set>, <Value>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#/#Infix#7:7,7##<Numeric Expression> / <Numeric Expression>` TO result.
    APPEND `ReflectiveMultiResolver#FirstQ#Function#7:8;7:8,7##FirstQ(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Cosh#Function#7:7##<Numeric Expression> Cosh(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#-#Infix#7:7,7##<Numeric Expression> - <Numeric Expression>` TO result.
    APPEND `SimpleResolver#-#Infix#8:8,8##<Set> - <Set>` TO result.
    APPEND `SimpleResolver#Name#Property#9:2##<Dimension>.Name` TO result.
    APPEND `SimpleResolver#Name#Property#9:3##<Hierarchy>.Name` TO result.
    APPEND `SimpleResolver#Name#Property#9:4##<Level>.Name` TO result.
    APPEND `SimpleResolver#Name#Property#9:6##<Member>.Name` TO result.
    APPEND `TopBottomCountFunDef$2#BottomCount#Function#8:8,7,7;8:8,7##BottomCount(<Set>, <Count>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#Descendants#Function#8:6;8:6,4;8:6,4,11;8:6,7;8:6,7,11;8:6,17,11#SELF,AFTER,BEFORE,BEFORE_AND_AFTER,SELF_AND_AFTER,SELF_AND_BEFORE,SELF_BEFORE_AFTER,LEAVES#`
               && `Descendants(<Member>[, <Level>[, <Desc_flag>]])` TO result.
    APPEND `ReflectiveMultiResolver#Descendants#Function#8:8;8:8,4;8:8,4,11;8:8,7;8:8,7,11;8:8,17,11#SELF,AFTER,BEFORE,BEFORE_AND_AFTER,SELF_AND_AFTER,SELF_AND_BEFORE,SELF_BEFORE_AFTER,LEAVES#`
               && `Descendants(<Set>[, <Level>[, <Desc_flag>]])` TO result.
    APPEND `SimpleResolver#OrderKey#Property#13:6##<Member>.OrderKey` TO result.
    APPEND `CoalesceEmptyFunDef$ResolverImpl#CoalesceEmpty#Function###CoalesceEmpty(<Value Expression>[, <Value Expression>...])` TO result.
    APPEND `SimpleResolver#Acos#Function#7:7##<Numeric Expression> Acos(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Acosh#Function#7:7##<Numeric Expression> Acosh(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Levels#Method#4:3,7##<Level> <Hierarchy>.Levels(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Levels#Method#4:3,9##<Level> <Hierarchy>.Levels(<String>)` TO result.
    APPEND `SimpleResolver#Levels#Function#4:9##<Level> Levels(<String>)` TO result.
    APPEND `ReflectiveMultiResolver#VarP#Function#7:8;7:8,7##VarP(<Set>[, <Numeric Expression>])` TO result.
    APPEND `OrderFunDef$ResolverImpl#Order#Function##ASC,DESC,BASC,BDESC#Order(<Set> {, <Key Specification>}...)` TO result.
    APPEND `SimpleResolver#Date#Function#18:##<DateTime> Date()` TO result.
    APPEND `SimpleResolver#ChrW#Function#9:15##<String> ChrW(<Integer>)` TO result.
    APPEND `OpeningClosingPeriodFunDef$2#ClosingPeriod#Function#6:;6:4;6:4,6;6:6##ClosingPeriod([<Level>[, <Member>]])` TO result.
    APPEND `ReflectiveMultiResolver#Format#Function#9:6,9;9:7,9;9:18,9##Format(<Expression>, <String Expression>)` TO result.
    APPEND `SimpleResolver#Atan2#Function#7:7,7##<Numeric Expression> Atan2(<Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Asin#Function#7:7##<Numeric Expression> Asin(<Numeric Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#LinRegR2#Function#7:8,7;7:8,7,7##LinRegR2(<Set>, <Numeric Expression>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#Percentile#Function#7:8,7,7##Percentile(<Set>, <Numeric Expression>, <Percent>)` TO result.
    APPEND `SimpleResolver#Month#Function#15:18##<Integer> Month(<DateTime>)` TO result.
    APPEND `SimpleResolver#CBool#Function#5:13##<Logical Expression> CBool(<Value>)` TO result.
    APPEND `SimpleResolver#Dimensions#Function#3:7##<Hierarchy> Dimensions(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Dimensions#Function#3:9##<Hierarchy> Dimensions(<String>)` TO result.
    APPEND `ReflectiveMultiResolver#NativizeSet#Function#8:8##NativizeSet(<Set>)` TO result.
    APPEND `ReflectiveMultiResolver#PeriodsToDate#Function#8:;8:4;8:4,6##PeriodsToDate([<Level>[, <Member>]])` TO result.
    APPEND `ReflectiveMultiResolver#StddevP#Function#7:8;7:8,7##StddevP(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Members#Function#6:9##<Member> Members(<String>)` TO result.
    APPEND `SimpleResolver#Distinct#Function#8:8##<Set> Distinct(<Set>)` TO result.
    APPEND `CrossJoinFunDef$ResolverImpl#Crossjoin#Function###Crossjoin(<Set1>, <Set2>[, <Set3>...])` TO result.
    APPEND `SimpleResolver#CByte#Function#15:13##<Integer> CByte(<Value>)` TO result.
    APPEND `SimpleResolver#*#Infix#7:7,7##<Numeric Expression> * <Numeric Expression>` TO result.
    APPEND `CrossJoinFunDef$StarCrossJoinResolver#*#Infix#8:8,8;8:6,8;8:8,6;8:6,6##<Set1> * <Set2>` TO result.
    APPEND `SimpleResolver#ValidMeasure#Function#7:10##<Numeric Expression> ValidMeasure(<Tuple>)` TO result.
    APPEND `SimpleResolver#InStr#Function#15:15,9,9##<Integer> InStr(<Integer>, <String>, <String>)` TO result.
    APPEND `SimpleResolver#InStr#Function#15:15,9,9,15##<Integer> InStr(<Integer>, <String>, <String>, <Integer>)` TO result.
    APPEND `SimpleResolver#InStr#Function#15:9,9##<Integer> InStr(<String>, <String>)` TO result.
    APPEND `SimpleResolver#Weekday#Function#15:18##<Integer> Weekday(<DateTime>)` TO result.
    APPEND `SimpleResolver#Weekday#Function#15:18,15##<Integer> Weekday(<DateTime>, <Integer>)` TO result.
    APPEND `SimpleResolver#+#Infix#7:7,7##<Numeric Expression> + <Numeric Expression>` TO result.
    APPEND `SimpleResolver#StrReverse#Function#9:9##<String> StrReverse(<String>)` TO result.
    APPEND `SimpleResolver##Empty#17:##` TO result.
    APPEND `SimpleResolver#LastChild#Property#6:6##<Member>.LastChild` TO result.
    APPEND `ReflectiveMultiResolver#Exists#Function#8:8,8##Exists(<Set1>, <Set2>])` TO result.
    APPEND `SimpleResolver#Dimension#Property#2:2##<Dimension>.Dimension` TO result.
    APPEND `SimpleResolver#Dimension#Property#2:3##<Hierarchy>.Dimension` TO result.
    APPEND `SimpleResolver#Dimension#Property#2:4##<Level>.Dimension` TO result.
    APPEND `SimpleResolver#Dimension#Property#2:6##<Member>.Dimension` TO result.
    APPEND `ReflectiveMultiResolver#Except#Function#8:8,8;8:8,8,11##Except(<Set1>, <Set2>[, ALL])` TO result.
    APPEND `SimpleResolver#PV#Function#7:7,7,7,7,5##<Numeric Expression> PV(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Logical Expression>)` TO result.
    APPEND `SimpleResolver#SqrtPi#Function#7:7##<Numeric Expression> SqrtPi(<Numeric Expression>)` TO result.
    APPEND `ParameterFunDef$ParameterResolver#Parameter#Function#9:73,11,9,73;9:73,11,9;7:73,11,7,73;7:73,11,7;6:73,3,6,73;6:73,3,6;8:73,3,8,73;8:73,3,8#NUMERIC,STRING#Parameter(<Name>, <Type>`
               && `, <DefaultValue>, <Description>, <Set>)` TO result.
    APPEND `SimpleResolver#CachedExists#Function#8:8,10,9##<Set> CachedExists(<Set>, <Tuple>, <String>)` TO result.
    APPEND `SimpleResolver#DefaultMember#Property#6:3##<Hierarchy>.DefaultMember` TO result.
    APPEND `SimpleResolver#Value#Property#7:6##<Member>.Value` TO result.
    APPEND `SimpleResolver#CalculatedChild#Method#6:6,9##<Member> <Member>.CalculatedChild(<String>)` TO result.
    APPEND `SimpleResolver#CurrentOrdinal#Property#15:8##<Set>.CurrentOrdinal` TO result.
    APPEND `SimpleResolver#Ordinal#Property#7:4##<Level>.Ordinal` TO result.
    APPEND `SimpleResolver#FormatCurrency#Function#9:13##<String> FormatCurrency(<Value>)` TO result.
    APPEND `SimpleResolver#FormatCurrency#Function#9:13,15##<String> FormatCurrency(<Value>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatCurrency#Function#9:13,15,15##<String> FormatCurrency(<Value>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatCurrency#Function#9:13,15,15,15##<String> FormatCurrency(<Value>, <Integer>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatCurrency#Function#9:13,15,15,15,15##<String> FormatCurrency(<Value>, <Integer>, <Integer>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#Trim#Function#9:9##<String> Trim(<String>)` TO result.
    APPEND `SimpleResolver#MonthName#Function#9:15,5##<String> MonthName(<Integer>, <Logical Expression>)` TO result.
    APPEND `ReflectiveMultiResolver#Stdev#Function#7:8;7:8,7##Stdev(<Set>[, <Numeric Expression>])` TO result.
    APPEND `ReflectiveMultiResolver#Ancestor#Function#6:6,4;6:6,7##Ancestor(<Member>, {<Level>|<Numeric Expression>})` TO result.
    APPEND `SimpleResolver#Left#Function#9:9,15##<String> Left(<String>, <Integer>)` TO result.
    APPEND `SimpleResolver#Filter#Function#8:8,5##<Set> Filter(<Set>, <Logical Expression>)` TO result.
    APPEND `SimpleResolver#Mid#Function#9:9,15##<String> Mid(<String>, <Integer>)` TO result.
    APPEND `SimpleResolver#Mid#Function#9:9,15,15##<String> Mid(<String>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#Minute#Function#15:18##<Integer> Minute(<DateTime>)` TO result.
    APPEND `SimpleResolver#NOT#Prefix#5:5##NOT <Logical Expression>` TO result.
    APPEND `SimpleResolver#InStrRev#Function#15:9,9##<Integer> InStrRev(<String>, <String>)` TO result.
    APPEND `SimpleResolver#InStrRev#Function#15:9,9,15##<Integer> InStrRev(<String>, <String>, <Integer>)` TO result.
    APPEND `SimpleResolver#InStrRev#Function#15:9,9,15,15##<Integer> InStrRev(<String>, <String>, <Integer>, <Integer>)` TO result.
    APPEND `DrilldownLevelTopBottomFunDef$1#DrilldownLevelTop#Function#8:8,7;8:8,7,4;8:8,7,4,7;8:8,7,17,7##DrilldownLevelTop(Set_Expression, Count [, [Level_Expression][, Numeric_Expression]])` TO result.
    APPEND `SimpleResolver#Time#Function#18:##<DateTime> Time()` TO result.
    APPEND `SimpleResolver#ChrB#Function#9:15##<String> ChrB(<Integer>)` TO result.
    APPEND `SimpleResolver#TypeName#Function#9:13##<String> TypeName(<Value>)` TO result.
    APPEND `SimpleResolver#Ascendants#Function#8:6##<Set> Ascendants(<Member>)` TO result.
    APPEND `ReflectiveMultiResolver#Sum#Function#7:8;7:8,7##Sum(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#IsDate#Function#5:13##<Logical Expression> IsDate(<Value>)` TO result.
    APPEND `SimpleResolver#Caption#Property#9:2##<Dimension>.Caption` TO result.
    APPEND `SimpleResolver#Caption#Property#9:3##<Hierarchy>.Caption` TO result.
    APPEND `SimpleResolver#Caption#Property#9:4##<Level>.Caption` TO result.
    APPEND `SimpleResolver#Caption#Property#9:6##<Member>.Caption` TO result.
    APPEND `TopBottomPercentSumFunDef$ResolverImpl#TopPercent#Function#8:8,7,7##TopPercent(<Set>, <Percentage>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#CDate#Function#18:13##<DateTime> CDate(<Value>)` TO result.
    APPEND `SimpleResolver#Children#Property#8:6##<Member>.Children` TO result.
    APPEND `SimpleResolver#Siblings#Property#8:6##<Member>.Siblings` TO result.
    APPEND `ReflectiveMultiResolver#ThirdQ#Function#7:8;7:8,7##ThirdQ(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Second#Function#15:18##<Integer> Second(<DateTime>)` TO result.
    APPEND `ReflectiveMultiResolver#DrilldownLevel#Function#8:8;8:8,4;8:8,17,7;8:8,4,11;8:8,17,7,11;8:8,17,17,11#INCLUDE_CALC_MEMBERS#DrilldownLevel(<Set>[, <Level>]) or DrilldownLevel(<Set>, `
               && `, <Index>)` TO result.
    APPEND `SimpleResolver#FormatDateTime#Function#9:18##<String> FormatDateTime(<DateTime>)` TO result.
    APPEND `SimpleResolver#FormatDateTime#Function#9:18,15##<String> FormatDateTime(<DateTime>, <Integer>)` TO result.
    APPEND `SimpleResolver#NextMember#Property#6:6##<Member>.NextMember` TO result.
    APPEND `ReflectiveMultiResolver#Rank#Function#15:10,8;15:10,8,7;15:6,8;15:6,8,7##Rank(<Tuple>, <Set> [, <Calc Expression>])` TO result.
    APPEND `SimpleResolver#Existing#Prefix#8:8##Existing <Set>` TO result.
    APPEND `ReflectiveMultiResolver#DrilldownMember#Function#8:8,8;8:8,8,11;8:8,8,17,17,11#RECURSIVE#DrilldownMember(<Set1>, <Set2>[, RECURSIVE])` TO result.
    APPEND `SimpleResolver#Degrees#Function#7:7##<Numeric Expression> Degrees(<Numeric Expression>)` TO result.
    APPEND `StrToSetFunDef$ResolverImpl#StrToSet#Function#8:9##StrToSet(<String Expression>)` TO result.
    APPEND `XtdFunDef$ResolverImpl#Ytd#Function#8:;8:6##Ytd([<Member>])` TO result.
    APPEND `CacheFunDef$CacheFunResolver#Cache#Function###Cache(<<Exp>>)` TO result.
    APPEND `XtdFunDef$ResolverImpl#Qtd#Function#8:;8:6##Qtd([<Member>])` TO result.
    APPEND `ReflectiveMultiResolver#IS EMPTY#Postfix#5:6;5:10##<Value Expression> IS EMPTY` TO result.
    APPEND `SimpleResolver#Tanh#Function#7:7##<Numeric Expression> Tanh(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#LastSibling#Property#6:6##<Member>.LastSibling` TO result.
    APPEND `SimpleResolver#AllMembers#Property#8:3##<Hierarchy>.AllMembers` TO result.
    APPEND `SimpleResolver#AllMembers#Property#8:4##<Level>.AllMembers` TO result.
    APPEND `SimpleResolver#Rate#Function#7:7,7,7##<Numeric Expression> Rate(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Rate#Function#7:7,7,7,7##<Numeric Expression> Rate(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>)` TO result.
    APPEND `SimpleResolver#Rate#Function#7:7,7,7,7,5##<Numeric Expression> Rate(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Logical Expression>)` TO result.
    APPEND `SimpleResolver#Rate#Function#7:7,7,7,7,5,7##<Numeric Expression> Rate(<Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Numeric Expression>, <Logical Expression>, `
               && `<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#FormatNumber#Function#9:13##<String> FormatNumber(<Value>)` TO result.
    APPEND `SimpleResolver#FormatNumber#Function#9:13,15##<String> FormatNumber(<Value>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatNumber#Function#9:13,15,15##<String> FormatNumber(<Value>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatNumber#Function#9:13,15,15,15##<String> FormatNumber(<Value>, <Integer>, <Integer>, <Integer>)` TO result.
    APPEND `SimpleResolver#FormatNumber#Function#9:13,15,15,15,15##<String> FormatNumber(<Value>, <Integer>, <Integer>, <Integer>, <Integer>)` TO result.
    APPEND `ReflectiveMultiResolver#Median#Function#7:8;7:8,7##Median(<Set>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#Mod#Function#7:13,13##<Numeric Expression> Mod(<Value>, <Value>)` TO result.
    APPEND `SimpleResolver#Members#Property#8:3##<Hierarchy>.Members` TO result.
    APPEND `SimpleResolver#Members#Property#8:4##<Level>.Members` TO result.
    APPEND `SimpleResolver#Unique_Name#Property#9:6##<Member>.Unique_Name` TO result.
    APPEND `SimpleResolver#TimeSerial#Function#18:15,15,15##<DateTime> TimeSerial(<Integer>, <Integer>, <Integer>)` TO result.
    APPEND `ReflectiveMultiResolver#CovarianceN#Function#7:8,7;7:8,7,7##CovarianceN(<Set>, <Numeric Expression>[, <Numeric Expression>])` TO result.
    APPEND `SimpleResolver#AscB#Function#15:9##<Integer> AscB(<String>)` TO result.
    APPEND `SimpleResolver#Asinh#Function#7:7##<Numeric Expression> Asinh(<Numeric Expression>)` TO result.
    APPEND `SimpleResolver#StripCalculatedMembers#Function#8:8##<Set> StripCalculatedMembers(<Set>)` TO result.
    APPEND `SetFunDef$ResolverImpl#{}#Braces###{<Member> [, <Member>...]}` TO result.
    APPEND `CastFunDef$ResolverImpl#Cast#Cast###Cast(<Expression> AS <Type>)` TO result.
    APPEND `SimpleResolver#Current#Property#10:8##<Set>.Current` TO result.
    APPEND `ReflectiveMultiResolver#Subset#Function#8:8,7;8:8,7,7##Subset(<Set>, <Start>[, <Count>])` TO result.
    APPEND `ReflectiveMultiResolver#ToggleDrillState#Function#8:8,8;8:8,8,11#RECURSIVE#ToggleDrillState(<Set1>, <Set2>[, RECURSIVE])` TO result.
    APPEND `SimpleResolver#DataMember#Property#6:6##<Member>.DataMember` TO result.
    APPEND `ReflectiveMultiResolver#Intersect#Function#8:8,8,11;8:8,8#ALL#Intersect(<Set1>, <Set2>[, ALL])` TO result.
    APPEND `SimpleResolver#IRR#Function#7:1##<Numeric Expression> IRR(<Array>)` TO result.
    APPEND `SimpleResolver#IRR#Function#7:1,7##<Numeric Expression> IRR(<Array>, <Numeric Expression>)` TO result.
    APPEND `PropertiesFunDef$ResolverImpl#Properties#Method###<Member>.Properties(<String Expression>)` TO result.
    APPEND `SimpleResolver#Chr#Function#9:15##<String> Chr(<Integer>)` TO result.
    APPEND `DrilldownLevelTopBottomFunDef$2#DrilldownLevelBottom#Function#8:8,7;8:8,7,4;8:8,7,4,7;8:8,7,17,7##DrilldownLevelBottom(Set_Expression, Count [, [Level_Expression][, Numeric_Express`
               && `ion]])` TO result.
    APPEND `SimpleResolver#DateAdd#Function#18:9,7,18##<DateTime> DateAdd(<String>, <Numeric Expression>, <DateTime>)` TO result.
    APPEND `ReflectiveMultiResolver#VarianceP#Function#7:8;7:8,7##VarianceP(<Set>[, <Numeric Expression>])` TO result.
    APPEND `UdfResolver#MATCHES#Infix#5:9,9##<String> MATCHES <String>` TO result.
    APPEND `UdfResolver#CurrentDateString#Function#9:9##<String> CurrentDateString(<String>)` TO result.
    APPEND `UdfResolver#Val#Function#7:7##<Numeric Expression> Val(<Numeric Expression>)` TO result.
    APPEND `UdfResolver#IN#Infix#5:6,8##<Member> IN <Set>` TO result.
    APPEND `UdfResolver#NullValue#Function#7:##<Numeric Expression> NullValue()` TO result.
    APPEND `UdfResolver#LastNonEmpty#Function#6:8,6##<Member> LastNonEmpty(<Set>, <Member>)` TO result.
    APPEND `UdfResolver#InverseNormal#Function#7:7##<Numeric Expression> InverseNormal(<Numeric Expression>)` TO result.
    APPEND `UdfResolver#CurrentDateMember#Function#6:3,9##<Member> CurrentDateMember(<Hierarchy>, <String>)` TO result.
    APPEND `UdfResolver#CurrentDateMember#Function#6:3,9,11#EXACT,BEFORE,AFTER#<Member> CurrentDateMember(<Hierarchy>, <String>, <Symbol>)` TO result.
  ENDMETHOD.

ENDCLASS.