*----------------------------------------------------------------------------------------------------------------------*
* olap4abap - XMLA server with an MDX engine for SAP BW               https://github.com/arcanist123/olap4abap
* Copyright (c) 2026 the olap4abap authors
*
* This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0,
* which is available at https://www.eclipse.org/legal/epl-2.0/
* SPDX-License-Identifier: EPL-2.0
*
* olap4abap contains code derived from Mondrian (Eclipse Public License 1.0): Copyright (C) 1998-2005 Julian Hyde,
* Copyright (C) 2005-2021 Hitachi Vantara and others, Copyright (C) 2021-2025 Sergei Semenkov. See the NOTICE file.
*----------------------------------------------------------------------------------------------------------------------*
"! MDX parser: the port of the reference's grammar MdxParser.jj (parser.MdxParserImpl, generated by JavaCC), one
"! method per production with the same lookahead decisions, and of the error handling of JavaccParserValidatorImpl: a
"! syntax error is "Syntax error at line L, column C, token 'T'" for the first token that does not fit. Tokens and
"! lexical errors come from ZZXXMLA1_CL_MDX_TOKEN_MANAGER. The result is the reference's parse tree: the statement with its
"! parts (Formula, QueryAxis, Subcube, ...) and the expressions as ZZXXMLA1_CL_MDX_NODE (Id, UnresolvedFunCall,
"! Literal), not yet resolved against a cube; resolving is the validator's job, as in the reference.
CLASS zzxxmla1_cl_mdx_parser DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
    TYPES ty_node TYPE REF TO zzxxmla1_cl_mdx_node.
    TYPES:
      BEGIN OF ty_member_property,
        name       TYPE string,
        expression TYPE ty_node,
      END OF ty_member_property,
      ty_t_member_property TYPE STANDARD TABLE OF ty_member_property WITH EMPTY KEY.
    TYPES:
      "! Formula: MEMBER or SET name AS expression
      BEGIN OF ty_formula,
        is_member  TYPE abap_bool,
        name       TYPE ty_node,   " an ID
        expression TYPE ty_node,
        properties TYPE ty_t_member_property,
      END OF ty_formula,
      ty_t_formula TYPE STANDARD TABLE OF ty_formula WITH EMPTY KEY.
    TYPES:
      "! QueryAxis
      BEGIN OF ty_axis,
        non_empty            TYPE abap_bool,
        expression           TYPE ty_node,
        ordinal              TYPE i,   " 0 COLUMNS, 1 ROWS, 2 PAGES, 3 CHAPTERS, 4 SECTIONS, then AXIS(n)
        dimension_properties TYPE zzxxmla1_cl_mdx_node=>ty_t_node,
      END OF ty_axis,
      ty_t_axis TYPE STANDARD TABLE OF ty_axis WITH EMPTY KEY.
    TYPES:
      "! Subcube: FROM cube, or FROM (SELECT axes FROM subcube WHERE slicer); the inner ones follow in the table, the last
      "! one names the cube
      BEGIN OF ty_subcube,
        cube_name TYPE string,
        axes      TYPE ty_t_axis,
        slicer    TYPE ty_node,
      END OF ty_subcube,
      ty_t_subcube TYPE STANDARD TABLE OF ty_subcube WITH EMPTY KEY.
    TYPES:
      "! Query (selectStatement)
      BEGIN OF ty_query,
        formulas        TYPE ty_t_formula,
        axes            TYPE ty_t_axis,
        cube            TYPE string,      " Subcube.getCubeName
        subcubes        TYPE ty_t_subcube,
        slicer          TYPE ty_node,
        cell_properties TYPE string_table,
      END OF ty_query.
    TYPES:
      BEGIN OF ty_update_clause,
        tuple      TYPE ty_node,
        value      TYPE ty_node,
        allocation TYPE string,   " NO_ALLOCATION, USE_EQUAL_ALLOCATION, ...
        weight     TYPE ty_node,
      END OF ty_update_clause,
      ty_t_update_clause TYPE STANDARD TABLE OF ty_update_clause WITH EMPTY KEY.
    TYPES:
      "! QueryPart: a statement of any kind
      BEGIN OF ty_statement,
        kind           TYPE string,   " SELECT, DRILLTHROUGH, EXPLAIN, DMV, CREATE_FORMULA, REFRESH, UPDATE, TRANSACTION
        explained      TYPE string,   " EXPLAIN: SELECT or DRILLTHROUGH
        query          TYPE ty_query, " SELECT, DRILLTHROUGH
        max_rows       TYPE i,        " DRILLTHROUGH
        first_rowset   TYPE i,
        return_list    TYPE zzxxmla1_cl_mdx_node=>ty_t_node,
        cube_name      TYPE string,   " CREATE_FORMULA, REFRESH, UPDATE
        formula        TYPE ty_formula,
        update_clauses TYPE ty_t_update_clause,
        dmv_table      TYPE string,   " DMV: SELECT columns FROM $SYSTEM.table WHERE condition
        dmv_columns    TYPE string_table,
        dmv_where      TYPE ty_node,
        command        TYPE string,   " TRANSACTION: BEGIN, COMMIT or ROLLBACK
      END OF ty_statement.

    "! statementEof
    CLASS-METHODS parse
      IMPORTING mdx           TYPE string
      RETURNING VALUE(result) TYPE ty_statement
      RAISING   zzxxmla1_cx_xmla.
    "! expressionEof
    CLASS-METHODS parse_expression
      IMPORTING mdx           TYPE string
      RETURNING VALUE(result) TYPE ty_node
      RAISING   zzxxmla1_cx_xmla.
    "! The statement as MDX, as the TestParser of ParserTest writes it.
    CLASS-METHODS to_mdx
      IMPORTING statement     TYPE ty_statement
      RETURNING VALUE(result) TYPE string.
    "! AxisOrdinal.name: COLUMNS, ROWS, PAGES, CHAPTERS, SECTIONS, AXIS(n).
    CLASS-METHODS axis_name
      IMPORTING ordinal       TYPE i
      RETURNING VALUE(result) TYPE string.

  PRIVATE SECTION.
    TYPES ty_segment TYPE zzxxmla1_cl_mdx_node=>ty_segment.
    TYPES ty_t_node TYPE zzxxmla1_cl_mdx_node=>ty_t_node.

    DATA token_manager TYPE REF TO zzxxmla1_cl_mdx_token_manager.
    DATA tokens        TYPE STANDARD TABLE OF zzxxmla1_cl_mdx_token_manager=>ty_token WITH EMPTY KEY.
    DATA consumed      TYPE i.   " the tokens read by the parser so far; the ones behind are lookahead

    METHODS constructor
      IMPORTING mdx TYPE string.

    " ---- tokens
    "! The kind of the token so many places ahead (1 is the next one), read when needed.
    METHODS kind
      IMPORTING ahead         TYPE i DEFAULT 1
      RETURNING VALUE(result) TYPE string
      RAISING   zzxxmla1_cx_xmla.
    "! jj_consume_token: the next token if it is of the kind, else a syntax error.
    METHODS consume
      IMPORTING expected      TYPE string
      RETURNING VALUE(result) TYPE zzxxmla1_cl_mdx_token_manager=>ty_token
      RAISING   zzxxmla1_cx_xmla.
    "! The syntax error at the next token.
    METHODS syntax_error
      RAISING zzxxmla1_cx_xmla.
    METHODS raise_error
      IMPORTING message TYPE string
      RAISING   zzxxmla1_cx_xmla.
    METHODS is_name_segment_start
      IMPORTING token_kind    TYPE string
      RETURNING VALUE(result) TYPE abap_bool.
    METHODS is_identifier_start
      IMPORTING token_kind    TYPE string
      RETURNING VALUE(result) TYPE abap_bool.
    METHODS is_atom_start
      IMPORTING token_kind    TYPE string
      RETURNING VALUE(result) TYPE abap_bool.
    METHODS is_factor_start
      IMPORTING token_kind    TYPE string
      RETURNING VALUE(result) TYPE abap_bool.
    METHODS is_expression_start
      IMPORTING token_kind    TYPE string
      RETURNING VALUE(result) TYPE abap_bool.
    METHODS is_numeric_literal
      IMPORTING token_kind    TYPE string
      RETURNING VALUE(result) TYPE abap_bool.

    " ---- LOOKAHEAD(dmvSelectStatement()): scans the tokens ahead without consuming them; a scan returns the
    " position (1 is the next token) behind what it matched, 0 if it does not match
    METHODS scan_dmv
      RETURNING VALUE(result) TYPE abap_bool
      RAISING   zzxxmla1_cx_xmla.
    METHODS scan_compound_id
      IMPORTING position      TYPE i
      RETURNING VALUE(result) TYPE i
      RAISING   zzxxmla1_cx_xmla.
    METHODS scan_identifier
      IMPORTING position      TYPE i
      RETURNING VALUE(result) TYPE i
      RAISING   zzxxmla1_cx_xmla.
    METHODS scan_name_segment
      IMPORTING position      TYPE i
      RETURNING VALUE(result) TYPE i
      RAISING   zzxxmla1_cx_xmla.

    " ---- helpers of the grammar
    CLASS-METHODS strip_quotes
      IMPORTING image         TYPE string
                prefix        TYPE string
                suffix        TYPE string
                quoted        TYPE string
      RETURNING VALUE(result) TYPE string.
    "! FunTable.isProperty: the functions with property syntax.
    CLASS-METHODS is_property
      IMPORTING name          TYPE string
      RETURNING VALUE(result) TYPE abap_bool.
    "! MdxParserImpl.createCall.
    METHODS create_call
      IMPORTING left          TYPE ty_node OPTIONAL
                segment       TYPE ty_segment
                args          TYPE ty_t_node OPTIONAL
                has_args      TYPE abap_bool
      RETURNING VALUE(result) TYPE ty_node.
    "! The name of the first segment of an ID, as ((Id.NameSegment) id.getElement(0)).name.
    CLASS-METHODS first_segment_name
      IMPORTING id            TYPE ty_node
      RETURNING VALUE(result) TYPE string.
    "! Util.implode: the segments with every name segment in brackets.
    CLASS-METHODS implode
      IMPORTING id            TYPE ty_node
      RETURNING VALUE(result) TYPE string.
    CLASS-METHODS formula_mdx
      IMPORTING formula       TYPE ty_formula
      RETURNING VALUE(result) TYPE string.
    CLASS-METHODS axis_mdx
      IMPORTING axis          TYPE ty_axis
      RETURNING VALUE(result) TYPE string.

    " ---- productions, named as in MdxParser.jj
    METHODS statement_eof RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
    METHODS expression_eof RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS identifier RETURNING VALUE(result) TYPE ty_segment RAISING zzxxmla1_cx_xmla.
    METHODS name_segment RETURNING VALUE(result) TYPE ty_segment RAISING zzxxmla1_cx_xmla.
    METHODS key_identifier RETURNING VALUE(result) TYPE ty_segment RAISING zzxxmla1_cx_xmla.
    METHODS amp_id RETURNING VALUE(result) TYPE zzxxmla1_cl_mdx_node=>ty_name_segment RAISING zzxxmla1_cx_xmla.
    METHODS keyword RETURNING VALUE(result) TYPE string RAISING zzxxmla1_cx_xmla.
    METHODS compound_id RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS unaliased_expression RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS term5 RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS term4 RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS term3 RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS term2 RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS term RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS factor RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS primary RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS segment_or_funcall
      IMPORTING left          TYPE ty_node
      RETURNING VALUE(result) TYPE ty_node
      RAISING   zzxxmla1_cx_xmla.
    METHODS numeric_literal RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS atom RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS case_expression RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS expression RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS expression_or_empty RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS exp_or_empty_list RETURNING VALUE(result) TYPE ty_t_node RAISING zzxxmla1_cx_xmla.
    METHODS exp_list RETURNING VALUE(result) TYPE ty_t_node RAISING zzxxmla1_cx_xmla.
    METHODS statement RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
    METHODS dmv_select_statement RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
    METHODS select_statement RETURNING VALUE(result) TYPE ty_query RAISING zzxxmla1_cx_xmla.
    METHODS select_subcube_clause RETURNING VALUE(result) TYPE ty_t_subcube RAISING zzxxmla1_cx_xmla.
    METHODS create_formula RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
    METHODS refresh_statement RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
    METHODS update_statement RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
    METHODS update_clause RETURNING VALUE(result) TYPE ty_update_clause RAISING zzxxmla1_cx_xmla.
    METHODS transaction_command_statement RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
    METHODS member_specification RETURNING VALUE(result) TYPE ty_formula RAISING zzxxmla1_cx_xmla.
    METHODS formula_expression RETURNING VALUE(result) TYPE ty_node RAISING zzxxmla1_cx_xmla.
    METHODS member_property_definition RETURNING VALUE(result) TYPE ty_member_property RAISING zzxxmla1_cx_xmla.
    METHODS set_specification RETURNING VALUE(result) TYPE ty_formula RAISING zzxxmla1_cx_xmla.
    METHODS axis_specification RETURNING VALUE(result) TYPE ty_axis RAISING zzxxmla1_cx_xmla.
    METHODS drillthrough_statement RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
    METHODS return_item_list RETURNING VALUE(result) TYPE ty_t_node RAISING zzxxmla1_cx_xmla.
    METHODS explain_statement RETURNING VALUE(result) TYPE ty_statement RAISING zzxxmla1_cx_xmla.
ENDCLASS.

CLASS zzxxmla1_cl_mdx_parser IMPLEMENTATION.

  METHOD parse.
    result = NEW zzxxmla1_cl_mdx_parser( mdx )->statement_eof( ).
  ENDMETHOD.

  METHOD parse_expression.
    result = NEW zzxxmla1_cl_mdx_parser( mdx )->expression_eof( ).
  ENDMETHOD.

  METHOD constructor.
    token_manager = NEW #( mdx ).
  ENDMETHOD.

  METHOD kind.
    WHILE lines( tokens ) < consumed + ahead.
      APPEND token_manager->next_token( ) TO tokens.
    ENDWHILE.
    result = tokens[ consumed + ahead ]-kind.
  ENDMETHOD.

  METHOD consume.
    IF kind( ) <> expected.
      syntax_error( ).
    ENDIF.
    consumed = consumed + 1.
    result = tokens[ consumed ].
  ENDMETHOD.

  METHOD syntax_error.
    " JavaccParserValidatorImpl.convertException: the token after the last one consumed
    kind( ).
    DATA(token) = tokens[ consumed + 1 ].
    raise_error( |Syntax error at line { token-begin_line }, column { token-begin_column }, token '{ token-image }'| ).
  ENDMETHOD.

  METHOD raise_error.
    zzxxmla1_cx_xmla=>raise_code( kind = `Server` code = `00HSBB01` text = `XMLA SOAP Body processing error`
                                  description = |olap4abap Error:{ message }| ).
  ENDMETHOD.

  METHOD is_name_segment_start.
    result = xsdbool( token_kind = `DIMENSION` OR token_kind = `PROPERTIES` OR token_kind = `ATSIGN`
                      OR token_kind = `ID` OR token_kind = `QUOTED_ID` ).
  ENDMETHOD.

  METHOD is_identifier_start.
    result = xsdbool( is_name_segment_start( token_kind ) = abap_true
                      OR token_kind = `AMP_QUOTED_ID` OR token_kind = `AMP_UNQUOTED_ID` ).
  ENDMETHOD.

  METHOD is_numeric_literal.
    result = xsdbool( token_kind = `UNSIGNED_INTEGER_LITERAL` OR token_kind = `APPROX_NUMERIC_LITERAL`
                      OR token_kind = `DECIMAL_NUMERIC_LITERAL` ).
  ENDMETHOD.

  METHOD is_atom_start.
    result = xsdbool( is_name_segment_start( token_kind ) = abap_true OR is_numeric_literal( token_kind ) = abap_true
                      OR token_kind = `CASE` OR token_kind = `CAST` OR token_kind = `NULL` OR token_kind = `LBRACE`
                      OR token_kind = `LPAREN` OR token_kind = `SINGLE_QUOTED_STRING`
                      OR token_kind = `DOUBLE_QUOTED_STRING` ).
  ENDMETHOD.

  METHOD is_factor_start.
    result = xsdbool( is_atom_start( token_kind ) = abap_true
                      OR token_kind = `EXISTING` OR token_kind = `MINUS` OR token_kind = `PLUS` ).
  ENDMETHOD.

  METHOD is_expression_start.
    result = xsdbool( is_factor_start( token_kind ) = abap_true OR token_kind = `NOT` ).
  ENDMETHOD.

  METHOD scan_dmv.
    " LOOKAHEAD(dmvSelectStatement()): SELECT [compoundId {, compoundId}] FROM $SYSTEM . nameSegment
    IF kind( 1 ) <> `SELECT`.
      RETURN.
    ENDIF.
    DATA(position) = 2.
    DATA(next) = scan_compound_id( position ).
    IF next > 0.
      position = next.
      WHILE kind( position ) = `COMMA`.
        next = scan_compound_id( position + 1 ).
        IF next = 0.
          EXIT.
        ENDIF.
        position = next.
      ENDWHILE.
    ENDIF.
    IF kind( position ) <> `FROM` OR kind( position + 1 ) <> `$SYSTEM` OR kind( position + 2 ) <> `DOT`.
      RETURN.
    ENDIF.
    result = xsdbool( scan_name_segment( position + 3 ) > 0 ).
  ENDMETHOD.

  METHOD scan_compound_id.
    result = scan_identifier( position ).
    WHILE result > 0 AND kind( result ) = `DOT`.
      DATA(next) = scan_identifier( result + 1 ).
      IF next = 0.
        EXIT.
      ENDIF.
      result = next.
    ENDWHILE.
  ENDMETHOD.

  METHOD scan_identifier.
    result = scan_name_segment( position ).
    IF result = 0 AND ( kind( position ) = `AMP_QUOTED_ID` OR kind( position ) = `AMP_UNQUOTED_ID` ).
      result = position + 1.
      WHILE kind( result ) = `AMP_QUOTED_ID` OR kind( result ) = `AMP_UNQUOTED_ID`.
        result = result + 1.
      ENDWHILE.
    ENDIF.
  ENDMETHOD.

  METHOD scan_name_segment.
    CASE kind( position ).
      WHEN `DIMENSION` OR `PROPERTIES` OR `ID` OR `QUOTED_ID`.
        result = position + 1.
      WHEN `ATSIGN`.
        IF kind( position + 1 ) = `ID`.
          result = position + 2.
        ENDIF.
    ENDCASE.
  ENDMETHOD.

  METHOD strip_quotes.
    result = substring( val = image off = strlen( prefix ) len = strlen( image ) - strlen( prefix ) - strlen( suffix ) ).
    result = replace( val = result sub = quoted with = suffix occ = 0 ).
  ENDMETHOD.

  METHOD is_property.
    result = zzxxmla1_cl_mdx_funtable=>instance( )->is_property( name ).
  ENDMETHOD.

  METHOD create_call.
    DATA(name) = COND string( WHEN segment-quoting <> zzxxmla1_cl_mdx_node=>c_quoting-key THEN segment-name ).
    IF has_args = abap_true.
      IF left IS BOUND.
        " method syntax: x.foo(arg1, arg2) or x.foo()
        DATA(all) = VALUE ty_t_node( ( left ) ).
        APPEND LINES OF args TO all.
        result = zzxxmla1_cl_mdx_node=>create_call( name = name syntax = zzxxmla1_cl_mdx_node=>c_syntax-method args = all ).
      ELSE.
        " function syntax: foo(arg1, arg2) or foo()
        result = zzxxmla1_cl_mdx_node=>create_call( name = name syntax = zzxxmla1_cl_mdx_node=>c_syntax-function
                                                    args = args ).
      ENDIF.
      RETURN.
    ENDIF.

    " member syntax foo.bar or property syntax foo.RESERVED_WORD
    DATA(call) = abap_false.
    DATA(syntax) = VALUE string( ).
    CASE segment-quoting.
      WHEN zzxxmla1_cl_mdx_node=>c_quoting-unquoted.
        syntax = zzxxmla1_cl_mdx_node=>c_syntax-property.
        call = is_property( name ).
      WHEN zzxxmla1_cl_mdx_node=>c_quoting-quoted.
        syntax = zzxxmla1_cl_mdx_node=>c_syntax-quoted_property.
      WHEN OTHERS.
        syntax = zzxxmla1_cl_mdx_node=>c_syntax-ampersand_quoted_property.
    ENDCASE.
    IF left IS BOUND AND left->kind = zzxxmla1_cl_mdx_node=>c_kind-id AND call = abap_false.
      result = left->append( segment ).
    ELSEIF left IS NOT BOUND.
      result = zzxxmla1_cl_mdx_node=>create_id( VALUE #( ( segment ) ) ).
    ELSE.
      result = zzxxmla1_cl_mdx_node=>create_call( name = name syntax = syntax args = VALUE #( ( left ) ) ).
    ENDIF.
  ENDMETHOD.

  METHOD first_segment_name.
    result = id->segments[ 1 ]-name.
  ENDMETHOD.

  METHOD implode.
    LOOP AT id->segments INTO DATA(segment).
      IF sy-tabix > 1.
        result = result && `.`.
      ENDIF.
      IF segment-quoting = zzxxmla1_cl_mdx_node=>c_quoting-unquoted.
        result = result && zzxxmla1_cl_mdx_node=>quote_identifier( segment-name ).
      ELSE.
        result = result && zzxxmla1_cl_mdx_node=>unparse_segment( segment ).
      ENDIF.
    ENDLOOP.
  ENDMETHOD.

  METHOD axis_name.
    result = SWITCH #( ordinal WHEN 0 THEN `COLUMNS` WHEN 1 THEN `ROWS` WHEN 2 THEN `PAGES` WHEN 3 THEN `CHAPTERS`
                               WHEN 4 THEN `SECTIONS` ELSE |AXIS({ ordinal })| ).
  ENDMETHOD.

  METHOD to_mdx.
    DATA(lf) = cl_abap_char_utilities=>newline.
    IF statement-kind = `EXPLAIN`.
      result = `explain plan for` && lf.
    ENDIF.
    DATA(drillthrough) = xsdbool( statement-kind = `DRILLTHROUGH` OR statement-explained = `DRILLTHROUGH` ).
    IF drillthrough = abap_true.
      result = result && `drillthrough`.
      IF statement-max_rows > 0.
        result = |{ result } maxrows { statement-max_rows }|.
      ENDIF.
      IF statement-first_rowset > 0.
        result = |{ result } firstrowset { statement-first_rowset }|.
      ENDIF.
      result = result && lf.
    ENDIF.
    LOOP AT statement-query-formulas INTO DATA(formula).
      result = result && COND #( WHEN sy-tabix = 1 THEN `with ` ELSE `  ` ) && formula_mdx( formula ) && lf.
    ENDLOOP.
    result = result && `select `.
    DATA(count) = lines( statement-query-axes ).
    LOOP AT statement-query-axes INTO DATA(axis).
      result = result && axis_mdx( axis ) && COND #( WHEN sy-tabix < count THEN `,` && lf && `  ` ELSE lf ).
    ENDLOOP.
    result = |{ result }from [{ statement-query-cube }]{ lf }|.
    IF statement-query-slicer IS BOUND.
      result = |{ result }where { statement-query-slicer->unparse( ) }{ lf }|.
    ENDIF.
    LOOP AT statement-query-cell_properties INTO DATA(cell_property).
      result = result && cell_property.
    ENDLOOP.
    IF drillthrough = abap_true AND statement-return_list IS NOT INITIAL.
      result = result && ` return  return `.
      LOOP AT statement-return_list INTO DATA(item).
        result = result && COND #( WHEN sy-tabix > 1 THEN `, ` ) && item->unparse( ).
      ENDLOOP.
    ENDIF.
  ENDMETHOD.

  METHOD formula_mdx.
    result = |{ COND #( WHEN formula-is_member = abap_true THEN `member` ELSE `set` ) } { formula-name->unparse( ) } as '|
          && |{ formula-expression->unparse( ) }'|.
    LOOP AT formula-properties INTO DATA(property).
      result = |{ result }, { property-name } = { property-expression->unparse( ) }|.
    ENDLOOP.
  ENDMETHOD.

  METHOD axis_mdx.
    IF axis-non_empty = abap_true.
      result = `NON EMPTY `.
    ENDIF.
    result = result && axis-expression->unparse( ).
    LOOP AT axis-dimension_properties INTO DATA(property).
      result = result && COND #( WHEN sy-tabix = 1 THEN ` DIMENSION PROPERTIES ` ELSE `, ` ) && property->unparse( ).
    ENDLOOP.
    result = |{ result } ON { axis_name( axis-ordinal ) }|.
  ENDMETHOD.

  METHOD statement_eof.
    result = statement( ).
    consume( `EOF` ).
  ENDMETHOD.

  METHOD expression_eof.
    result = expression( ).
    consume( `EOF` ).
  ENDMETHOD.

  METHOD identifier.
    DATA(next) = kind( ).
    IF is_name_segment_start( next ) = abap_true.
      result = name_segment( ).
    ELSEIF next = `AMP_QUOTED_ID` OR next = `AMP_UNQUOTED_ID`.
      result = key_identifier( ).
    ELSE.
      syntax_error( ).
    ENDIF.
  ENDMETHOD.

  METHOD name_segment.
    CASE kind( ).
      WHEN `DIMENSION` OR `PROPERTIES`.
        " a non-reserved keyword taken as an identifier
        result = VALUE #( name = keyword( ) quoting = zzxxmla1_cl_mdx_node=>c_quoting-unquoted ).
      WHEN `ID`.
        result = VALUE #( name = consume( `ID` )-image quoting = zzxxmla1_cl_mdx_node=>c_quoting-unquoted ).
      WHEN `ATSIGN`.
        consume( `ATSIGN` ).
        result = VALUE #( name = `@` && consume( `ID` )-image quoting = zzxxmla1_cl_mdx_node=>c_quoting-unquoted ).
      WHEN `QUOTED_ID`.
        result = VALUE #( name    = strip_quotes( image = consume( `QUOTED_ID` )-image prefix = `[` suffix = `]` quoted = `]]` )
                          quoting = zzxxmla1_cl_mdx_node=>c_quoting-quoted ).
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
  ENDMETHOD.

  METHOD key_identifier.
    " for example &foo&[1]&bar in [x].&foo&[1]&bar.[y]
    result-quoting = zzxxmla1_cl_mdx_node=>c_quoting-key.
    DO.
      APPEND amp_id( ) TO result-keys.
      IF kind( ) <> `AMP_QUOTED_ID` AND kind( ) <> `AMP_UNQUOTED_ID`.
        EXIT.
      ENDIF.
    ENDDO.
  ENDMETHOD.

  METHOD amp_id.
    CASE kind( ).
      WHEN `AMP_QUOTED_ID`.
        result = VALUE #( name    = strip_quotes( image = consume( `AMP_QUOTED_ID` )-image prefix = `&[` suffix = `]`
                                                  quoted = `]]` )
                          quoting = zzxxmla1_cl_mdx_node=>c_quoting-quoted ).
      WHEN `AMP_UNQUOTED_ID`.
        result = VALUE #( name    = substring( val = consume( `AMP_UNQUOTED_ID` )-image off = 1 )
                          quoting = zzxxmla1_cl_mdx_node=>c_quoting-unquoted ).
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
  ENDMETHOD.

  METHOD keyword.
    CASE kind( ).
      WHEN `DIMENSION`.
        consume( `DIMENSION` ).
        result = `Dimension`.
      WHEN `PROPERTIES`.
        consume( `PROPERTIES` ).
        result = `Properties`.
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
  ENDMETHOD.

  METHOD compound_id.
    DATA(segments) = VALUE zzxxmla1_cl_mdx_node=>ty_t_segment( ( identifier( ) ) ).
    WHILE kind( ) = `DOT`.
      consume( `DOT` ).
      APPEND identifier( ) TO segments.
    ENDWHILE.
    result = zzxxmla1_cl_mdx_node=>create_id( segments ).
  ENDMETHOD.

  METHOD unaliased_expression.
    result = term5( ).
    DO.
      DATA(next) = kind( ).
      CASE next.
        WHEN `OR` OR `XOR`.
          consume( next ).
          result = zzxxmla1_cl_mdx_node=>create_call( name = next syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                      args = VALUE #( ( result ) ( term5( ) ) ) ).
        WHEN `COLON`.
          " range m1 : m2 yields a set of members
          consume( next ).
          result = zzxxmla1_cl_mdx_node=>create_call( name = `:` syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                      args = VALUE #( ( result ) ( term5( ) ) ) ).
        WHEN OTHERS.
          EXIT.
      ENDCASE.
    ENDDO.
  ENDMETHOD.

  METHOD term5.
    result = term4( ).
    WHILE kind( ) = `AND`.
      consume( `AND` ).
      result = zzxxmla1_cl_mdx_node=>create_call( name = `AND` syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                  args = VALUE #( ( result ) ( term4( ) ) ) ).
    ENDWHILE.
  ENDMETHOD.

  METHOD term4.
    IF kind( ) = `NOT`.
      consume( `NOT` ).
      result = zzxxmla1_cl_mdx_node=>create_call( name = `NOT` syntax = zzxxmla1_cl_mdx_node=>c_syntax-prefix
                                                  args = VALUE #( ( term4( ) ) ) ).
    ELSEIF is_factor_start( kind( ) ) = abap_true.
      result = term3( ).
    ELSE.
      syntax_error( ).
    ENDIF.
  ENDMETHOD.

  METHOD term3.
    result = term2( ).
    DO.
      DATA(next) = kind( ).
      CASE next.
        WHEN `EQ` OR `NE` OR `LT` OR `GT` OR `LE` OR `GE`.
          " e.g. 1 < 5
          DATA(operator) = consume( next )-image.
          result = zzxxmla1_cl_mdx_node=>create_call( name = operator syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                      args = VALUE #( ( result ) ( term2( ) ) ) ).
        WHEN `IS` OR `MATCHES` OR `NOT` OR `IN`.
          IF next = `IS` AND kind( 2 ) = `NULL`.
            " LOOKAHEAD(2) <IS> <NULL>: NULL is a literal too, x IS NULL wins
            consume( `IS` ).
            consume( `NULL` ).
            result = zzxxmla1_cl_mdx_node=>create_call( name = `IS NULL` syntax = zzxxmla1_cl_mdx_node=>c_syntax-postfix
                                                        args = VALUE #( ( result ) ) ).
          ELSEIF next = `IS` AND is_factor_start( kind( 2 ) ) = abap_true.
            " LOOKAHEAD(2) <IS> term2()
            consume( `IS` ).
            result = zzxxmla1_cl_mdx_node=>create_call( name = `IS` syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                        args = VALUE #( ( result ) ( term2( ) ) ) ).
          ELSEIF next = `IS`.
            consume( `IS` ).
            consume( `EMPTY` ).
            result = zzxxmla1_cl_mdx_node=>create_call( name = `IS EMPTY` syntax = zzxxmla1_cl_mdx_node=>c_syntax-postfix
                                                        args = VALUE #( ( result ) ) ).
          ELSEIF next = `MATCHES`.
            consume( `MATCHES` ).
            result = zzxxmla1_cl_mdx_node=>create_call( name = `MATCHES` syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                        args = VALUE #( ( result ) ( term2( ) ) ) ).
          ELSEIF next = `NOT` AND kind( 2 ) = `MATCHES`.
            " LOOKAHEAD(2) <NOT> <MATCHES>
            consume( `NOT` ).
            consume( `MATCHES` ).
            DATA(matches) = zzxxmla1_cl_mdx_node=>create_call( name = `MATCHES` syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                               args = VALUE #( ( result ) ( term2( ) ) ) ).
            result = zzxxmla1_cl_mdx_node=>create_call( name = `NOT` syntax = zzxxmla1_cl_mdx_node=>c_syntax-prefix
                                                        args = VALUE #( ( matches ) ) ).
          ELSEIF next = `IN`.
            consume( `IN` ).
            result = zzxxmla1_cl_mdx_node=>create_call( name = `IN` syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                        args = VALUE #( ( result ) ( term2( ) ) ) ).
          ELSE.
            consume( `NOT` ).
            consume( `IN` ).
            DATA(in) = zzxxmla1_cl_mdx_node=>create_call( name = `IN` syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                          args = VALUE #( ( result ) ( term2( ) ) ) ).
            result = zzxxmla1_cl_mdx_node=>create_call( name = `NOT` syntax = zzxxmla1_cl_mdx_node=>c_syntax-prefix
                                                        args = VALUE #( ( in ) ) ).
          ENDIF.
        WHEN OTHERS.
          EXIT.
      ENDCASE.
    ENDDO.
  ENDMETHOD.

  METHOD term2.
    result = term( ).
    DO.
      DATA(next) = kind( ).
      DATA(operator) = SWITCH string( next WHEN `PLUS` THEN `+` WHEN `MINUS` THEN `-` WHEN `CONCAT` THEN `||` ).
      IF operator IS INITIAL.
        EXIT.
      ENDIF.
      consume( next ).
      result = zzxxmla1_cl_mdx_node=>create_call( name = operator syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                  args = VALUE #( ( result ) ( term( ) ) ) ).
    ENDDO.
  ENDMETHOD.

  METHOD term.
    result = factor( ).
    DO.
      DATA(next) = kind( ).
      DATA(operator) = SWITCH string( next WHEN `ASTERISK` THEN `*` WHEN `SOLIDUS` THEN `/` ).
      IF operator IS INITIAL.
        EXIT.
      ENDIF.
      consume( next ).
      result = zzxxmla1_cl_mdx_node=>create_call( name = operator syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                  args = VALUE #( ( result ) ( factor( ) ) ) ).
    ENDDO.
  ENDMETHOD.

  METHOD factor.
    CASE kind( ).
      WHEN `PLUS`.
        consume( `PLUS` ).
        result = primary( ).
      WHEN `MINUS`.
        consume( `MINUS` ).
        result = zzxxmla1_cl_mdx_node=>create_call( name = `-` syntax = zzxxmla1_cl_mdx_node=>c_syntax-prefix
                                                    args = VALUE #( ( primary( ) ) ) ).
      WHEN `EXISTING`.
        consume( `EXISTING` ).
        result = zzxxmla1_cl_mdx_node=>create_call( name = `Existing` syntax = zzxxmla1_cl_mdx_node=>c_syntax-prefix
                                                    args = VALUE #( ( primary( ) ) ) ).
      WHEN OTHERS.
        IF is_atom_start( kind( ) ) = abap_false.
          syntax_error( ).
        ENDIF.
        result = primary( ).
    ENDCASE.
  ENDMETHOD.

  METHOD primary.
    result = atom( ).
    WHILE kind( ) = `DOT`.
      consume( `DOT` ).
      result = segment_or_funcall( result ).
    ENDWHILE.
  ENDMETHOD.

  METHOD segment_or_funcall.
    DATA args TYPE ty_t_node.
    DATA(has_args) = abap_false.
    DATA(segment) = identifier( ).
    IF kind( ) = `LPAREN`.
      consume( `LPAREN` ).
      has_args = abap_true.
      IF kind( ) <> `RPAREN`.
        args = exp_or_empty_list( ).
      ENDIF.
      consume( `RPAREN` ).
    ENDIF.
    result = create_call( left = left segment = segment args = args has_args = has_args ).
  ENDMETHOD.

  METHOD numeric_literal.
    DATA(next) = kind( ).
    IF is_numeric_literal( next ) = abap_false.
      syntax_error( ).
    ENDIF.
    result = zzxxmla1_cl_mdx_node=>create_numeric( consume( next )-image ).
  ENDMETHOD.

  METHOD atom.
    DATA list TYPE ty_t_node.
    DATA has_args TYPE abap_bool.
    DATA(next) = kind( ).
    CASE next.
      WHEN `SINGLE_QUOTED_STRING`.
        result = zzxxmla1_cl_mdx_node=>create_string(
                   strip_quotes( image = consume( next )-image prefix = `'` suffix = `'` quoted = `''` ) ).
      WHEN `DOUBLE_QUOTED_STRING`.
        result = zzxxmla1_cl_mdx_node=>create_string(
                   strip_quotes( image = consume( next )-image prefix = `"` suffix = `"` quoted = `""` ) ).
      WHEN `UNSIGNED_INTEGER_LITERAL` OR `APPROX_NUMERIC_LITERAL` OR `DECIMAL_NUMERIC_LITERAL`.
        result = numeric_literal( ).
      WHEN `NULL`.
        consume( `NULL` ).
        result = zzxxmla1_cl_mdx_node=>create_null( ).
      WHEN `CAST`.
        consume( `CAST` ).
        consume( `LPAREN` ).
        DATA(value) = unaliased_expression( ).
        consume( `AS` ).
        DATA(type) = name_segment( ).
        consume( `RPAREN` ).
        result = zzxxmla1_cl_mdx_node=>create_call( name = `CAST` syntax = zzxxmla1_cl_mdx_node=>c_syntax-cast
                   args = VALUE #( ( value ) ( zzxxmla1_cl_mdx_node=>create_symbol( type-name ) ) ) ).
      WHEN `LPAREN`.
        " ([Sales], [Time]) is a tuple, ([Sales]) and (5) are just expressions
        consume( `LPAREN` ).
        list = exp_list( ).
        consume( `RPAREN` ).
        result = zzxxmla1_cl_mdx_node=>create_call( name = `()` syntax = zzxxmla1_cl_mdx_node=>c_syntax-parentheses
                                                    args = list ).
      WHEN `LBRACE`.
        " a set built from sets and tuples
        consume( `LBRACE` ).
        IF kind( ) <> `RBRACE`.
          IF is_expression_start( kind( ) ) = abap_false.
            syntax_error( ).
          ENDIF.
          list = exp_list( ).
        ENDIF.
        consume( `RBRACE` ).
        result = zzxxmla1_cl_mdx_node=>create_call( name = `{}` syntax = zzxxmla1_cl_mdx_node=>c_syntax-braces
                                                    args = list ).
      WHEN `CASE`.
        result = case_expression( ).
      WHEN OTHERS.
        IF is_name_segment_start( next ) = abap_false.
          syntax_error( ).
        ENDIF.
        " function call foo(a, b) or whiz!bang!foo(a, b), the qualifiers before ! are ignored; properties x.PROP and
        " methods exp.meth(a) are in primary
        DATA(segment) = name_segment( ).
        WHILE kind( ) = `BANG`.
          consume( `BANG` ).
          segment = name_segment( ).
        ENDWHILE.
        IF kind( ) = `LPAREN`.
          consume( `LPAREN` ).
          has_args = abap_true.
          IF kind( ) <> `RPAREN`.
            list = exp_or_empty_list( ).
          ENDIF.
          consume( `RPAREN` ).
        ENDIF.
        result = create_call( segment = segment args = list has_args = has_args ).
    ENDCASE.
  ENDMETHOD.

  METHOD case_expression.
    DATA list TYPE ty_t_node.
    DATA(match) = abap_false.
    consume( `CASE` ).
    IF is_expression_start( kind( ) ) = abap_true.
      match = abap_true.
      APPEND expression( ) TO list.
    ENDIF.
    WHILE kind( ) = `WHEN`.
      consume( `WHEN` ).
      APPEND expression( ) TO list.
      consume( `THEN` ).
      APPEND expression( ) TO list.
    ENDWHILE.
    IF kind( ) = `ELSE`.
      consume( `ELSE` ).
      APPEND expression( ) TO list.
    ENDIF.
    consume( `END` ).
    result = zzxxmla1_cl_mdx_node=>create_call( name   = COND #( WHEN match = abap_true THEN `_CaseMatch` ELSE `_CaseTest` )
                                                syntax = zzxxmla1_cl_mdx_node=>c_syntax-case
                                                args   = list ).
  ENDMETHOD.

  METHOD expression.
    result = unaliased_expression( ).
    WHILE kind( ) = `AS`.
      consume( `AS` ).
      DATA(alias) = zzxxmla1_cl_mdx_node=>create_id( VALUE #( ( identifier( ) ) ) ).
      result = zzxxmla1_cl_mdx_node=>create_call( name = `AS` syntax = zzxxmla1_cl_mdx_node=>c_syntax-infix
                                                  args = VALUE #( ( result ) ( alias ) ) ).
    ENDWHILE.
  ENDMETHOD.

  METHOD expression_or_empty.
    IF is_expression_start( kind( ) ) = abap_true.
      result = expression( ).
    ELSE.
      result = zzxxmla1_cl_mdx_node=>create_call( name = `` syntax = zzxxmla1_cl_mdx_node=>c_syntax-empty ).
    ENDIF.
  ENDMETHOD.

  METHOD exp_or_empty_list.
    " some of the expressions may be empty; used for function arguments
    APPEND expression_or_empty( ) TO result.
    WHILE kind( ) = `COMMA`.
      consume( `COMMA` ).
      APPEND expression_or_empty( ) TO result.
    ENDWHILE.
  ENDMETHOD.

  METHOD exp_list.
    APPEND expression( ) TO result.
    WHILE kind( ) = `COMMA`.
      consume( `COMMA` ).
      APPEND expression( ) TO result.
    ENDWHILE.
  ENDMETHOD.

  METHOD statement.
    IF scan_dmv( ) = abap_true.
      result = dmv_select_statement( ).
      RETURN.
    ENDIF.
    CASE kind( ).
      WHEN `SELECT` OR `WITH`.
        result = VALUE #( kind = `SELECT` query = select_statement( ) ).
      WHEN `CREATE`.
        result = create_formula( ).
      WHEN `DRILLTHROUGH`.
        result = drillthrough_statement( ).
      WHEN `EXPLAIN`.
        result = explain_statement( ).
      WHEN `REFRESH`.
        result = refresh_statement( ).
      WHEN `UPDATE`.
        result = update_statement( ).
      WHEN `BEGIN` OR `COMMIT` OR `ROLLBACK`.
        result = transaction_command_statement( ).
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
  ENDMETHOD.

  METHOD dmv_select_statement.
    result-kind = `DMV`.
    consume( `SELECT` ).
    IF is_identifier_start( kind( ) ) = abap_true.
      APPEND first_segment_name( compound_id( ) ) TO result-dmv_columns.
      WHILE kind( ) = `COMMA`.
        consume( `COMMA` ).
        APPEND first_segment_name( compound_id( ) ) TO result-dmv_columns.
      ENDWHILE.
    ENDIF.
    consume( `FROM` ).
    consume( `$SYSTEM` ).
    consume( `DOT` ).
    result-dmv_table = name_segment( )-name.
    IF kind( ) = `WHERE`.
      consume( `WHERE` ).
      result-dmv_where = expression( ).
    ENDIF.
  ENDMETHOD.

  METHOD select_statement.
    IF kind( ) = `WITH`.
      consume( `WITH` ).
      DO.
        CASE kind( ).
          WHEN `MEMBER`.
            APPEND member_specification( ) TO result-formulas.
          WHEN `SET`.
            APPEND set_specification( ) TO result-formulas.
          WHEN OTHERS.
            syntax_error( ).
        ENDCASE.
        IF kind( ) <> `MEMBER` AND kind( ) <> `SET`.
          EXIT.
        ENDIF.
      ENDDO.
    ENDIF.
    consume( `SELECT` ).
    IF is_expression_start( kind( ) ) = abap_true OR kind( ) = `NON`.
      APPEND axis_specification( ) TO result-axes.
      WHILE kind( ) = `COMMA`.
        consume( `COMMA` ).
        APPEND axis_specification( ) TO result-axes.
      ENDWHILE.
    ENDIF.
    consume( `FROM` ).
    result-subcubes = select_subcube_clause( ).
    result-cube = result-subcubes[ lines( result-subcubes ) ]-cube_name.
    IF kind( ) = `WHERE`.
      consume( `WHERE` ).
      result-slicer = expression( ).
    ENDIF.
    IF kind( ) = `CELL` OR kind( ) = `PROPERTIES`.
      IF kind( ) = `CELL`.
        consume( `CELL` ).
      ENDIF.
      consume( `PROPERTIES` ).
      APPEND implode( compound_id( ) ) TO result-cell_properties.
      WHILE kind( ) = `COMMA`.
        consume( `COMMA` ).
        APPEND implode( compound_id( ) ) TO result-cell_properties.
      ENDWHILE.
    ENDIF.
  ENDMETHOD.

  METHOD select_subcube_clause.
    DATA subcube TYPE ty_subcube.
    DATA(next) = kind( ).
    IF is_identifier_start( next ) = abap_true.
      result = VALUE #( ( cube_name = first_segment_name( compound_id( ) ) ) ).
    ELSEIF next = `LPAREN`.
      consume( `LPAREN` ).
      consume( `SELECT` ).
      IF is_expression_start( kind( ) ) = abap_true OR kind( ) = `NON`.
        APPEND axis_specification( ) TO subcube-axes.
        WHILE kind( ) = `COMMA`.
          consume( `COMMA` ).
          APPEND axis_specification( ) TO subcube-axes.
        ENDWHILE.
      ELSEIF kind( ) = `ASTERISK`.
        consume( `ASTERISK` ).
      ENDIF.
      consume( `FROM` ).
      DATA(inner) = select_subcube_clause( ).
      IF kind( ) = `WHERE`.
        consume( `WHERE` ).
        subcube-slicer = expression( ).
      ENDIF.
      consume( `RPAREN` ).
      result = VALUE #( ( subcube ) ).
      APPEND LINES OF inner TO result.
    ELSE.
      syntax_error( ).
    ENDIF.
  ENDMETHOD.

  METHOD create_formula.
    result-kind = `CREATE_FORMULA`.
    consume( `CREATE` ).
    consume( `SESSION` ).
    CASE kind( ).
      WHEN `MEMBER`.
        consume( `MEMBER` ).
        result-formula-is_member = abap_true.
      WHEN `SET`.
        consume( `SET` ).
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
    result-cube_name = name_segment( )-name.
    consume( `DOT` ).
    result-formula-name = compound_id( ).
    consume( `AS` ).
    result-formula-expression = formula_expression( ).
    WHILE kind( ) = `COMMA`.
      consume( `COMMA` ).
      DATA(property) = member_property_definition( ).
      " a set keeps no properties
      IF result-formula-is_member = abap_true.
        APPEND property TO result-formula-properties.
      ENDIF.
    ENDWHILE.
  ENDMETHOD.

  METHOD refresh_statement.
    result-kind = `REFRESH`.
    consume( `REFRESH` ).
    consume( `CUBE` ).
    result-cube_name = first_segment_name( compound_id( ) ).
  ENDMETHOD.

  METHOD update_statement.
    result-kind = `UPDATE`.
    consume( `UPDATE` ).
    IF kind( ) = `CUBE`.
      consume( `CUBE` ).
    ENDIF.
    result-cube_name = first_segment_name( compound_id( ) ).
    consume( `SET` ).
    APPEND update_clause( ) TO result-update_clauses.
    WHILE kind( ) = `COMMA`.
      consume( `COMMA` ).
      APPEND update_clause( ) TO result-update_clauses.
    ENDWHILE.
  ENDMETHOD.

  METHOD update_clause.
    result-tuple = primary( ).
    consume( `EQ` ).
    result-value = unaliased_expression( ).
    result-allocation = `NO_ALLOCATION`.
    DATA(next) = kind( ).
    CASE next.
      WHEN `USE_EQUAL_ALLOCATION` OR `USE_EQUAL_INCREMENT`.
        consume( next ).
        result-allocation = next.
      WHEN `USE_WEIGHTED_ALLOCATION` OR `USE_WEIGHTED_INCREMENT`.
        consume( next ).
        result-allocation = next.
        IF kind( ) = `BY`.
          consume( `BY` ).
          result-weight = unaliased_expression( ).
        ENDIF.
    ENDCASE.
  ENDMETHOD.

  METHOD transaction_command_statement.
    result-kind = `TRANSACTION`.
    DATA(next) = kind( ).
    CASE next.
      WHEN `BEGIN` OR `COMMIT` OR `ROLLBACK`.
        consume( next ).
        result-command = next.
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
    next = kind( ).
    CASE next.
      WHEN `TRANSACTION` OR `TRAN`.
        consume( next ).
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
  ENDMETHOD.

  METHOD member_specification.
    " MEMBER name AS expression [, property = expression ...]
    consume( `MEMBER` ).
    result-is_member = abap_true.
    result-name = compound_id( ).
    consume( `AS` ).
    result-expression = formula_expression( ).
    WHILE kind( ) = `COMMA`.
      consume( `COMMA` ).
      APPEND member_property_definition( ) TO result-properties.
    ENDWHILE.
  ENDMETHOD.

  METHOD formula_expression.
    IF kind( ) = `SINGLE_QUOTED_STRING`.
      " the archaic WITH MEMBER m AS '<expr>': the string is parsed on its own by expression(), not to its end
      DATA(inner) = strip_quotes( image = consume( `SINGLE_QUOTED_STRING` )-image prefix = `'` suffix = `'` quoted = `''` ).
      result = NEW zzxxmla1_cl_mdx_parser( inner )->expression( ).
    ELSEIF is_expression_start( kind( ) ) = abap_true.
      result = unaliased_expression( ).
    ELSE.
      syntax_error( ).
    ENDIF.
  ENDMETHOD.

  METHOD member_property_definition.
    result-name = name_segment( )-name.
    consume( `EQ` ).
    result-expression = expression( ).
  ENDMETHOD.

  METHOD set_specification.
    consume( `SET` ).
    result-name = compound_id( ).
    consume( `AS` ).
    result-expression = formula_expression( ).
  ENDMETHOD.

  METHOD axis_specification.
    " [NON EMPTY] set [[DIMENSION] PROPERTIES id, ...] ON axis
    DATA number TYPE ty_node.
    IF kind( ) = `NON`.
      consume( `NON` ).
      consume( `EMPTY` ).
      result-non_empty = abap_true.
    ENDIF.
    result-expression = expression( ).
    IF kind( ) = `DIMENSION` OR kind( ) = `PROPERTIES`.
      IF kind( ) = `DIMENSION`.
        consume( `DIMENSION` ).
      ENDIF.
      consume( `PROPERTIES` ).
      APPEND compound_id( ) TO result-dimension_properties.
      WHILE kind( ) = `COMMA`.
        consume( `COMMA` ).
        APPEND compound_id( ) TO result-dimension_properties.
      ENDWHILE.
    ENDIF.
    consume( `ON` ).
    DATA(next) = kind( ).
    CASE next.
      WHEN `COLUMNS`.
        consume( next ).
        result-ordinal = 0.
      WHEN `ROWS`.
        consume( next ).
        result-ordinal = 1.
      WHEN `PAGES`.
        consume( next ).
        result-ordinal = 2.
      WHEN `SECTIONS`.
        consume( next ).
        result-ordinal = 4.
      WHEN `CHAPTERS`.
        consume( next ).
        result-ordinal = 3.
      WHEN `AXIS` OR `UNSIGNED_INTEGER_LITERAL` OR `APPROX_NUMERIC_LITERAL` OR `DECIMAL_NUMERIC_LITERAL`.
        IF next = `AXIS`.
          consume( `AXIS` ).
          consume( `LPAREN` ).
          number = numeric_literal( ).
          consume( `RPAREN` ).
        ELSE.
          number = numeric_literal( ).
        ENDIF.
        " the ordinals of the standard axes are 0 to 4, higher ones are allowed, negative ones mean special cases
        DATA(amount) = number->number.
        IF amount < 0 OR amount <> trunc( amount ) OR amount > 2147483647.
          raise_error( |Invalid axis specification. The axis number must be a non-negative integer, but it was |
                    && |{ zzxxmla1_cl_mdx_format=>format( value = amount pattern = `#,##0.###` ) }.| ).
        ENDIF.
        result-ordinal = amount.
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
  ENDMETHOD.

  METHOD drillthrough_statement.
    result-kind = `DRILLTHROUGH`.
    consume( `DRILLTHROUGH` ).
    IF kind( ) = `MAXROWS`.
      consume( `MAXROWS` ).
      result-max_rows = consume( `UNSIGNED_INTEGER_LITERAL` )-image.
    ENDIF.
    IF kind( ) = `FIRSTROWSET`.
      consume( `FIRSTROWSET` ).
      result-first_rowset = consume( `UNSIGNED_INTEGER_LITERAL` )-image.
    ENDIF.
    result-query = select_statement( ).
    IF kind( ) = `RETURN`.
      consume( `RETURN` ).
      result-return_list = return_item_list( ).
    ENDIF.
  ENDMETHOD.

  METHOD return_item_list.
    APPEND compound_id( ) TO result.
    WHILE kind( ) = `COMMA`.
      consume( `COMMA` ).
      APPEND compound_id( ) TO result.
    ENDWHILE.
  ENDMETHOD.

  METHOD explain_statement.
    consume( `EXPLAIN` ).
    consume( `PLAN` ).
    consume( `FOR` ).
    CASE kind( ).
      WHEN `SELECT` OR `WITH`.
        result = VALUE #( kind = `SELECT` query = select_statement( ) ).
      WHEN `DRILLTHROUGH`.
        result = drillthrough_statement( ).
      WHEN OTHERS.
        syntax_error( ).
    ENDCASE.
    result-explained = result-kind.
    result-kind = `EXPLAIN`.
  ENDMETHOD.

ENDCLASS.