*----------------------------------------------------------------------------------------------------------------------*
* olap4abap - XMLA server with an MDX engine for SAP BW               https://github.com/arcanist123/olap4abap
* Copyright (c) 2026 the olap4abap authors
*
* This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0,
* which is available at https://www.eclipse.org/legal/epl-2.0/
* SPDX-License-Identifier: EPL-2.0
*
* olap4abap contains code derived from Mondrian (Eclipse Public License 1.0): Copyright (C) 1998-2005 Julian Hyde,
* Copyright (C) 2005-2021 Hitachi Vantara and others, Copyright (C) 2021-2025 Sergei Semenkov. See the NOTICE file.
*----------------------------------------------------------------------------------------------------------------------*
"! The files of the schema builder (web/schema/), generated by scripts/generate-web-app-abap.py: do not
"! edit, change web/schema/ and generate again. ZZXXMLA1_CL_SETUP writes them below /schema/.
CLASS zzxxmla1_cl_web_app_files DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    TYPES:
      BEGIN OF ty_file,
        path    TYPE string,
        content TYPE string,
      END OF ty_file,
      ty_t_file TYPE STANDARD TABLE OF ty_file WITH EMPTY KEY.

    "! The files with their paths on the server.
    CLASS-METHODS files
      RETURNING VALUE(result) TYPE ty_t_file.
  PROTECTED SECTION.
  PRIVATE SECTION.
    "! /schema/app.css
    CLASS-METHODS file_1
      RETURNING VALUE(result) TYPE string.
    "! /schema/app.js
    CLASS-METHODS file_2
      RETURNING VALUE(result) TYPE string.
    "! /schema/index.html
    CLASS-METHODS file_3
      RETURNING VALUE(result) TYPE string.
    "! /schema/vendor/htm-preact-standalone.mjs
    CLASS-METHODS file_4
      RETURNING VALUE(result) TYPE string.
ENDCLASS.



CLASS zzxxmla1_cl_web_app_files IMPLEMENTATION.

  METHOD files.
    result = VALUE #(
      ( path = `/schema/app.css` content = file_1( ) )
      ( path = `/schema/app.js` content = file_2( ) )
      ( path = `/schema/index.html` content = file_3( ) )
      ( path = `/schema/vendor/htm-preact-standalone.mjs` content = file_4( ) ) ).
  ENDMETHOD.

  METHOD file_1.
    DATA parts TYPE string_table.
    APPEND |/* The schema builder (docs/schema-generator.md, UI). No build step: this file is what the server serves. */\n:root \{\n  --bg: #f6f7f9;\n  --panel: #ffffff;\n  --sunken: #eef0f3;| TO parts.
    APPEND |\n  --line: #d9dde3;\n  --text: #1c2128;\n  --muted: #5f6b7a;\n  --accent: #1f6feb;\n  --accent-text: #ffffff;\n  --accent-soft: #e5efff;\n  --ok: #1a7f37;\n  --ok-soft: #e6f4ea;\n| TO parts.
    APPEND |  --warn: #9a6700;\n  --warn-soft: #fff4d6;\n  --err: #cf222e;\n  --err-soft: #ffebe9;\n  --mono: ui-monospace, "Cascadia Mono", Consolas, "SF Mono", Menlo, monospace;\n  --radius:| TO parts.
    APPEND | 6px;\n  color-scheme: light;\n\}\n@media (prefers-color-scheme: dark) \{\n  :root \{\n    --bg: #0f1216;\n    --panel: #161b22;\n    --sunken: #1d232b;\n    --line: #2d343d;\n    | TO parts.
    APPEND |--text: #e2e6eb;\n    --muted: #8d97a5;\n    --accent: #4c8dff;\n    --accent-text: #0b1220;\n    --accent-soft: #1b2a44;\n    --ok: #4ac26b;\n    --ok-soft: #13291b;\n    --warn: | TO parts.
    APPEND |#d4a72c;\n    --warn-soft: #2e2510;\n    --err: #ff7b72;\n    --err-soft: #3a1717;\n    color-scheme: dark;\n  \}\n\}\n\n* \{ box-sizing: border-box; \}\nhtml, body \{ margin: 0; h| TO parts.
    APPEND |eight: 100%; \}\nbody \{\n  background: var(--bg);\n  color: var(--text);\n  font: 14px/1.45 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;\n\}\n/* the page does not scr| TO parts.
    APPEND |oll, its panes do (the outline stays in view) */\n#app \{ height: 100%; display: flex; flex-direction: column; \}\n.page \{ flex: 1; min-height: 0; overflow: auto; \}\n.banner \{ p| TO parts.
    APPEND |adding: 8px 16px; border-bottom: 1px solid var(--line); background: var(--err-soft); color: var(--err); white-space: pre-wrap; \}\n.boot \{ padding: 24px; color: var(--muted); \}\n| TO parts.
    APPEND |\nh1, h2, h3 \{ margin: 0; font-weight: 600; \}\nh1 \{ font-size: 16px; \}\nh2 \{ font-size: 15px; \}\nh3 \{ font-size: 13px; text-transform: uppercase; letter-spacing: .04em; colo| TO parts.
    APPEND |r: var(--muted); \}\ncode, .mono \{ font-family: var(--mono); font-size: 12.5px; \}\n.muted \{ color: var(--muted); \}\n.small \{ font-size: 12px; \}\na \{ color: var(--accent); \}| TO parts.
    APPEND |\n\n/* top bar */\n.topbar \{\n  display: flex; align-items: center; gap: 12px; flex-wrap: wrap;\n  padding: 8px 16px; background: var(--panel); border-bottom: 1px solid var(--line| TO parts.
    APPEND |);\n  position: sticky; top: 0; z-index: 5;\n\}\n.topbar .title \{ display: flex; align-items: baseline; gap: 8px; min-width: 0; \}\n.topbar .title .src \{ color: var(--muted); whi| TO parts.
    APPEND |te-space: nowrap; overflow: hidden; text-overflow: ellipsis; \}\n.topbar .spacer \{ flex: 1; \}\n.topbar label.inline \{ display: flex; align-items: center; gap: 6px; color: var(--| TO parts.
    APPEND |muted); \}\n\n/* controls */\nbutton, .button \{\n  font: inherit; border: 1px solid var(--line); background: var(--panel); color: var(--text);\n  border-radius: var(--radius); pad| TO parts.
    APPEND |ding: 4px 10px; cursor: pointer; white-space: nowrap;\n\}\nbutton:hover:not(:disabled) \{ border-color: var(--muted); \}\nbutton:disabled \{ opacity: .5; cursor: default; \}\nbutto| TO parts.
    APPEND |n.primary \{ background: var(--accent); border-color: var(--accent); color: var(--accent-text); font-weight: 600; \}\nbutton.danger \{ color: var(--err); \}\nbutton.icon \{ padding| TO parts.
    APPEND |: 2px 7px; line-height: 1.2; \}\nbutton.link \{ border: 0; background: none; color: var(--accent); padding: 0; \}\ninput[type=text], input[type=search], select, textarea \{\n  font| TO parts.
    APPEND |: inherit; color: var(--text); background: var(--panel);\n  border: 1px solid var(--line); border-radius: var(--radius); padding: 4px 8px; min-width: 0;\n\}\ninput[type=text]:focus| TO parts.
    APPEND |, input[type=search]:focus, select:focus, textarea:focus, button:focus-visible \{\n  outline: 2px solid var(--accent); outline-offset: -1px;\n\}\ninput.invalid \{ border-color: var| TO parts.
    APPEND |(--err); \}\ninput[readonly] \{ background: var(--sunken); color: var(--muted); \}\n.field-error \{ color: var(--err); font-size: 12px; \}\n\n/* status pill */\n.status \{ display:| TO parts.
    APPEND | inline-flex; align-items: center; gap: 6px; border-radius: 999px; padding: 2px 10px; font-size: 12.5px;\n  max-width: 46ch; white-space: nowrap; overflow: hidden; text-overflow: e| TO parts.
    APPEND |llipsis; \}\n.status.ok \{ background: var(--ok-soft); color: var(--ok); \}\n.status.err \{ background: var(--err-soft); color: var(--err); \}\n.status.busy \{ background: var(--su| TO parts.
    APPEND |nken); color: var(--muted); \}\n.status.warn \{ background: var(--warn-soft); color: var(--warn); \}\n\n/* start page */\n.start \{ display: grid; grid-template-columns: minmax(0, | TO parts.
    APPEND |1fr) minmax(0, 1.4fr); gap: 16px; padding: 16px; align-items: start; \}\n@media (max-width: 860px) \{ .start \{ grid-template-columns: minmax(0, 1fr); \} \}\n.card \{ background: v| TO parts.
    APPEND |ar(--panel); border: 1px solid var(--line); border-radius: var(--radius); \}\n.card > header \{ display: flex; align-items: center; gap: 8px; padding: 10px 12px; border-bottom: 1px| TO parts.
    APPEND | solid var(--line); \}\n.card > header .spacer \{ flex: 1; \}\n.card .body \{ padding: 12px; \}\n.card .scroll \{ max-height: calc(100vh - 170px); overflow: auto; \}\n\ntable \{ bo| TO parts.
    APPEND |rder-collapse: collapse; width: 100%; \}\nth, td \{ text-align: left; padding: 5px 8px; border-bottom: 1px solid var(--line); vertical-align: middle; \}\nth \{ font-weight: 600; co| TO parts.
    APPEND |lor: var(--muted); font-size: 12px; position: sticky; top: 0; background: var(--panel); z-index: 1; \}\ntr.clickable \{ cursor: pointer; \}\ntr.clickable:hover td \{ background: va| TO parts.
    APPEND |r(--accent-soft); \}\ntd.num \{ text-align: right; font-variant-numeric: tabular-nums; \}\ntd.actions \{ white-space: nowrap; text-align: right; \}\ntd input[type=text], td select | TO parts.
    APPEND |\{ width: 100%; \}\n.kind \{ font-size: 11.5px; border: 1px solid var(--line); border-radius: 4px; padding: 0 5px; color: var(--muted); \}\n\n/* editor */\n.editor \{ flex: 1; disp| TO parts.
    APPEND |lay: grid; grid-template-columns: 260px minmax(0, 1fr); min-height: 0; \}\n@media (max-width: 760px) \{ .editor \{ grid-template-columns: minmax(0, 1fr); grid-template-rows: auto m| TO parts.
    APPEND |inmax(0, 1fr); \} .tree \{ max-height: 40vh; border-right: 0; border-bottom: 1px solid var(--line); \} \}\n.tree \{ background: var(--panel); border-right: 1px solid var(--line); o| TO parts.
    APPEND |verflow: auto; padding: 8px 0; \}\n.tree .group \{ padding: 10px 14px 4px; \}\n.tree .item \{\n  display: flex; align-items: center; gap: 6px; width: 100%; text-align: left; border| TO parts.
    APPEND |: 0; border-radius: 0;\n  background: none; padding: 4px 14px; color: var(--text);\n\}\n.tree .item.sub \{ padding-left: 28px; \}\n.tree .item:hover \{ background: var(--sunken); | TO parts.
    APPEND |\}\n.tree .item.selected \{ background: var(--accent-soft); color: var(--accent); font-weight: 600; \}\n.tree .item .badge \{ margin-left: auto; font-size: 11px; color: var(--muted| TO parts.
    APPEND |); font-weight: 400; \}\n.main \{ overflow: auto; min-width: 0; \}\n.tabs \{ display: flex; gap: 2px; padding: 8px 16px 0; border-bottom: 1px solid var(--line); background: var(--p| TO parts.
    APPEND |anel); \}\n.tabs button \{ border: 0; border-bottom: 2px solid transparent; border-radius: 0; background: none; padding: 6px 12px; color: var(--muted); \}\n.tabs button.active \{ b| TO parts.
    APPEND |order-bottom-color: var(--accent); color: var(--text); font-weight: 600; \}\n.pane \{ padding: 16px; display: flex; flex-direction: column; gap: 16px; max-width: 1100px; \}\n\n.for| TO parts.
    APPEND |m \{ display: grid; grid-template-columns: max-content minmax(0, 1fr); gap: 8px 12px; align-items: center; max-width: 640px; \}\n.form > label \{ color: var(--muted); \}\n.row \{ d| TO parts.
    APPEND |isplay: flex; align-items: center; gap: 8px; flex-wrap: wrap; \}\n.switch \{ display: inline-flex; align-items: center; gap: 6px; cursor: pointer; \}\n\n.section \{ background: var| TO parts.
    APPEND |(--panel); border: 1px solid var(--line); border-radius: var(--radius); \}\n.section > header \{ display: flex; align-items: center; gap: 8px; padding: 8px 12px; border-bottom: 1px| TO parts.
    APPEND | solid var(--line); flex-wrap: wrap; \}\n.section > header .spacer \{ flex: 1; \}\n.section > .body \{ padding: 12px; display: flex; flex-direction: column; gap: 10px; \}\n.section| TO parts.
    APPEND | table th \{ position: static; \}\n.section .scroll-x \{ overflow-x: auto; \}\n\n.hier \{ border: 1px solid var(--line); border-radius: var(--radius); background: var(--bg); \}\n.h| TO parts.
    APPEND |ier > header \{ display: flex; align-items: center; gap: 8px; padding: 8px 10px; flex-wrap: wrap; border-bottom: 1px solid var(--line); \}\n.hier > .body \{ padding: 10px; display:| TO parts.
    APPEND | flex; flex-direction: column; gap: 8px; \}\n.props \{ padding: 4px 0 4px 24px; display: flex; flex-direction: column; gap: 4px; \}\n.props select, .props input[type=text] \{ width| TO parts.
    APPEND |: auto; \}\n\n.notice \{ border-radius: var(--radius); padding: 8px 12px; \}\n.notice.err \{ background: var(--err-soft); color: var(--err); white-space: pre-wrap; \}\n.notice.warn| TO parts.
    APPEND | \{ background: var(--warn-soft); color: var(--warn); \}\n.notice.ok \{ background: var(--ok-soft); color: var(--ok); \}\n.notice.info \{ background: var(--sunken); color: var(--te| TO parts.
    APPEND |xt); \}\nul.plain \{ margin: 0; padding-left: 18px; \}\n\ntextarea.xml \{ width: 100%; min-height: calc(100vh - 230px); font-family: var(--mono); font-size: 12.5px; line-height: 1.| TO parts.
    APPEND |5;\n  white-space: pre; tab-size: 2; resize: vertical; \}\n\n/* dialog */\n.backdrop \{ position: fixed; inset: 0; background: rgba(0, 0, 0, .35); display: flex; align-items: cente| TO parts.
    APPEND |r; justify-content: center; padding: 16px; z-index: 20; \}\n.dialog \{ background: var(--panel); border: 1px solid var(--line); border-radius: 8px; width: min(560px, 100%); max-hei| TO parts.
    APPEND |ght: 90vh; overflow: auto;\n  box-shadow: 0 12px 40px rgba(0, 0, 0, .25); \}\n.dialog > header \{ padding: 14px 16px 0; \}\n.dialog > .body \{ padding: 12px 16px; display: flex; fl| TO parts.
    APPEND |ex-direction: column; gap: 10px; \}\n.dialog > footer \{ padding: 0 16px 14px; display: flex; justify-content: flex-end; gap: 8px; \}\n| TO parts.
    result = concat_lines_of( parts ).
  ENDMETHOD.

  METHOD file_2.
    DATA parts TYPE string_table.
    APPEND |// The schema builder (docs/schema-generator.md, UI): proposes a Mondrian schema for a BW InfoProvider or reopens an\n// accepted one, lets the user edit it and accepts it through | TO parts.
    APPEND |the API below this folder (ZZXXMLA1_CL_SCHEMA_API).\n// The schema XML is the model: it is edited as a DOM (DOMParser) and sent back as text, the server never parses JSON.\n// No b| TO parts.
    APPEND |uild step: Preact with htm, vendored as one ES module; this file is what the server serves.\nimport \{ html, render, useState, useEffect, useMemo, useRef, useCallback \} from './ve| TO parts.
    APPEND |ndor/htm-preact-standalone.mjs';\n\nconst TIME_TYPES = ['TimeYears', 'TimeHalfYears', 'TimeQuarters', 'TimeMonths', 'TimeWeeks', 'TimeDays', 'TimeHours',\n  'TimeMinutes', 'TimeSec| TO parts.
    APPEND |onds', 'TimeUndefined'];\n// what the engine evaluates (ZZXXMLA1_CL_MDX_FACTS): count, everything else is summed\nconst AGGREGATORS = ['sum', 'count'];\nconst FORMATS = ['Standard'| TO parts.
    APPEND |, '#,###', '#,##0', '#,##0.00', 'Currency', 'Percent', '0.0%'];\n// a catalog name is a file name too (ZZXXMLA1_CL_SCHEMA_API, check_catalog_name)\nconst CATALOG_NAME = /^[A-Za-z0-| TO parts.
    APPEND |9_-][A-Za-z0-9_.-]*$/;\n\n// ---------------------------------------------------------------------------------------------------------- API\n\nconst client = new URLSearchParams(lo| TO parts.
    APPEND |cation.search).get('sap-client');\n\nasync function api(method, resource, params = \{\}, body) \{\n  const query = new URLSearchParams(params);\n  if (client) query.set('sap-client| TO parts.
    APPEND |', client);\n  const response = await fetch(`api/$\{resource\}?$\{query\}`, \{\n    method,\n    body,\n    headers: body == null ? \{\} : \{ 'Content-Type': 'application/xml; char| TO parts.
    APPEND |set=utf-8' \},\n  \});\n  let data;\n  try \{\n    data = await response.json();\n  \} catch \{\n    throw new Error(`$\{response.status\} $\{response.statusText\}`);\n  \}\n  if (| TO parts.
    APPEND |!response.ok) throw new Error(data.error \|\| `$\{response.status\} $\{response.statusText\}`);\n  return data;\n\}\n\n// ----------------------------------------------------------| TO parts.
    APPEND |------------------------------------------------ XML\n\nfunction parseXml(text) \{\n  const doc = new DOMParser().parseFromString(text, 'application/xml');\n  const error = doc.get| TO parts.
    APPEND |ElementsByTagName('parsererror')[0];\n  if (error) throw new Error(error.textContent.trim().split('\\n').filter(Boolean).slice(0, 2).join(' '));\n  if (doc.documentElement.tagName | TO parts.
    APPEND |!== 'Schema') throw new Error('The root element is not <Schema>');\n  return doc;\n\}\n\nconst escapeText = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt| TO parts.
    APPEND |;');\nconst escapeAttr = (s) => escapeText(s).replace(/"/g, '&quot;').replace(/\\n/g, '&#10;').replace(/\\t/g, '&#9;');\n\n// The schema as text, indented by two spaces; whitespace| TO parts.
    APPEND | between elements is not kept, comments are.\nfunction serialize(doc) \{\n  const lines = [];\n  const walk = (node, depth) => \{\n    const pad = '  '.repeat(depth);\n    if (node| TO parts.
    APPEND |.nodeType === Node.COMMENT_NODE) return lines.push(`$\{pad\}<!--$\{node.data\}-->`);\n    if (node.nodeType === Node.CDATA_SECTION_NODE) return lines.push(`$\{pad\}<![CDATA[$\{node| TO parts.
    APPEND |.data\}]]>`);\n    if (node.nodeType === Node.TEXT_NODE) return node.data.trim() && lines.push(pad + escapeText(node.data.trim()));\n    if (node.nodeType !== Node.ELEMENT_NODE) re| TO parts.
    APPEND |turn;\n    const attrs = [...node.attributes].map((a) => ` $\{a.name\}="$\{escapeAttr(a.value)\}"`).join('');\n    const content = [...node.childNodes].filter((c) => c.nodeType !==| TO parts.
    APPEND | Node.TEXT_NODE \|\| c.data.trim());\n    if (!content.length) return lines.push(`$\{pad\}<$\{node.tagName\}$\{attrs\}/>`);\n    if (content.length === 1 && content[0].nodeType ===| TO parts.
    APPEND | Node.TEXT_NODE) \{\n      return lines.push(`$\{pad\}<$\{node.tagName\}$\{attrs\}>$\{escapeText(content[0].data.trim())\}</$\{node.tagName\}>`);\n    \}\n    lines.push(`$\{pad\}<| TO parts.
    APPEND |$\{node.tagName\}$\{attrs\}>`);\n    content.forEach((c) => walk(c, depth + 1));\n    lines.push(`$\{pad\}</$\{node.tagName\}>`);\n  \};\n  doc.childNodes.forEach((n) => walk(n, 0)| TO parts.
    APPEND |);\n  return lines.join('\\n') + '\\n';\n\}\n\nconst kids = (el, tag) => (el ? [...el.children].filter((c) => c.tagName === tag) : []);\nconst attr = (el, name) => (el && el.getAtt| TO parts.
    APPEND |ribute(name)) ?? '';\nfunction setAttr(el, name, value) \{\n  if (value === '' \|\| value == null) el.removeAttribute(name);\n  else el.setAttribute(name, value);\n\}\nfunction cre| TO parts.
    APPEND |ate(doc, tag, attrs) \{\n  const el = doc.createElement(tag);\n  Object.entries(attrs).forEach(([name, value]) => setAttr(el, name, value));\n  return el;\n\}\n// inserts el after | TO parts.
    APPEND |the last child of the parent with one of the tags, else as its last child\nfunction insertAfterLast(parent, el, tags) \{\n  const last = [...parent.children].filter((c) => tags.inc| TO parts.
    APPEND |ludes(c.tagName)).pop();\n  parent.insertBefore(el, last ? last.nextSibling : null);\n\}\n// moves el before its previous (-1) or after its next (+1) sibling of the same tag\nfunct| TO parts.
    APPEND |ion move(el, step) \{\n  const siblings = kids(el.parentNode, el.tagName);\n  const other = siblings[siblings.indexOf(el) + step];\n  if (!other) return;\n  if (step < 0) el.parent| TO parts.
    APPEND |Node.insertBefore(el, other);\n  else el.parentNode.insertBefore(other, el);\n\}\nconst isTrue = (el, name, fallback) => (el.hasAttribute(name) ? attr(el, name) === 'true' : fallba| TO parts.
    APPEND |ck);\n\n// --------------------------------------------------------------------------------------------- the schema model\n\nconst schemaOf = (doc) => doc.documentElement;\nconst s| TO parts.
    APPEND |haredDims = (doc) => kids(schemaOf(doc), 'Dimension');\nconst cubesOf = (doc) => kids(schemaOf(doc), 'Cube');\nconst isTime = (dim) => attr(dim, 'type') === 'TimeDimension';\nconst| TO parts.
    APPEND | attributesOf = (dim) => kids(dim, 'DimensionAttribute');\nconst hierarchiesOf = (dim) => kids(dim, 'Hierarchy');\nconst keyColumn = (attribute) => attr(kids(attribute, 'KeyColumn'| TO parts.
    APPEND |)[0], 'columnName');\nconst usagesOf = (doc, dim) =>\n  cubesOf(doc).flatMap((cube) => kids(cube, 'DimensionUsage').filter((u) => attr(u, 'source') === attr(dim, 'name'))\n    .map| TO parts.
    APPEND |((usage) => (\{ cube, usage \})));\nconst isShared = (dim) => dim.parentNode.tagName === 'Schema';\n\n// The selection is a path, so it survives undo (which replaces the document).| TO parts.
    APPEND |\nfunction resolve(doc, sel) \{\n  if (sel.kind === 'cube') return cubesOf(doc)[sel.ci];\n  if (sel.kind === 'dim') return sel.ci == null ? sharedDims(doc)[sel.di] : kids(cubesOf(d| TO parts.
    APPEND |oc)[sel.ci], 'Dimension')[sel.di];\n  return schemaOf(doc);\n\}\n\n// The time suggestions of a proposal, keyed by the view and column, which the UI never changes (names it does).| TO parts.
    APPEND |\nfunction suggestionKeys(doc, suggestions) \{\n  const keys = new Map();\n  for (const s of suggestions \|\| []) \{\n    const dim = sharedDims(doc).find((d) => attr(d, 'name') ==| TO parts.
    APPEND |= s.dimension);\n    const attribute = attributesOf(dim).find((a) => attr(a, 'name') === s.attribute);\n    if (attribute) keys.set(`$\{attr(dim, 'table')\}\|$\{keyColumn(attribute| TO parts.
    APPEND |)\}`, s.levelType);\n  \}\n  return keys;\n\}\nconst suggestionFor = (suggestions, dim, attribute) => suggestions.get(`$\{attr(dim, 'table')\}\|$\{keyColumn(attribute)\}`);\n\nfunc| TO parts.
    APPEND |tion setTimeDimension(dim, on, suggestions) \{\n  const attributes = attributesOf(dim);\n  if (on) \{\n    dim.setAttribute('type', 'TimeDimension');\n    // Mondrian requires a ti| TO parts.
    APPEND |me level type on every level of a time dimension, the attribute hierarchies' too\n    for (const a of attributes) \{\n      if (!TIME_TYPES.includes(attr(a, 'levelType'))) a.setAtt| TO parts.
    APPEND |ribute('levelType', suggestionFor(suggestions, dim, a) \|\| 'TimeUndefined');\n    \}\n    for (const h of hierarchiesOf(dim)) \{\n      for (const level of kids(h, 'Level')) \{\n | TO parts.
    APPEND |       if (TIME_TYPES.includes(attr(level, 'levelType'))) continue;\n        const source = attributes.find((a) => attr(a, 'name') === attr(level, 'sourceAttribute'));\n        lev| TO parts.
    APPEND |el.setAttribute('levelType', source ? attr(source, 'levelType') : 'TimeUndefined');\n      \}\n    \}\n  \} else \{\n    dim.removeAttribute('type');\n    attributes.forEach((a) =>| TO parts.
    APPEND | a.setAttribute('levelType', 'Regular'));\n    hierarchiesOf(dim).forEach((h) => kids(h, 'Level').forEach((level) => level.removeAttribute('levelType')));\n  \}\n\}\n\nfunction ren| TO parts.
    APPEND |ameDimension(doc, dim, name) \{\n  const old = attr(dim, 'name');\n  dim.setAttribute('name', name);\n  if (isShared(dim)) \{\n    for (const cube of cubesOf(doc)) \{\n      for (c| TO parts.
    APPEND |onst usage of kids(cube, 'DimensionUsage').filter((u) => attr(u, 'source') === old)) \{\n        usage.setAttribute('source', name);\n        if (attr(usage, 'name') === old) usage| TO parts.
    APPEND |.setAttribute('name', name);\n      \}\n    \}\n  \}\n  for (const h of hierarchiesOf(dim)) \{\n    const member = attr(h, 'defaultMember');\n    if (member.startsWith(`[$\{old\}]`| TO parts.
    APPEND |)) h.setAttribute('defaultMember', `[$\{name\}]$\{member.slice(old.length + 2)\}`);\n  \}\n\}\n\nfunction renameAttribute(dim, attribute, name) \{\n  const old = attr(attribute, 'n| TO parts.
    APPEND |ame');\n  attribute.setAttribute('name', name);\n  for (const h of hierarchiesOf(dim)) \{\n    for (const level of kids(h, 'Level')) \{\n      if (attr(level, 'sourceAttribute') ==| TO parts.
    APPEND |= old) level.setAttribute('sourceAttribute', name);\n      kids(level, 'Property').filter((p) => attr(p, 'sourceAttribute') === old).forEach((p) => p.setAttribute('sourceAttribute'| TO parts.
    APPEND |, name));\n    \}\n  \}\n\}\n\nfunction setAttributeLevelType(dim, attribute, levelType) \{\n  const old = attr(attribute, 'levelType');\n  attribute.setAttribute('levelType', leve| TO parts.
    APPEND |lType);\n  // the levels on the attribute follow, unless they were given another type\n  for (const h of hierarchiesOf(dim)) \{\n    for (const level of kids(h, 'Level')) \{\n     | TO parts.
    APPEND | if (attr(level, 'sourceAttribute') === attr(attribute, 'name') && attr(level, 'levelType') === old) \{\n        level.setAttribute('levelType', levelType);\n      \}\n    \}\n  \}| TO parts.
    APPEND |\n\}\n\nconst required = (what) => (value) => (value.trim() ? '' : `$\{what\} needs a name`);\nconst unique = (what, others) => (value) =>\n  required(what)(value) \|\| (others.inc| TO parts.
    APPEND |ludes(value) ? `$\{what\} '$\{value\}' exists already` : '');\n\n// ------------------------------------------------------------------------------------------------- components\n\n| TO parts.
    APPEND |function TextField(\{ value = '', onCommit, validate, placeholder, mono, readOnly, list, title, size \}) \{\n  const [text, setText] = useState(value);\n  const [error, setError] =| TO parts.
    APPEND | useState('');\n  useEffect(() => \{\n    setText(value);\n    setError('');\n  \}, [value]);\n  const commit = () => \{\n    if (text === value) return setError('');\n    const pr| TO parts.
    APPEND |oblem = validate ? validate(text) : '';\n    if (problem) return setError(problem);\n    setError('');\n    onCommit(text);\n  \};\n  if (readOnly) return html`<input type="text" c| TO parts.
    APPEND |lass=$\{mono ? 'mono' : ''\} value=$\{value\} readOnly size=$\{size\} title=$\{title \|\| value\} />`;\n  return html`<span>\n    <input type="text" class=$\{[mono && 'mono', error| TO parts.
    APPEND | && 'invalid'].filter(Boolean).join(' ')\} value=$\{text\}\n      placeholder=$\{placeholder\} list=$\{list\} size=$\{size\} title=$\{error \|\| title \|\| ''\}\n      onInput=$\{(| TO parts.
    APPEND |e) => setText(e.target.value)\} onChange=$\{commit\}\n      onKeyDown=$\{(e) => \{ if (e.key === 'Escape') \{ setText(value); setError(''); \} \}\} />\n    $\{error && html`<div cl| TO parts.
    APPEND |ass="field-error">$\{error\}</div>`\}\n  </span>`;\n\}\n\nfunction Select(\{ value, options, onChange, title \}) \{\n  const values = options.includes(value) \|\| value === '' ? op| TO parts.
    APPEND |tions : [value, ...options];\n  return html`<select value=$\{value\} title=$\{title\} onChange=$\{(e) => onChange(e.target.value)\}>\n    $\{value === '' && html`<option value="">–| TO parts.
    APPEND |</option>`\}\n    $\{values.map((o) => html`<option value=$\{o\}>$\{o\}</option>`)\}\n  </select>`;\n\}\n\nfunction Check(\{ checked, onChange, label, title \}) \{\n  return html`<| TO parts.
    APPEND |label class="switch" title=$\{title\}>\n    <input type="checkbox" checked=$\{checked\} onChange=$\{(e) => onChange(e.target.checked)\} />$\{label\}\n  </label>`;\n\}\n\nfunction D| TO parts.
    APPEND |ialog(\{ title, children, footer, onClose \}) \{\n  useEffect(() => \{\n    const onKey = (e) => e.key === 'Escape' && onClose && onClose();\n    addEventListener('keydown', onKey)| TO parts.
    APPEND |;\n    return () => removeEventListener('keydown', onKey);\n  \}, [onClose]);\n  return html`<div class="backdrop" onClick=$\{(e) => e.target === e.currentTarget && onClose && onCl| TO parts.
    APPEND |ose()\}>\n    <div class="dialog" role="dialog" aria-modal="true">\n      <header><h2>$\{title\}</h2></header>\n      <div class="body">$\{children\}</div>\n      <footer>$\{footer| TO parts.
    APPEND |\}</footer>\n    </div>\n  </div>`;\n\}\n\n// ------------------------------------------------------------------------------------------------- start page\n\nfunction formatTime(is| TO parts.
    APPEND |o) \{\n  if (!iso) return '';\n  const d = new Date(iso);\n  return isNaN(d) ? iso : d.toLocaleString();\n\}\n\nfunction Start(\{ onOpen, opening, error \}) \{\n  const [providers,| TO parts.
    APPEND | setProviders] = useState(null);\n  const [schemas, setSchemas] = useState(null);\n  const [loadError, setLoadError] = useState('');\n  const [filter, setFilter] = useState('');\n | TO parts.
    APPEND | const [removing, setRemoving] = useState(null);\n  const loadSchemas = () => api('GET', 'schemas').then((d) => setSchemas(d.schemas), (e) => setLoadError(e.message));\n  useEffect| TO parts.
    APPEND |(() => \{\n    api('GET', 'providers').then((d) => setProviders(d.providers), (e) => setLoadError(e.message));\n    loadSchemas();\n  \}, []);\n  const words = filter.toLowerCase()| TO parts.
    APPEND |.split(/\\s+/).filter(Boolean);\n  const shown = (providers \|\| []).filter((p) =>\n    words.every((w) => `$\{p.name\} $\{p.text\} $\{p.infoarea\} $\{p.kind\}`.toLowerCase().inclu| TO parts.
    APPEND |des(w)));\n\n  return html`\n    <div class="topbar"><h1>Schema Builder</h1><span class="muted">Mondrian schemas for BW InfoProviders</span></div>\n    <div class="page">\n    $\{(| TO parts.
    APPEND |error \|\| loadError) && html`<div style="padding: 16px 16px 0"><div class="notice err">$\{error \|\| loadError\}</div></div>`\}\n    $\{opening && html`<div style="padding: 16px 1| TO parts.
    APPEND |6px 0"><div class="notice info">$\{opening\}</div></div>`\}\n    <div class="start">\n      <section class="card">\n        <header><h2>Accepted schemas</h2><span class="spacer"></| TO parts.
    APPEND |span><span class="muted small">catalogs of /WEB-INF/datasources.xml</span></header>\n        <div class="scroll">\n          $\{schemas == null ? html`<div class="body muted">Loadi| TO parts.
    APPEND |ng…</div>` : !schemas.length ? html`<div class="body muted">No catalogs yet.</div>` : html`\n          <table>\n            <thead><tr><th>Catalog</th><th>Schema file</th><th>Chang| TO parts.
    APPEND |ed</th><th></th></tr></thead>\n            <tbody>$\{schemas.map((s) => html`\n              <tr class=$\{s.exists ? 'clickable' : ''\} title=$\{s.exists ? `Edit $\{s.catalog\}` : | TO parts.
    APPEND |'The schema file is missing'\}\n                onClick=$\{() => s.exists && !opening && onOpen(\{ kind: 'schema', name: s.catalog \})\}>\n                <td><strong>$\{s.catalog| TO parts.
    APPEND |\}</strong><div class="muted small">$\{s.dataSource\}</div></td>\n                <td class="mono">$\{s.file\}$\{!s.exists && html` <span class="kind">missing</span>`\}</td>\n     | TO parts.
    APPEND |           <td class="small">$\{formatTime(s.changedAt)\}<div class="muted">$\{s.changedBy\}</div></td>\n                <td><button class="danger" title=$\{`Remove catalog $\{s.ca| TO parts.
    APPEND |talog\}`\} disabled=$\{!!opening\}\n                  onClick=$\{(e) => \{ e.stopPropagation(); setRemoving(\{ kind: 'confirm', schema: s \}); \}\}>Remove…</button></td>\n         | TO parts.
    APPEND |     </tr>`)\}\n            </tbody>\n          </table>`\}\n        </div>\n      </section>\n      <section class="card">\n        <header>\n          <h2>Propose from a provider| TO parts.
    APPEND |</h2><span class="spacer"></span>\n          <input type="search" placeholder="Filter by name, text, InfoArea" value=$\{filter\} onInput=$\{(e) => setFilter(e.target.value)\}\n    | TO parts.
    APPEND |        aria-label="Filter providers" style="width: min(260px, 100%)" />\n        </header>\n        <div class="scroll">\n          $\{providers == null ? html`<div class="body mu| TO parts.
    APPEND |ted">Loading…</div>` : html`\n          <table>\n            <thead><tr><th>Provider</th><th>Text</th><th>InfoArea</th></tr></thead>\n            <tbody>$\{shown.map((p) => html`\n| TO parts.
    APPEND |              <tr class="clickable" title=$\{`Propose a schema for $\{p.name\}`\} onClick=$\{() => !opening && onOpen(\{ kind: 'proposal', name: p.name \})\}>\n                <td>| TO parts.
    APPEND |<strong class="mono">$\{p.name\}</strong> <span class="kind">$\{p.kind\}</span></td>\n                <td>$\{p.text\}</td>\n                <td class="mono small">$\{p.infoarea\}</| TO parts.
    APPEND |td>\n              </tr>`)\}\n            </tbody>\n          </table>\n          $\{!shown.length && html`<div class="body muted">No provider matches.</div>`\}`\}\n        </div>| TO parts.
    APPEND |\n      </section>\n    </div>\n    </div>\n    $\{removing && html`<$\{RemoveDialog\} dialog=$\{removing\} onClose=$\{() => setRemoving(null)\}\n      onRemove=$\{async () => \{\n| TO parts.
    APPEND |        const s = removing.schema;\n        setRemoving(\{ kind: 'removing', schema: s \});\n        try \{\n          const result = await api('POST', 'remove', \{ catalog: s.cata| TO parts.
    APPEND |log \});\n          setRemoving(\{ kind: 'done', schema: s, result \});\n        \} catch (e) \{\n          setRemoving(\{ kind: 'failed', schema: s, message: e.message \});\n     | TO parts.
    APPEND |   \}\n        loadSchemas();\n      \}\} />`\}`;\n\}\n\nfunction RemoveDialog(\{ dialog, onRemove, onClose \}) \{\n  const s = dialog.schema;\n  if (dialog.kind === 'confirm') \{| TO parts.
    APPEND |\n    return html`<$\{Dialog\} title="Remove the schema" onClose=$\{onClose\} footer=$\{html`\n      <button onClick=$\{onClose\}>Cancel</button>\n      <button class="primary" onC| TO parts.
    APPEND |lick=$\{onRemove\}>Remove $\{s.catalog\}</button>`\}>\n      <div class="notice warn">Catalog <strong class="mono">$\{s.catalog\}</strong> and its cubes are removed: the next XMLA | TO parts.
    APPEND |request\n        does not see them. This cannot be undone here; the schema can be proposed and accepted again.</div>\n      <div class="form">\n        <label>Data source</label><s| TO parts.
    APPEND |pan>$\{s.dataSource\}</span>\n        <label>Schema file</label><span class="mono">$\{s.file\}$\{s.exists ? ' (deleted)' : ' (missing)'\}</span>\n        <label>Views</label><span>| TO parts.
    APPEND |kept: other schemas can use them</span>\n      </div>\n    <//>`;\n  \}\n  if (dialog.kind === 'removing') \{\n    return html`<$\{Dialog\} title="Removing…" footer=$\{''\}><span c| TO parts.
    APPEND |lass="muted">Removing $\{s.catalog\}…</span><//>`;\n  \}\n  if (dialog.kind === 'failed') \{\n    return html`<$\{Dialog\} title="Not removed" onClose=$\{onClose\} footer=$\{html`<| TO parts.
    APPEND |button onClick=$\{onClose\}>Close</button>`\}>\n      <div class="notice err">$\{dialog.message\}</div><span class="muted">Nothing was changed.</span>\n    <//>`;\n  \}\n  const r | TO parts.
    APPEND |= dialog.result;\n  return html`<$\{Dialog\} title="Removed" onClose=$\{onClose\} footer=$\{html`<button class="primary" onClick=$\{onClose\}>Close</button>`\}>\n    <div class="no| TO parts.
    APPEND |tice ok">Catalog <strong class="mono">$\{r.catalog\}</strong> is removed from /WEB-INF/datasources.xml.</div>\n    <span class="muted">$\{r.removedFiles.length ? html`Deleted $\{r.| TO parts.
    APPEND |removedFiles.map((f, i) => html`$\{i > 0 && ', '\}<span class="mono">$\{f\}</span>`)\}.` : 'No schema file deleted.'\}</span>\n  <//>`;\n\}\n\n// ----------------------------------| TO parts.
    APPEND |------------------------------------------------------------------- panes\n\nfunction SchemaPane(\{ doc, edit, source, catalog, notes \}) \{\n  const schema = schemaOf(doc);\n  ret| TO parts.
    APPEND |urn html`<div class="pane">\n    <div class="form">\n      <label>Schema name</label>\n      <$\{TextField\} value=$\{attr(schema, 'name')\} validate=$\{required('The schema')\} on| TO parts.
    APPEND |Commit=$\{(v) => edit(() => schema.setAttribute('name', v))\} />\n      <label>Description</label>\n      <$\{TextField\} value=$\{attr(schema, 'description')\} onCommit=$\{(v) => | TO parts.
    APPEND |edit(() => setAttr(schema, 'description', v))\} />\n      $\{source.kind === 'proposal' && html`\n        <label>Provider</label><span><strong class="mono">$\{source.name\}</strong| TO parts.
    APPEND |> <span class="kind">$\{source.providerKind\}</span> $\{source.text\}</span>\n        <label>Fact table</label><span class="mono">$\{source.factTable\}</span>`\}\n      $\{source.k| TO parts.
    APPEND |ind === 'schema' && html`\n        <label>Schema file</label><span class="mono">$\{source.file\}</span>\n        <label>Last accepted</label><span>$\{formatTime(source.changedAt)\}| TO parts.
    APPEND | $\{source.changedBy && html`<span class="muted">by $\{source.changedBy\}</span>`\}</span>`\}\n    </div>\n    <div class="notice info">\n      Every attribute of a dimension is al| TO parts.
    APPEND |ready an attribute hierarchy, so the schema is usable as proposed. Rename what\n      reads badly, drop what nobody needs, mark a dimension as time, and build user hierarchies (e.g| TO parts.
    APPEND |. Country › State ›\n      City) from attributes. The server checks the schema as you edit; <strong>Accept</strong> generates the views,\n      writes the schema file and registers| TO parts.
    APPEND | catalog <strong class="mono">$\{catalog \|\| '?'\}</strong>.\n    </div>\n    $\{notes.length > 0 && html`<section class="section">\n      <header><h3>Not proposed</h3></header>\n| TO parts.
    APPEND |      <div class="body"><ul class="plain">$\{notes.map((n) => html`<li><span class="mono">$\{n.iobjnm\}</span>: $\{n.reason\}</li>`)\}</ul></div>\n    </section>`\}\n  </div>`;\n\}| TO parts.
    APPEND |\n\nfunction CubePane(\{ doc, edit, cube, select \}) \{\n  const measures = kids(cube, 'Measure');\n  const usages = kids(cube, 'DimensionUsage');\n  const privates = kids(cube, 'D| TO parts.
    APPEND |imension');\n  const known = ['Table', 'DimensionUsage', 'Dimension', 'Measure', 'Annotations'];\n  const others = [...cube.children].filter((c) => !known.includes(c.tagName)).map(| TO parts.
    APPEND |(c) => c.tagName);\n  const measureNames = measures.map((m) => attr(m, 'name'));\n  const dimNames = [...usages, ...privates].map((u) => attr(u, 'name'));\n  const defaultMeasure =| TO parts.
    APPEND | attr(cube, 'defaultMeasure');\n\n  const removeMeasure = (m) => edit(() => \{\n    const name = attr(m, 'name');\n    m.remove();\n    if (defaultMeasure === name) setAttr(cube, '| TO parts.
    APPEND |defaultMeasure', attr(kids(cube, 'Measure')[0], 'name'));\n  \});\n\n  return html`<div class="pane">\n    <div class="form">\n      <label>Cube name</label>\n      <$\{TextField\}| TO parts.
    APPEND | value=$\{attr(cube, 'name')\} validate=$\{unique('A cube', cubesOf(doc).filter((c) => c !== cube).map((c) => attr(c, 'name')))\}\n        onCommit=$\{(v) => edit(() => cube.setAtt| TO parts.
    APPEND |ribute('name', v))\} />\n      <label>Caption</label>\n      <$\{TextField\} value=$\{attr(cube, 'caption')\} placeholder=$\{attr(cube, 'name')\} onCommit=$\{(v) => edit(() => setA| TO parts.
    APPEND |ttr(cube, 'caption', v))\} />\n      <label>Fact table</label>\n      <$\{TextField\} readOnly mono value=$\{attr(kids(cube, 'Table')[0], 'name')\} />\n      <label>Default measure| TO parts.
    APPEND |</label>\n      <$\{Select\} value=$\{defaultMeasure\} options=$\{measureNames\} onChange=$\{(v) => edit(() => setAttr(cube, 'defaultMeasure', v))\} />\n    </div>\n\n    <section | TO parts.
    APPEND |class="section">\n      <header><h3>Measures</h3><span class="spacer"></span><span class="muted small">key figures of the fact table</span></header>\n      <div class="body scroll-| TO parts.
    APPEND |x"><table>\n        <thead><tr><th>Name</th><th>Column</th><th>Aggregator</th><th>Format string</th><th>Visible</th><th></th></tr></thead>\n        <tbody>$\{measures.map((m, i) =>| TO parts.
    APPEND | html`<tr key=$\{i\}>\n          <td><$\{TextField\} value=$\{attr(m, 'name')\} validate=$\{unique('A measure', measureNames.filter((n) => n !== attr(m, 'name')))\}\n            on| TO parts.
    APPEND |Commit=$\{(v) => edit(() => \{ if (defaultMeasure === attr(m, 'name')) cube.setAttribute('defaultMeasure', v); m.setAttribute('name', v); \})\} /></td>\n          <td class="mono s| TO parts.
    APPEND |mall">$\{attr(m, 'column')\}</td>\n          <td><$\{Select\} value=$\{attr(m, 'aggregator')\} options=$\{AGGREGATORS\} onChange=$\{(v) => edit(() => m.setAttribute('aggregator', v| TO parts.
    APPEND |))\}\n            title="The engine evaluates sum and count" /></td>\n          <td><$\{TextField\} value=$\{attr(m, 'formatString')\} list="formats" placeholder="Standard" mono\n | TO parts.
    APPEND |           onCommit=$\{(v) => edit(() => setAttr(m, 'formatString', v))\} /></td>\n          <td><input type="checkbox" checked=$\{isTrue(m, 'visible', true)\} aria-label="Visible"| TO parts.
    APPEND |\n            onChange=$\{(e) => edit(() => m.setAttribute('visible', String(e.target.checked)))\} /></td>\n          <td class="actions">\n            <button class="icon" title="| TO parts.
    APPEND |Up" disabled=$\{i === 0\} onClick=$\{() => edit(() => move(m, -1))\}>↑</button>\n            <button class="icon" title="Down" disabled=$\{i === measures.length - 1\} onClick=$\{()| TO parts.
    APPEND | => edit(() => move(m, 1))\}>↓</button>\n            <button class="icon danger" title="Remove the measure" disabled=$\{measures.length === 1\} onClick=$\{() => removeMeasure(m)\}>| TO parts.
    APPEND |✕</button>\n          </td>\n        </tr>`)\}</tbody>\n      </table></div>\n    </section>\n\n    <section class="section">\n      <header><h3>Dimensions of the cube</h3><span cl| TO parts.
    APPEND |ass="spacer"></span><span class="muted small">joined on the fact table's foreign key</span></header>\n      <div class="body scroll-x"><table>\n        <thead><tr><th>Name in the c| TO parts.
    APPEND |ube</th><th>Dimension</th><th>Foreign key</th><th></th></tr></thead>\n        <tbody>\n          $\{usages.map((u, i) => \{\n            const di = sharedDims(doc).findIndex((d) =>| TO parts.
    APPEND | attr(d, 'name') === attr(u, 'source'));\n            return html`<tr key=$\{'u' + i\}>\n              <td><$\{TextField\} value=$\{attr(u, 'name')\} validate=$\{unique('A dimensio| TO parts.
    APPEND |n', dimNames.filter((n) => n !== attr(u, 'name')))\}\n                onCommit=$\{(v) => edit(() => u.setAttribute('name', v))\} /></td>\n              <td>$\{di >= 0 ? html`<butto| TO parts.
    APPEND |n class="link" onClick=$\{() => select(\{ kind: 'dim', ci: null, di \})\}>$\{attr(u, 'source')\}</button>`\n                : html`<span class="field-error">$\{attr(u, 'source')\} | TO parts.
    APPEND |(missing)</span>`\}</td>\n              <td class="mono small">$\{attr(u, 'foreignKey')\}</td>\n              <td class="actions"><button class="icon danger" title="Remove from the| TO parts.
    APPEND | cube (the dimension stays)"\n                onClick=$\{() => confirm(`Remove '$\{attr(u, 'name')\}' from cube '$\{attr(cube, 'name')\}'?`) && edit(() => u.remove())\}>✕</button><| TO parts.
    APPEND |/td>\n            </tr>`;\n          \})\}\n          $\{privates.map((d, i) => html`<tr key=$\{'p' + i\}>\n            <td>$\{attr(d, 'name')\}</td>\n            <td><button class| TO parts.
    APPEND |="link" onClick=$\{() => select(\{ kind: 'dim', ci: cubesOf(doc).indexOf(cube), di: i \})\}>private dimension</button></td>\n            <td class="mono small">$\{attr(d, 'foreignK| TO parts.
    APPEND |ey')\}</td><td></td>\n          </tr>`)\}\n        </tbody>\n      </table></div>\n    </section>\n    $\{others.length > 0 && html`<div class="notice warn">The cube also has $\{[.| TO parts.
    APPEND |..new Set(others)].join(', ')\}; edit them on the XML tab.</div>`\}\n  </div>`;\n\}\n\nfunction DimensionPane(\{ doc, edit, dim, sel, select, suggestions \}) \{\n  const time = isT| TO parts.
    APPEND |ime(dim);\n  const attributes = attributesOf(dim);\n  const hierarchies = hierarchiesOf(dim);\n  const usages = isShared(dim) ? usagesOf(doc, dim) : [];\n  const attrNames = attrib| TO parts.
    APPEND |utes.map((a) => attr(a, 'name'));\n  const used = new Set(hierarchies.flatMap((h) => kids(h, 'Level').flatMap((l) =>\n    [attr(l, 'sourceAttribute'), ...kids(l, 'Property').map((p| TO parts.
    APPEND |) => attr(p, 'sourceAttribute'))])));\n  const siblings = isShared(dim) ? sharedDims(doc) : kids(dim.parentNode, 'Dimension');\n\n  const remove = () => \{\n    const what = usages| TO parts.
    APPEND |.length ? ` and its $\{usages.length\} cube usage(s)` : '';\n    if (!confirm(`Remove dimension '$\{attr(dim, 'name')\}'$\{what\}?`)) return;\n    edit(() => \{\n      usages.forEa| TO parts.
    APPEND |ch((\{ usage \}) => usage.remove());\n      dim.remove();\n    \});\n    select(\{ kind: 'schema' \});\n  \};\n  const addHierarchy = () => edit(() => \{\n    const names = [...att| TO parts.
    APPEND |rNames, ...hierarchies.map((h) => attr(h, 'name'))];\n    let name = `$\{attr(dim, 'name')\} Hierarchy`;\n    for (let n = 2; names.includes(name); n++) name = `$\{attr(dim, 'name'| TO parts.
    APPEND |)\} Hierarchy $\{n\}`;\n    insertAfterLast(dim, create(doc, 'Hierarchy', \{ name, hasAll: 'true' \}), ['Hierarchy', 'DimensionAttribute']);\n  \});\n\n  return html`<div class="pa| TO parts.
    APPEND |ne">\n    <div class="form">\n      <label>Dimension name</label>\n      <$\{TextField\} value=$\{attr(dim, 'name')\} validate=$\{unique('A dimension', siblings.filter((d) => d !==| TO parts.
    APPEND | dim).map((d) => attr(d, 'name')))\}\n        onCommit=$\{(v) => edit(() => renameDimension(doc, dim, v))\} />\n      <label>Caption</label>\n      <$\{TextField\} value=$\{attr(di| TO parts.
    APPEND |m, 'caption')\} placeholder=$\{attr(dim, 'name')\} onCommit=$\{(v) => edit(() => setAttr(dim, 'caption', v))\} />\n      <label>Table</label>\n      <$\{TextField\} readOnly mono v| TO parts.
    APPEND |alue=$\{attr(dim, 'table')\} title="The view of the characteristic; a DDL name (ZZXXMLA1_C_...) is generated on accept" />\n      <label>Time</label>\n      <span class="row">\n   | TO parts.
    APPEND |     <$\{Check\} checked=$\{time\} label="Time dimension" onChange=$\{(on) => edit(() => setTimeDimension(dim, on, suggestions))\} />\n        <span class="muted small">enables the| TO parts.
    APPEND | time functions (Ytd, ParallelPeriod, …); every level then needs a time level type</span>\n      </span>\n      $\{isShared(dim) && html`<label>Used by</label>\n        <span>$\{us| TO parts.
    APPEND |ages.length ? usages.map((\{ cube, usage \}, i) => html`$\{i > 0 && ', '\}<button class="link"\n          onClick=$\{() => select(\{ kind: 'cube', ci: cubesOf(doc).indexOf(cube) \}| TO parts.
    APPEND |)\}>$\{attr(cube, 'name')\}</button>\n          <span class="muted small"> as $\{attr(usage, 'name')\} on <span class="mono">$\{attr(usage, 'foreignKey')\}</span></span>`)\n       | TO parts.
    APPEND |   : html`<span class="muted">no cube – not visible in MDX</span>`\}</span>`\}\n    </div>\n\n    <section class="section">\n      <header><h3>Attributes</h3><span class="spacer"><| TO parts.
    APPEND |/span><span class="muted small">each one is an attribute hierarchy</span></header>\n      <div class="body scroll-x"><table>\n        <thead><tr><th>Name</th><th>Key column</th><th| TO parts.
    APPEND |>Name column</th>$\{time && html`<th>Level type</th>`\}<th></th></tr></thead>\n        <tbody>$\{attributes.map((a, i) => \{\n          const suggestion = suggestionFor(suggestions| TO parts.
    APPEND |, dim, a);\n          const isKey = attr(a, 'usage') === 'Key';\n          return html`<tr key=$\{i\}>\n            <td><$\{TextField\} value=$\{attr(a, 'name')\} validate=$\{uniqu| TO parts.
    APPEND |e('An attribute', attrNames.filter((n) => n !== attr(a, 'name')))\}\n              onCommit=$\{(v) => edit(() => renameAttribute(dim, a, v))\} /></td>\n            <td class="mono | TO parts.
    APPEND |small">$\{keyColumn(a)\} $\{isKey && html`<span class="kind">key</span>`\}</td>\n            <td class="mono small">$\{attr(kids(a, 'NameColumn')[0], 'columnName')\}</td>\n        | TO parts.
    APPEND |    $\{time && html`<td><div class="row">\n              <$\{Select\} value=$\{attr(a, 'levelType')\} options=$\{TIME_TYPES\} onChange=$\{(v) => edit(() => setAttributeLevelType(di| TO parts.
    APPEND |m, a, v))\} />\n              $\{suggestion && suggestion !== attr(a, 'levelType') && html`<button class="link small"\n                onClick=$\{() => edit(() => setAttributeLevel| TO parts.
    APPEND |Type(dim, a, suggestion))\}>suggested: $\{suggestion\}</button>`\}\n            </div></td>`\}\n            <td class="actions"><button class="icon danger" disabled=$\{isKey \|\| u| TO parts.
    APPEND |sed.has(attr(a, 'name'))\}\n              title=$\{isKey ? 'The key attribute stays' : used.has(attr(a, 'name')) ? 'A hierarchy uses it' : 'Remove the attribute'\}\n              o| TO parts.
    APPEND |nClick=$\{() => edit(() => a.remove())\}>✕</button></td>\n          </tr>`;\n        \})\}</tbody>\n      </table></div>\n    </section>\n\n    <section class="section">\n      <he| TO parts.
    APPEND |ader>\n        <h3>User hierarchies</h3><span class="spacer"></span>\n        <button onClick=$\{addHierarchy\}>Add hierarchy</button>\n      </header>\n      <div class="body">\n | TO parts.
    APPEND |       $\{!hierarchies.length && html`<span class="muted">None. A user hierarchy nests attributes as levels, top level first.</span>`\}\n        $\{hierarchies.map((h, i) => html`<| TO parts.
    APPEND |$\{HierarchyEditor\} key=$\{i\} doc=$\{doc\} edit=$\{edit\} dim=$\{dim\} h=$\{h\}\n          others=$\{[...attrNames, ...hierarchies.filter((o) => o !== h).map((o) => attr(o, 'name| TO parts.
    APPEND |'))]\} />`)\}\n      </div>\n    </section>\n\n    <div class="row"><button class="danger" onClick=$\{remove\}>Remove dimension</button></div>\n  </div>`;\n\}\n\nfunction Hierarchy| TO parts.
    APPEND |Editor(\{ doc, edit, dim, h, others \}) \{\n  const [open, setOpen] = useState(\{\});\n  const time = isTime(dim);\n  const levels = kids(h, 'Level');\n  const attributes = attribu| TO parts.
    APPEND |tesOf(dim);\n  const attrNames = attributes.map((a) => attr(a, 'name'));\n  const hasAll = isTrue(h, 'hasAll', true);\n  const name = attr(h, 'name');\n  const clash = (!name \|\| | TO parts.
    APPEND |name === attr(dim, 'name')) && attrNames.includes(attr(dim, 'name'));\n  const levelNames = levels.map((l) => attr(l, 'name'));\n\n  const addLevel = (source) => edit(() => \{\n   | TO parts.
    APPEND | const a = attributes.find((x) => attr(x, 'name') === source);\n    let levelName = source;\n    for (let n = 2; levelNames.includes(levelName); n++) levelName = `$\{source\} $\{n| TO parts.
    APPEND |\}`;\n    h.appendChild(create(doc, 'Level', \{\n      name: levelName,\n      uniqueMembers: levels.length === 0 ? 'true' : 'false',\n      sourceAttribute: source,\n      levelTy| TO parts.
    APPEND |pe: time ? attr(a, 'levelType') \|\| 'TimeUndefined' : '',\n    \}));\n  \});\n\n  return html`<div class="hier">\n    <header>\n      <$\{TextField\} value=$\{name\} placeholder=$| TO parts.
    APPEND |\{`(unnamed: [$\{attr(dim, 'name')\}])`\}\n        validate=$\{(v) => (v && others.includes(v) ? `'$\{v\}' is already an attribute or hierarchy of the dimension` : '')\}\n        o| TO parts.
    APPEND |nCommit=$\{(v) => edit(() => setAttr(h, 'name', v))\} />\n      <$\{Check\} checked=$\{hasAll\} label="All member" onChange=$\{(on) => edit(() => h.setAttribute('hasAll', String(on| TO parts.
    APPEND |)))\} />\n      $\{hasAll && html`<$\{TextField\} value=$\{attr(h, 'allMemberName')\} placeholder="All member name" size="16"\n        onCommit=$\{(v) => edit(() => setAttr(h, 'all| TO parts.
    APPEND |MemberName', v))\} />`\}\n      <$\{TextField\} value=$\{attr(h, 'defaultMember')\} mono placeholder=$\{hasAll ? 'default member: the All member' : `default member, e.g. [$\{attr(d| TO parts.
    APPEND |im, 'name')\}].[1997]`\}\n        title="A unique member name" onCommit=$\{(v) => edit(() => setAttr(h, 'defaultMember', v))\} />\n      <span class="spacer"></span>\n      <button| TO parts.
    APPEND | class="danger" onClick=$\{() => confirm(`Remove hierarchy '$\{name \|\| attr(dim, 'name')\}'?`) && edit(() => h.remove())\}>Remove</button>\n    </header>\n    <div class="body">| TO parts.
    APPEND |\n      $\{clash && html`<div class="notice warn">Name the hierarchy: the attribute '$\{attr(dim, 'name')\}' has the dimension's name, so an\n        unnamed hierarchy (or one name| TO parts.
    APPEND |d like the dimension) would share its unique name.</div>`\}\n      $\{!hasAll && !attr(h, 'defaultMember') && html`<div class="notice warn">Without an All member the first member i| TO parts.
    APPEND |s the default; BW's\n        empty member (SID 0) may come first, so give a default member.</div>`\}\n      $\{levels.length > 0 && html`<div class="scroll-x"><table>\n        <the| TO parts.
    APPEND |ad><tr><th>#</th><th>Level</th><th>Attribute</th>$\{time && html`<th>Level type</th>`\}<th title="Members are unique within the level, not only within their parent">Unique</th><th>| TO parts.
    APPEND |Properties</th><th></th></tr></thead>\n        <tbody>$\{levels.map((l, i) => \{\n          const props = kids(l, 'Property');\n          return html`\n          <tr key=$\{'l' + i| TO parts.
    APPEND |\}>\n            <td class="num muted">$\{i + 1\}</td>\n            <td><$\{TextField\} value=$\{attr(l, 'name')\} validate=$\{unique('A level', levelNames.filter((n) => n !== attr| TO parts.
    APPEND |(l, 'name')))\}\n              onCommit=$\{(v) => edit(() => l.setAttribute('name', v))\} /></td>\n            <td><$\{Select\} value=$\{attr(l, 'sourceAttribute')\} options=$\{att| TO parts.
    APPEND |rNames\} onChange=$\{(v) => edit(() => l.setAttribute('sourceAttribute', v))\} /></td>\n            $\{time && html`<td><$\{Select\} value=$\{attr(l, 'levelType')\} options=$\{TIME| TO parts.
    APPEND |_TYPES\} onChange=$\{(v) => edit(() => l.setAttribute('levelType', v))\} /></td>`\}\n            <td><input type="checkbox" checked=$\{isTrue(l, 'uniqueMembers', false)\} aria-labe| TO parts.
    APPEND |l="Unique members"\n              onChange=$\{(e) => edit(() => l.setAttribute('uniqueMembers', String(e.target.checked)))\} /></td>\n            <td><button class="link" onClick=$| TO parts.
    APPEND |\{() => setOpen(\{ ...open, [i]: !open[i] \})\}>$\{props.length\} $\{open[i] ? '▾' : '▸'\}</button></td>\n            <td class="actions">\n              <button class="icon" title| TO parts.
    APPEND |="Up" disabled=$\{i === 0\} onClick=$\{() => edit(() => move(l, -1))\}>↑</button>\n              <button class="icon" title="Down" disabled=$\{i === levels.length - 1\} onClick=$\{| TO parts.
    APPEND |() => edit(() => move(l, 1))\}>↓</button>\n              <button class="icon danger" title="Remove the level" onClick=$\{() => edit(() => l.remove())\}>✕</button>\n            </td| TO parts.
    APPEND |>\n          </tr>\n          $\{open[i] && html`<tr key=$\{'p' + i\}><td></td><td colspan=$\{time ? 6 : 5\}><div class="props">\n            $\{props.map((p, j) => html`<div class| TO parts.
    APPEND |="row" key=$\{j\}>\n              <$\{TextField\} value=$\{attr(p, 'name')\} validate=$\{required('A property')\} onCommit=$\{(v) => edit(() => p.setAttribute('name', v))\} />\n   | TO parts.
    APPEND |           <span class="muted">from</span>\n              <$\{Select\} value=$\{attr(p, 'sourceAttribute')\} options=$\{attrNames\} onChange=$\{(v) => edit(() => p.setAttribute('so| TO parts.
    APPEND |urceAttribute', v))\} />\n              <button class="icon danger" title="Remove the property" onClick=$\{() => edit(() => p.remove())\}>✕</button>\n            </div>`)\}\n      | TO parts.
    APPEND |      <div class="row"><select value="" aria-label="Add a property" onChange=$\{(e) => \{\n              const source = e.target.value;\n              e.target.value = '';\n       | TO parts.
    APPEND |       if (source) edit(() => l.appendChild(create(doc, 'Property', \{ name: source, sourceAttribute: source \})));\n            \}\}>\n              <option value="">Add a member | TO parts.
    APPEND |property…</option>\n              $\{attrNames.filter((n) => !props.some((p) => attr(p, 'sourceAttribute') === n)).map((n) => html`<option value=$\{n\}>$\{n\}</option>`)\}\n       | TO parts.
    APPEND |     </select><span class="muted small">attributes shown with each member of this level</span></div>\n          </div></td></tr>`\}`;\n        \})\}</tbody>\n      </table></div>`| TO parts.
    APPEND |\}\n      <div class="row">\n        <select value="" aria-label="Add a level" onChange=$\{(e) => \{\n          const source = e.target.value;\n          e.target.value = '';\n    | TO parts.
    APPEND |      if (source) addLevel(source);\n        \}\}>\n          <option value="">Add a level…</option>\n          $\{attrNames.map((n) => html`<option value=$\{n\}>$\{n\}$\{levels.so| TO parts.
    APPEND |me((l) => attr(l, 'sourceAttribute') === n) ? ' (used)' : ''\}</option>`)\}\n        </select>\n        $\{!levels.length && html`<span class="muted small">start with the top level| TO parts.
    APPEND |</span>`\}\n      </div>\n    </div>\n  </div>`;\n\}\n\nfunction XmlPane(\{ xml, replace \}) \{\n  const [text, setText] = useState(xml);\n  const [error, setError] = useState('');| TO parts.
    APPEND |\n  useEffect(() => \{\n    setText(xml);\n    setError('');\n  \}, [xml]);\n  const apply = () => \{\n    try \{\n      replace(parseXml(text));\n    \} catch (e) \{\n      setErr| TO parts.
    APPEND |or(e.message);\n    \}\n  \};\n  const download = () => \{\n    const link = document.createElement('a');\n    link.href = URL.createObjectURL(new Blob([xml], \{ type: 'application| TO parts.
    APPEND |/xml' \}));\n    link.download = `$\{attr(parseXml(xml).documentElement, 'name') \|\| 'schema'\}.xml`;\n    link.click();\n    URL.revokeObjectURL(link.href);\n  \};\n  return html| TO parts.
    APPEND |`<div class="pane" style="max-width: none">\n    <div class="row">\n      <button class="primary" disabled=$\{text === xml\} onClick=$\{apply\}>Apply</button>\n      <button disabl| TO parts.
    APPEND |ed=$\{text === xml\} onClick=$\{() => \{ setText(xml); setError(''); \}\}>Revert</button>\n      <button onClick=$\{download\}>Download</button>\n      <span class="muted small">An| TO parts.
    APPEND |ything the outline does not cover (calculated members, captions, annotations, …) is edited here.</span>\n    </div>\n    $\{error && html`<div class="notice err">$\{error\}</div>`| TO parts.
    APPEND |\}\n    <textarea class="xml" spellcheck="false" value=$\{text\} onInput=$\{(e) => setText(e.target.value)\}\n      onKeyDown=$\{(e) => \{\n        if ((e.ctrlKey \|\| e.metaKey) &| TO parts.
    APPEND |& e.key === 's') \{ e.preventDefault(); apply(); \}\n      \}\}></textarea>\n  </div>`;\n\}\n\n// ----------------------------------------------------------------------------------| TO parts.
    APPEND |-------------------- editor\n\nfunction Tree(\{ doc, sel, select, notes \}) \{\n  const item = (target, label, badge, sub) => \{\n    const selected = JSON.stringify(target) === JS| TO parts.
    APPEND |ON.stringify(sel);\n    return html`<button class=$\{`item$\{sub ? ' sub' : ''\}$\{selected ? ' selected' : ''\}`\} onClick=$\{() => select(target)\}>\n      <span>$\{label\}</span| TO parts.
    APPEND |>$\{badge && html`<span class="badge">$\{badge\}</span>`\}\n    </button>`;\n  \};\n  const usedNames = new Set(cubesOf(doc).flatMap((c) => kids(c, 'DimensionUsage').map((u) => att| TO parts.
    APPEND |r(u, 'source'))));\n  return html`<nav class="tree" aria-label="Schema outline">\n    $\{item(\{ kind: 'schema' \}, html`<strong>$\{attr(schemaOf(doc), 'name') \|\| 'Schema'\}</str| TO parts.
    APPEND |ong>`, notes.length ? `$\{notes.length\} note$\{notes.length > 1 ? 's' : ''\}` : '')\}\n    <div class="group"><h3>Cubes</h3></div>\n    $\{cubesOf(doc).map((cube, ci) => html`\n  | TO parts.
    APPEND |    $\{item(\{ kind: 'cube', ci \}, attr(cube, 'name'), `$\{kids(cube, 'Measure').length\} measures`)\}\n      $\{kids(cube, 'Dimension').map((d, di) => item(\{ kind: 'dim', ci, di| TO parts.
    APPEND | \}, attr(d, 'name'), isTime(d) ? 'time' : '', true))\}`)\}\n    <div class="group"><h3>Dimensions</h3></div>\n    $\{sharedDims(doc).map((d, di) => item(\{ kind: 'dim', ci: null, | TO parts.
    APPEND |di \}, attr(d, 'name'),\n      [isTime(d) && 'time', hierarchiesOf(d).length && `$\{hierarchiesOf(d).length\} hier.`, !usedNames.has(attr(d, 'name')) && 'unused']\n        .filter(| TO parts.
    APPEND |Boolean).join(' · ')))\}\n  </nav>`;\n\}\n\nfunction Editor(\{ session, onClose, onAccepted \}) \{\n  const [doc, setDoc] = useState(session.doc);\n  const [version, setVersion] = | TO parts.
    APPEND |useState(0);\n  const [source, setSource] = useState(session.source);\n  const [catalog, setCatalog] = useState(session.catalog);\n  const [dirty, setDirty] = useState(false);\n  c| TO parts.
    APPEND |onst [sel, setSel] = useState(\{ kind: 'schema' \});\n  const [tab, setTab] = useState('outline');\n  const [check, setCheck] = useState(\{ state: 'busy' \});\n  const [dialog, set| TO parts.
    APPEND |Dialog] = useState(null);\n  const undoStack = useRef([]);\n  const xml = useMemo(() => serialize(doc), [doc, version]);\n\n  const edit = useCallback((change) => \{\n    undoStack| TO parts.
    APPEND |.current.push(serialize(doc));\n    if (undoStack.current.length > 100) undoStack.current.shift();\n    change(doc);\n    setVersion((v) => v + 1);\n    setDirty(true);\n  \}, [doc| TO parts.
    APPEND |]);\n  const replace = useCallback((next) => \{\n    undoStack.current.push(serialize(doc));\n    setDoc(next);\n    setVersion((v) => v + 1);\n    setDirty(true);\n  \}, [doc]);\n| TO parts.
    APPEND |  const undo = useCallback(() => \{\n    const previous = undoStack.current.pop();\n    if (previous == null) return;\n    setDoc(parseXml(previous));\n    setVersion((v) => v + 1)| TO parts.
    APPEND |;\n  \}, []);\n\n  // Ctrl+Z outside of input fields (they have their own undo)\n  useEffect(() => \{\n    const onKey = (e) => \{\n      if ((e.ctrlKey \|\| e.metaKey) && e.key ==| TO parts.
    APPEND |= 'z' && !/^(INPUT\|TEXTAREA\|SELECT)$/.test(document.activeElement.tagName)) \{\n        e.preventDefault();\n        undo();\n      \}\n    \};\n    addEventListener('keydown', o| TO parts.
    APPEND |nKey);\n    return () => removeEventListener('keydown', onKey);\n  \}, [undo]);\n  useEffect(() => \{\n    const onLeave = (e) => \{ if (dirty) \{ e.preventDefault(); e.returnValue| TO parts.
    APPEND | = ''; \} \};\n    addEventListener('beforeunload', onLeave);\n    return () => removeEventListener('beforeunload', onLeave);\n  \}, [dirty]);\n\n  // the server's checks of accept| TO parts.
    APPEND |, nothing written; the last request wins\n  const sequence = useRef(0);\n  useEffect(() => \{\n    const mine = ++sequence.current;\n    setCheck((c) => (\{ ...c, state: 'busy' \})| TO parts.
    APPEND |);\n    const timer = setTimeout(async () => \{\n      try \{\n        if (!CATALOG_NAME.test(catalog)) throw new Error('A catalog name has letters, digits, _, - and . (not first)'| TO parts.
    APPEND |);\n        const result = await api('POST', 'check', \{ catalog \}, xml);\n        if (mine === sequence.current) setCheck(\{ state: 'ok', result, xml, catalog \});\n      \} catc| TO parts.
    APPEND |h (e) \{\n        if (mine === sequence.current) setCheck(\{ state: 'err', message: e.message \});\n      \}\n    \}, 500);\n    return () => clearTimeout(timer);\n  \}, [xml, cata| TO parts.
    APPEND |log]);\n\n  const current = check.state === 'ok' && check.xml === xml && check.catalog === catalog;\n  const accept = async () => \{\n    setDialog(\{ kind: 'accepting' \});\n    t| TO parts.
    APPEND |ry \{\n      const result = await api('POST', 'accept', \{ catalog \}, xml);\n      undoStack.current = [];\n      setDoc(parseXml(result.xml));\n      setVersion((v) => v + 1);\n | TO parts.
    APPEND |     setDirty(false);\n      const reopened = \{ kind: 'schema', name: result.catalog, file: result.file, changedAt: new Date().toISOString(), changedBy: '' \};\n      setSource(re| TO parts.
    APPEND |opened);\n      setDialog(\{ kind: 'accepted', result \});\n      onAccepted(reopened);\n    \} catch (e) \{\n      setDialog(\{ kind: 'failed', message: e.message \});\n    \}\n  | TO parts.
    APPEND |\};\n\n  let target = resolve(doc, sel);\n  const shownSel = target ? sel : \{ kind: 'schema' \};\n  if (!target) target = schemaOf(doc);\n  const status = check.state === 'busy' ?| TO parts.
    APPEND | html`<span class="status busy">Checking…</span>`\n    : check.state === 'err' ? html`<span class="status err" title=$\{check.message\}>✕ Does not load</span>`\n      : html`<span | TO parts.
    APPEND |class="status ok" title=$\{check.result.file\}>✓ Loads$\{check.result.newCatalog ? ' · new catalog' : ' · replaces the catalog\\'s schema'\}</span>`;\n\n  return html`\n    <div cl| TO parts.
    APPEND |ass="topbar">\n      <button onClick=$\{() => (!dirty \|\| confirm('Leave without accepting? Your changes are lost.')) && onClose()\} title="Back to the list">←</button>\n      <di| TO parts.
    APPEND |v class="title">\n        <h1>Schema Builder</h1>\n        <span class="src">$\{source.kind === 'proposal' ? html`proposal for <span class="mono">$\{source.name\}</span>` : html`ca| TO parts.
    APPEND |talog <span class="mono">$\{source.name\}</span>`\}$\{dirty && ' · edited'\}</span>\n      </div>\n      <span class="spacer"></span>\n      <label class="inline">Catalog\n        | TO parts.
    APPEND |<input type="text" class=$\{`mono$\{CATALOG_NAME.test(catalog) ? '' : ' invalid'\}`\} value=$\{catalog\} size="16"\n          onInput=$\{(e) => setCatalog(e.target.value.trim())\} | TO parts.
    APPEND |/>\n      </label>\n      $\{status\}\n      <button disabled=$\{!undoStack.current.length\} onClick=$\{undo\} title="Undo (Ctrl+Z)">Undo</button>\n      <button class="primary" di| TO parts.
    APPEND |sabled=$\{!current\} onClick=$\{() => setDialog(\{ kind: 'confirm' \})\}\n        title=$\{current ? 'Generate the views, write the schema file and register the catalog' : 'Waiting| TO parts.
    APPEND | for a successful check'\}>Accept…</button>\n    </div>\n    $\{check.state === 'err' && html`<div class="banner" role="alert">$\{check.message\}</div>`\}\n    <div class="editor">| TO parts.
    APPEND |\n      <$\{Tree\} doc=$\{doc\} sel=$\{shownSel\} select=$\{(s) => \{ setSel(s); setTab('outline'); \}\} notes=$\{session.notes\} />\n      <main class="main">\n        <div class=| TO parts.
    APPEND |"tabs" role="tablist">\n          <button role="tab" class=$\{tab === 'outline' ? 'active' : ''\} onClick=$\{() => setTab('outline')\}>Outline</button>\n          <button role="tab| TO parts.
    APPEND |" class=$\{tab === 'xml' ? 'active' : ''\} onClick=$\{() => setTab('xml')\}>XML</button>\n        </div>\n        $\{tab === 'xml' ? html`<$\{XmlPane\} xml=$\{xml\} replace=$\{repl| TO parts.
    APPEND |ace\} />`\n          : shownSel.kind === 'cube' ? html`<$\{CubePane\} key=$\{JSON.stringify(shownSel)\} doc=$\{doc\} edit=$\{edit\} cube=$\{target\} select=$\{setSel\} />`\n       | TO parts.
    APPEND |     : shownSel.kind === 'dim' ? html`<$\{DimensionPane\} key=$\{JSON.stringify(shownSel)\} doc=$\{doc\} edit=$\{edit\} dim=$\{target\} sel=$\{shownSel\}\n                select=$| TO parts.
    APPEND |\{setSel\} suggestions=$\{session.suggestions\} />`\n              : html`<$\{SchemaPane\} doc=$\{doc\} edit=$\{edit\} source=$\{source\} catalog=$\{catalog\} notes=$\{session.note| TO parts.
    APPEND |s\} />`\}\n      </main>\n    </div>\n    <datalist id="formats">$\{FORMATS.map((f) => html`<option value=$\{f\} />`)\}</datalist>\n    $\{dialog && html`<$\{AcceptDialog\} dialog=| TO parts.
    APPEND |$\{dialog\} check=$\{check\} catalog=$\{catalog\} onAccept=$\{accept\} onClose=$\{() => setDialog(null)\} />`\}`;\n\}\n\nfunction AcceptDialog(\{ dialog, check, catalog, onAccept, | TO parts.
    APPEND |onClose \}) \{\n  if (dialog.kind === 'confirm') \{\n    const r = check.result;\n    return html`<$\{Dialog\} title="Accept the schema" onClose=$\{onClose\} footer=$\{html`\n     | TO parts.
    APPEND | <button onClick=$\{onClose\}>Cancel</button>\n      <button class="primary" onClick=$\{onAccept\}>$\{r.newCatalog ? 'Accept' : 'Replace the schema'\}</button>`\}>\n      $\{r.newC| TO parts.
    APPEND |atalog ? html`<div class="notice info">Catalog <strong class="mono">$\{r.catalog\}</strong> is new: it is added to the first data source.</div>`\n        : html`<div class="notice | TO parts.
    APPEND |warn">Catalog <strong class="mono">$\{r.catalog\}</strong> exists: its schema file is replaced, and the next\n          XMLA request serves the new schema.</div>`\}\n      <div cla| TO parts.
    APPEND |ss="form">\n        <label>Schema file</label><span class="mono">$\{r.file\}</span>\n        <label>Views</label>\n        <span>$\{r.views.length ? html`generated for $\{r.views.m| TO parts.
    APPEND |ap((v, i) => html`$\{i > 0 && ', '\}<span class="mono">$\{v\}</span>`)\}` : 'none to generate'\}</span>\n      </div>\n    <//>`;\n  \}\n  if (dialog.kind === 'accepting') \{\n    | TO parts.
    APPEND |return html`<$\{Dialog\} title="Accepting…" footer=$\{''\}><span class="muted">Generating the views and writing $\{catalog\}…</span><//>`;\n  \}\n  if (dialog.kind === 'failed') \{| TO parts.
    APPEND |\n    return html`<$\{Dialog\} title="Not accepted" onClose=$\{onClose\} footer=$\{html`<button onClick=$\{onClose\}>Close</button>`\}>\n      <div class="notice err">$\{dialog.mes| TO parts.
    APPEND |sage\}</div><span class="muted">Nothing was written.</span>\n    <//>`;\n  \}\n  const r = dialog.result;\n  return html`<$\{Dialog\} title="Accepted" onClose=$\{onClose\} footer=$| TO parts.
    APPEND |\{html`<button class="primary" onClick=$\{onClose\}>Close</button>`\}>\n    <div class="notice ok">Catalog <strong class="mono">$\{r.catalog\}</strong> is written to <span class="m| TO parts.
    APPEND |ono">$\{r.file\}</span>; the next XMLA\n      request reads it.</div>\n    $\{r.views.length > 0 && html`<table>\n      <thead><tr><th>Characteristic</th><th>DDL source</th><th>Vie| TO parts.
    APPEND |w</th></tr></thead>\n      <tbody>$\{r.views.map((v) => html`<tr><td class="mono">$\{v.characteristic\}</td><td class="mono">$\{v.ddlName\}</td><td class="mono">$\{v.viewName\}</td| TO parts.
    APPEND |></tr>`)\}</tbody>\n    </table>`\}\n  <//>`;\n\}\n\n// --------------------------------------------------------------------------------------------------------- app\n\n// #proposa| TO parts.
    APPEND |l/<provider> or #schema/<catalog>, so a reload opens the same thing again\nconst readHash = () => \{\n  const m = /^#(proposal\|schema)\\/(.+)$/.exec(location.hash);\n  return m ? | TO parts.
    APPEND |\{ kind: m[1], name: decodeURIComponent(m[2]) \} : null;\n\};\nconst writeHash = (what) => history.replaceState(null, '', what ? `#$\{what.kind\}/$\{encodeURIComponent(what.name)\}| TO parts.
    APPEND |` : location.pathname + location.search);\n\nfunction App() \{\n  const [session, setSession] = useState(null);\n  const [opening, setOpening] = useState('');\n  const [error, setE| TO parts.
    APPEND |rror] = useState('');\n  const counter = useRef(0);\n\n  const open = async (what) => \{\n    setError('');\n    setOpening(what.kind === 'proposal' ? `Proposing a schema for $\{wh| TO parts.
    APPEND |at.name\}…` : `Opening catalog $\{what.name\}…`);\n    try \{\n      let next;\n      if (what.kind === 'proposal') \{\n        const d = await api('GET', 'proposal', \{ provider: | TO parts.
    APPEND |what.name \});\n        const doc = parseXml(d.xml);\n        next = \{\n          doc,\n          catalog: attr(schemaOf(doc), 'name'),\n          source: \{ kind: 'proposal', nam| TO parts.
    APPEND |e: d.provider.name, providerKind: d.provider.kind, text: d.provider.text, factTable: d.provider.factTable \},\n          notes: d.notes \|\| [],\n          suggestions: suggestionK| TO parts.
    APPEND |eys(doc, d.suggestions),\n        \};\n      \} else \{\n        const d = await api('GET', 'schema', \{ catalog: what.name \});\n        next = \{\n          doc: parseXml(d.xml),| TO parts.
    APPEND |\n          catalog: d.catalog,\n          source: \{ kind: 'schema', name: d.catalog, file: d.file, changedAt: d.changedAt, changedBy: d.changedBy \},\n          notes: [],\n     | TO parts.
    APPEND |     suggestions: new Map(),\n        \};\n      \}\n      next.id = ++counter.current;\n      writeHash(what);\n      setSession(next);\n    \} catch (e) \{\n      writeHash(null)| TO parts.
    APPEND |;\n      setError(`$\{what.name\}: $\{e.message\}`);\n    \} finally \{\n      setOpening('');\n    \}\n  \};\n\n  useEffect(() => \{\n    const what = readHash();\n    if (what) o| TO parts.
    APPEND |pen(what);\n  \}, []);\n\n  if (session) \{\n    return html`<$\{Editor\} key=$\{session.id\} session=$\{session\}\n      onClose=$\{() => \{ writeHash(null); setSession(null); \}| TO parts.
    APPEND |\}\n      onAccepted=$\{(source) => writeHash(source)\} />`;\n  \}\n  return html`<$\{Start\} onOpen=$\{open\} opening=$\{opening\} error=$\{error\} />`;\n\}\n\nconst root = docume| TO parts.
    APPEND |nt.getElementById('app');\nroot.textContent = '';\nrender(html`<$\{App\} />`, root);\n| TO parts.
    result = concat_lines_of( parts ).
  ENDMETHOD.

  METHOD file_3.
    DATA parts TYPE string_table.
    APPEND |<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Schema Builder</title>\n  <lin| TO parts.
    APPEND |k rel="stylesheet" href="app.css">\n  <script type="module" src="app.js"></script>\n</head>\n<body>\n  <div id="app"><p class="boot">Loading…</p></div>\n  <noscript>The schema buil| TO parts.
    APPEND |der needs JavaScript.</noscript>\n</body>\n</html>\n| TO parts.
    result = concat_lines_of( parts ).
  ENDMETHOD.

  METHOD file_4.
    DATA parts TYPE string_table.
    APPEND |// htm 3.1.1, preact/standalone.module.js (Preact 10 with hooks and htm in one module), unchanged from\n// https://unpkg.com/htm@3.1.1/preact/standalone.module.js. htm: Apache-2.0,| TO parts.
    APPEND | Preact: MIT.\nvar e,n,_,t,o,r,u,l=\{\},i=[],c=/acit\|ex(?:s\|g\|n\|p\|$)\|rph\|grid\|ows\|mnc\|ntw\|ine[ch]\|zoo\|^ord\|itera/i;function s(e,n)\{for(var _ in n)e[_]=n[_];return e| TO parts.
    APPEND |\}function f(e)\{var n=e.parentNode;n&&n.removeChild(e)\}function a(n,_,t)\{var o,r,u,l=\{\};for(u in _)"key"==u?o=_[u]:"ref"==u?r=_[u]:l[u]=_[u];if(arguments.length>2&&(l.children| TO parts.
    APPEND |=arguments.length>3?e.call(arguments,2):t),"function"==typeof n&&null!=n.defaultProps)for(u in n.defaultProps)void 0===l[u]&&(l[u]=n.defaultProps[u]);return p(n,l,o,r,null)\}functi| TO parts.
    APPEND |on p(e,t,o,r,u)\{var l=\{type:e,props:t,key:o,ref:r,__k:null,__:null,__b:0,__e:null,__d:void 0,__c:null,__h:null,constructor:void 0,__v:null==u?++_:u\};return null!=n.vnode&&n.vnod| TO parts.
    APPEND |e(l),l\}function h(e)\{return e.children\}function d(e,n)\{this.props=e,this.context=n\}function v(e,n)\{if(null==n)return e.__?v(e.__,e.__.__k.indexOf(e)+1):null;for(var _;n<e.__k| TO parts.
    APPEND |.length;n++)if(null!=(_=e.__k[n])&&null!=_.__e)return _.__e;return"function"==typeof e.type?v(e):null\}function y(e)\{var n,_;if(null!=(e=e.__)&&null!=e.__c)\{for(e.__e=e.__c.base=| TO parts.
    APPEND |null,n=0;n<e.__k.length;n++)if(null!=(_=e.__k[n])&&null!=_.__e)\{e.__e=e.__c.base=_.__e;break\}return y(e)\}\}function m(e)\{(!e.__d&&(e.__d=!0)&&t.push(e)&&!g.__r++\|\|r!==n.debou| TO parts.
    APPEND |nceRendering)&&((r=n.debounceRendering)\|\|o)(g)\}function g()\{for(var e;g.__r=t.length;)e=t.sort(function(e,n)\{return e.__v.__b-n.__v.__b\}),t=[],e.some(function(e)\{var n,_,t,o| TO parts.
    APPEND |,r,u;e.__d&&(r=(o=(n=e).__v).__e,(u=n.__P)&&(_=[],(t=s(\{\},o)).__v=o.__v+1,P(u,o,t,n.__n,void 0!==u.ownerSVGElement,null!=o.__h?[r]:null,_,null==r?v(o):r,o.__h),D(_,o),o.__e!=r&&y| TO parts.
    APPEND |(o)))\})\}function k(e,n,_,t,o,r,u,c,s,f)\{var a,d,y,m,g,k,x,H=t&&t.__k\|\|i,E=H.length;for(_.__k=[],a=0;a<n.length;a++)if(null!=(m=_.__k[a]=null==(m=n[a])\|\|"boolean"==typeof m?n| TO parts.
    APPEND |ull:"string"==typeof m\|\|"number"==typeof m\|\|"bigint"==typeof m?p(null,m,null,null,m):Array.isArray(m)?p(h,\{children:m\},null,null,null):m.__b>0?p(m.type,m.props,m.key,null,m._| TO parts.
    APPEND |_v):m))\{if(m.__=_,m.__b=_.__b+1,null===(y=H[a])\|\|y&&m.key==y.key&&m.type===y.type)H[a]=void 0;else for(d=0;d<E;d++)\{if((y=H[d])&&m.key==y.key&&m.type===y.type)\{H[d]=void 0;bre| TO parts.
    APPEND |ak\}y=null\}P(e,m,y=y\|\|l,o,r,u,c,s,f),g=m.__e,(d=m.ref)&&y.ref!=d&&(x\|\|(x=[]),y.ref&&x.push(y.ref,null,m),x.push(d,m.__c\|\|g,m)),null!=g?(null==k&&(k=g),"function"==typeof m.t| TO parts.
    APPEND |ype&&null!=m.__k&&m.__k===y.__k?m.__d=s=b(m,s,e):s=C(e,m,y,H,g,s),f\|\|"option"!==_.type?"function"==typeof _.type&&(_.__d=s):e.value=""):s&&y.__e==s&&s.parentNode!=e&&(s=v(y))\}fo| TO parts.
    APPEND |r(_.__e=k,a=E;a--;)null!=H[a]&&("function"==typeof _.type&&null!=H[a].__e&&H[a].__e==_.__d&&(_.__d=v(t,a+1)),U(H[a],H[a]));if(x)for(a=0;a<x.length;a++)T(x[a],x[++a],x[++a])\}functi| TO parts.
    APPEND |on b(e,n,_)\{var t,o;for(t=0;t<e.__k.length;t++)(o=e.__k[t])&&(o.__=e,n="function"==typeof o.type?b(o,n,_):C(_,o,o,e.__k,o.__e,n));return n\}function C(e,n,_,t,o,r)\{var u,l,i;if(v| TO parts.
    APPEND |oid 0!==n.__d)u=n.__d,n.__d=void 0;else if(null==_\|\|o!=r\|\|null==o.parentNode)e:if(null==r\|\|r.parentNode!==e)e.appendChild(o),u=null;else\{for(l=r,i=0;(l=l.nextSibling)&&i<t.l| TO parts.
    APPEND |ength;i+=2)if(l==o)break e;e.insertBefore(o,r),u=r\}return void 0!==u?u:o.nextSibling\}function x(e,n,_)\{"-"===n[0]?e.setProperty(n,_):e[n]=null==_?"":"number"!=typeof _\|\|c.test| TO parts.
    APPEND |(n)?_:_+"px"\}function H(e,n,_,t,o)\{var r;e:if("style"===n)if("string"==typeof _)e.style.cssText=_;else\{if("string"==typeof t&&(e.style.cssText=t=""),t)for(n in t)_&&n in _\|\|x(| TO parts.
    APPEND |e.style,n,"");if(_)for(n in _)t&&_[n]===t[n]\|\|x(e.style,n,_[n])\}else if("o"===n[0]&&"n"===n[1])r=n!==(n=n.replace(/Capture$/,"")),n=n.toLowerCase()in e?n.toLowerCase().slice(2):| TO parts.
    APPEND |n.slice(2),e.l\|\|(e.l=\{\}),e.l[n+r]=_,_?t\|\|e.addEventListener(n,r?S:E,r):e.removeEventListener(n,r?S:E,r);else if("dangerouslySetInnerHTML"!==n)\{if(o)n=n.replace(/xlink[H:h]/,| TO parts.
    APPEND |"h").replace(/sName$/,"s");else if("href"!==n&&"list"!==n&&"form"!==n&&"tabIndex"!==n&&"download"!==n&&n in e)try\{e[n]=null==_?"":_;break e\}catch(e)\{\}"function"==typeof _\|\|(n| TO parts.
    APPEND |ull!=_&&(!1!==_\|\|"a"===n[0]&&"r"===n[1])?e.setAttribute(n,_):e.removeAttribute(n))\}\}function E(e)\{this.l[e.type+!1](n.event?n.event(e):e)\}function S(e)\{this.l[e.type+!0](n.e| TO parts.
    APPEND |vent?n.event(e):e)\}function P(e,_,t,o,r,u,l,i,c)\{var f,a,p,v,y,m,g,b,C,x,H,E=_.type;if(void 0!==_.constructor)return null;null!=t.__h&&(c=t.__h,i=_.__e=t.__e,_.__h=null,u=[i]),(f| TO parts.
    APPEND |=n.__b)&&f(_);try\{e:if("function"==typeof E)\{if(b=_.props,C=(f=E.contextType)&&o[f.__c],x=f?C?C.props.value:f.__:o,t.__c?g=(a=_.__c=t.__c).__=a.__E:("prototype"in E&&E.prototype.| TO parts.
    APPEND |render?_.__c=a=new E(b,x):(_.__c=a=new d(b,x),a.constructor=E,a.render=A),C&&C.sub(a),a.props=b,a.state\|\|(a.state=\{\}),a.context=x,a.__n=o,p=a.__d=!0,a.__h=[]),null==a.__s&&(a._| TO parts.
    APPEND |_s=a.state),null!=E.getDerivedStateFromProps&&(a.__s==a.state&&(a.__s=s(\{\},a.__s)),s(a.__s,E.getDerivedStateFromProps(b,a.__s))),v=a.props,y=a.state,p)null==E.getDerivedStateFrom| TO parts.
    APPEND |Props&&null!=a.componentWillMount&&a.componentWillMount(),null!=a.componentDidMount&&a.__h.push(a.componentDidMount);else\{if(null==E.getDerivedStateFromProps&&b!==v&&null!=a.compo| TO parts.
    APPEND |nentWillReceiveProps&&a.componentWillReceiveProps(b,x),!a.__e&&null!=a.shouldComponentUpdate&&!1===a.shouldComponentUpdate(b,a.__s,x)\|\|_.__v===t.__v)\{a.props=b,a.state=a.__s,_._| TO parts.
    APPEND |_v!==t.__v&&(a.__d=!1),a.__v=_,_.__e=t.__e,_.__k=t.__k,_.__k.forEach(function(e)\{e&&(e.__=_)\}),a.__h.length&&l.push(a);break e\}null!=a.componentWillUpdate&&a.componentWillUpdate| TO parts.
    APPEND |(b,a.__s,x),null!=a.componentDidUpdate&&a.__h.push(function()\{a.componentDidUpdate(v,y,m)\})\}a.context=x,a.props=b,a.state=a.__s,(f=n.__r)&&f(_),a.__d=!1,a.__v=_,a.__P=e,f=a.rend| TO parts.
    APPEND |er(a.props,a.state,a.context),a.state=a.__s,null!=a.getChildContext&&(o=s(s(\{\},o),a.getChildContext())),p\|\|null==a.getSnapshotBeforeUpdate\|\|(m=a.getSnapshotBeforeUpdate(v,y))| TO parts.
    APPEND |,H=null!=f&&f.type===h&&null==f.key?f.props.children:f,k(e,Array.isArray(H)?H:[H],_,t,o,r,u,l,i,c),a.base=_.__e,_.__h=null,a.__h.length&&l.push(a),g&&(a.__E=a.__=null),a.__e=!1\}el| TO parts.
    APPEND |se null==u&&_.__v===t.__v?(_.__k=t.__k,_.__e=t.__e):_.__e=w(t.__e,_,t,o,r,u,l,c);(f=n.diffed)&&f(_)\}catch(e)\{_.__v=null,(c\|\|null!=u)&&(_.__e=i,_.__h=!!c,u[u.indexOf(i)]=null),n| TO parts.
    APPEND |.__e(e,_,t)\}\}function D(e,_)\{n.__c&&n.__c(_,e),e.some(function(_)\{try\{e=_.__h,_.__h=[],e.some(function(e)\{e.call(_)\})\}catch(e)\{n.__e(e,_.__v)\}\})\}function w(n,_,t,o,r,u,| TO parts.
    APPEND |i,c)\{var s,a,p,h=t.props,d=_.props,y=_.type,m=0;if("svg"===y&&(r=!0),null!=u)for(;m<u.length;m++)if((s=u[m])&&(s===n\|\|(y?s.localName==y:3==s.nodeType)))\{n=s,u[m]=null;break\}if| TO parts.
    APPEND |(null==n)\{if(null===y)return document.createTextNode(d);n=r?document.createElementNS("http://www.w3.org/2000/svg",y):document.createElement(y,d.is&&d),u=null,c=!1\}if(null===y)h==| TO parts.
    APPEND |=d\|\|c&&n.data===d\|\|(n.data=d);else\{if(u=u&&e.call(n.childNodes),a=(h=t.props\|\|l).dangerouslySetInnerHTML,p=d.dangerouslySetInnerHTML,!c)\{if(null!=u)for(h=\{\},m=0;m<n.attri| TO parts.
    APPEND |butes.length;m++)h[n.attributes[m].name]=n.attributes[m].value;(p\|\|a)&&(p&&(a&&p.__html==a.__html\|\|p.__html===n.innerHTML)\|\|(n.innerHTML=p&&p.__html\|\|""))\}if(function(e,n,| TO parts.
    APPEND |_,t,o)\{var r;for(r in _)"children"===r\|\|"key"===r\|\|r in n\|\|H(e,r,null,_[r],t);for(r in n)o&&"function"!=typeof n[r]\|\|"children"===r\|\|"key"===r\|\|"value"===r\|\|"checked| TO parts.
    APPEND |"===r\|\|_[r]===n[r]\|\|H(e,r,n[r],_[r],t)\}(n,d,h,r,c),p)_.__k=[];else if(m=_.props.children,k(n,Array.isArray(m)?m:[m],_,t,o,r&&"foreignObject"!==y,u,i,u?u[0]:t.__k&&v(t,0),c),nu| TO parts.
    APPEND |ll!=u)for(m=u.length;m--;)null!=u[m]&&f(u[m]);c\|\|("value"in d&&void 0!==(m=d.value)&&(m!==n.value\|\|"progress"===y&&!m)&&H(n,"value",m,h.value,!1),"checked"in d&&void 0!==(m=d.c| TO parts.
    APPEND |hecked)&&m!==n.checked&&H(n,"checked",m,h.checked,!1))\}return n\}function T(e,_,t)\{try\{"function"==typeof e?e(_):e.current=_\}catch(e)\{n.__e(e,t)\}\}function U(e,_,t)\{var o,r;| TO parts.
    APPEND |if(n.unmount&&n.unmount(e),(o=e.ref)&&(o.current&&o.current!==e.__e\|\|T(o,null,_)),null!=(o=e.__c))\{if(o.componentWillUnmount)try\{o.componentWillUnmount()\}catch(e)\{n.__e(e,_)| TO parts.
    APPEND |\}o.base=o.__P=null\}if(o=e.__k)for(r=0;r<o.length;r++)o[r]&&U(o[r],_,"function"!=typeof e.type);t\|\|null==e.__e\|\|f(e.__e),e.__e=e.__d=void 0\}function A(e,n,_)\{return this.con| TO parts.
    APPEND |structor(e,_)\}function M(_,t,o)\{var r,u,i;n.__&&n.__(_,t),u=(r="function"==typeof o)?null:o&&o.__k\|\|t.__k,i=[],P(t,_=(!r&&o\|\|t).__k=a(h,null,[_]),u\|\|l,l,void 0!==t.ownerSVG| TO parts.
    APPEND |Element,!r&&o?[o]:u?null:t.firstChild?e.call(t.childNodes):null,i,!r&&o?o:u?u.__e:t.firstChild,r),D(i,_)\}function F(e,n)\{var _=\{__c:n="__cC"+u++,__:e,Consumer:function(e,n)\{ret| TO parts.
    APPEND |urn e.children(n)\},Provider:function(e)\{var _,t;return this.getChildContext\|\|(_=[],(t=\{\})[n]=this,this.getChildContext=function()\{return t\},this.shouldComponentUpdate=funct| TO parts.
    APPEND |ion(e)\{this.props.value!==e.value&&_.some(m)\},this.sub=function(e)\{_.push(e);var n=e.componentWillUnmount;e.componentWillUnmount=function()\{_.splice(_.indexOf(e),1),n&&n.call(e| TO parts.
    APPEND |)\}\}),e.children\}\};return _.Provider.__=_.Consumer.contextType=_\}e=i.slice,n=\{__e:function(e,n)\{for(var _,t,o;n=n.__;)if((_=n.__c)&&!_.__)try\{if((t=_.constructor)&&null!=t.g| TO parts.
    APPEND |etDerivedStateFromError&&(_.setState(t.getDerivedStateFromError(e)),o=_.__d),null!=_.componentDidCatch&&(_.componentDidCatch(e),o=_.__d),o)return _.__E=_\}catch(n)\{e=n\}throw e\}| TO parts.
    APPEND |\},_=0,d.prototype.setState=function(e,n)\{var _;_=null!=this.__s&&this.__s!==this.state?this.__s:this.__s=s(\{\},this.state),"function"==typeof e&&(e=e(s(\{\},_),this.props)),e&&s| TO parts.
    APPEND |(_,e),null!=e&&this.__v&&(n&&this.__h.push(n),m(this))\},d.prototype.forceUpdate=function(e)\{this.__v&&(this.__e=!0,e&&this.__h.push(e),m(this))\},d.prototype.render=h,t=[],o="fun| TO parts.
    APPEND |ction"==typeof Promise?Promise.prototype.then.bind(Promise.resolve()):setTimeout,g.__r=0,u=0;var L,N,W,R=0,I=[],O=n.__b,V=n.__r,q=n.diffed,B=n.__c,$=n.unmount;function j(e,_)\{n.__| TO parts.
    APPEND |h&&n.__h(N,e,R\|\|_),R=0;var t=N.__H\|\|(N.__H=\{__:[],__h:[]\});return e>=t.__.length&&t.__.push(\{\}),t.__[e]\}function G(e)\{return R=1,z(ie,e)\}function z(e,n,_)\{var t=j(L++,2| TO parts.
    APPEND |);return t.t=e,t.__c\|\|(t.__=[_?_(n):ie(void 0,n),function(e)\{var n=t.t(t.__[0],e);t.__[0]!==n&&(t.__=[n,t.__[1]],t.__c.setState(\{\}))\}],t.__c=N),t.__\}function J(e,_)\{var t=j| TO parts.
    APPEND |(L++,3);!n.__s&&le(t.__H,_)&&(t.__=e,t.__H=_,N.__H.__h.push(t))\}function K(e,_)\{var t=j(L++,4);!n.__s&&le(t.__H,_)&&(t.__=e,t.__H=_,N.__h.push(t))\}function Q(e)\{return R=5,Y(fu| TO parts.
    APPEND |nction()\{return\{current:e\}\},[])\}function X(e,n,_)\{R=6,K(function()\{"function"==typeof e?e(n()):e&&(e.current=n())\},null==_?_:_.concat(e))\}function Y(e,n)\{var _=j(L++,7);r| TO parts.
    APPEND |eturn le(_.__H,n)&&(_.__=e(),_.__H=n,_.__h=e),_.__\}function Z(e,n)\{return R=8,Y(function()\{return e\},n)\}function ee(e)\{var n=N.context[e.__c],_=j(L++,9);return _.c=e,n?(null=| TO parts.
    APPEND |=_.__&&(_.__=!0,n.sub(N)),n.props.value):e.__\}function ne(e,_)\{n.useDebugValue&&n.useDebugValue(_?_(e):e)\}function _e(e)\{var n=j(L++,10),_=G();return n.__=e,N.componentDidCatch| TO parts.
    APPEND |\|\|(N.componentDidCatch=function(e)\{n.__&&n.__(e),_[1](e)\}),[_[0],function()\{_[1](void 0)\}]\}function te()\{I.forEach(function(e)\{if(e.__P)try\{e.__H.__h.forEach(re),e.__H.__| TO parts.
    APPEND |h.forEach(ue),e.__H.__h=[]\}catch(_)\{e.__H.__h=[],n.__e(_,e.__v)\}\}),I=[]\}n.__b=function(e)\{N=null,O&&O(e)\},n.__r=function(e)\{V&&V(e),L=0;var n=(N=e.__c).__H;n&&(n.__h.forEac| TO parts.
    APPEND |h(re),n.__h.forEach(ue),n.__h=[])\},n.diffed=function(e)\{q&&q(e);var _=e.__c;_&&_.__H&&_.__H.__h.length&&(1!==I.push(_)&&W===n.requestAnimationFrame\|\|((W=n.requestAnimationFrame| TO parts.
    APPEND |)\|\|function(e)\{var n,_=function()\{clearTimeout(t),oe&&cancelAnimationFrame(n),setTimeout(e)\},t=setTimeout(_,100);oe&&(n=requestAnimationFrame(_))\})(te)),N=void 0\},n.__c=func| TO parts.
    APPEND |tion(e,_)\{_.some(function(e)\{try\{e.__h.forEach(re),e.__h=e.__h.filter(function(e)\{return!e.__\|\|ue(e)\})\}catch(t)\{_.some(function(e)\{e.__h&&(e.__h=[])\}),_=[],n.__e(t,e.__v| TO parts.
    APPEND |)\}\}),B&&B(e,_)\},n.unmount=function(e)\{$&&$(e);var _=e.__c;if(_&&_.__H)try\{_.__H.__.forEach(re)\}catch(e)\{n.__e(e,_.__v)\}\};var oe="function"==typeof requestAnimationFrame;fu| TO parts.
    APPEND |nction re(e)\{var n=N;"function"==typeof e.__c&&e.__c(),N=n\}function ue(e)\{var n=N;e.__c=e.__(),N=n\}function le(e,n)\{return!e\|\|e.length!==n.length\|\|n.some(function(n,_)\{re| TO parts.
    APPEND |turn n!==e[_]\})\}function ie(e,n)\{return"function"==typeof n?n(e):n\}var ce=function(e,n,_,t)\{var o;n[0]=0;for(var r=1;r<n.length;r++)\{var u=n[r++],l=n[r]?(n[0]\|=u?1:2,_[n[r++| TO parts.
    APPEND |]]):n[++r];3===u?t[0]=l:4===u?t[1]=Object.assign(t[1]\|\|\{\},l):5===u?(t[1]=t[1]\|\|\{\})[n[++r]]=l:6===u?t[1][n[++r]]+=l+"":u?(o=e.apply(l,ce(e,l,_,["",null])),t.push(o),l[0]?n[0| TO parts.
    APPEND |]\|=2:(n[r-2]=0,n[r]=o)):t.push(l)\}return t\},se=new Map,fe=function(e)\{var n=se.get(this);return n\|\|(n=new Map,se.set(this,n)),(n=ce(this,n.get(e)\|\|(n.set(e,n=function(e)\{f| TO parts.
    APPEND |or(var n,_,t=1,o="",r="",u=[0],l=function(e)\{1===t&&(e\|\|(o=o.replace(/^\\s*\\n\\s*\|\\s*\\n\\s*$/g,"")))?u.push(0,e,o):3===t&&(e\|\|o)?(u.push(3,e,o),t=2):2===t&&"..."===o&&e?u.| TO parts.
    APPEND |push(4,e,0):2===t&&o&&!e?u.push(5,0,!0,o):t>=5&&((o\|\|!e&&5===t)&&(u.push(t,0,o,_),t=6),e&&(u.push(t,e,0,_),t=6)),o=""\},i=0;i<e.length;i++)\{i&&(1===t&&l(),l(i));for(var c=0;c<e[| TO parts.
    APPEND |i].length;c++)n=e[i][c],1===t?"<"===n?(l(),u=[u],t=3):o+=n:4===t?"--"===o&&">"===n?(t=1,o=""):o=n+o[0]:r?n===r?r="":o+=n:'"'===n\|\|"'"===n?r=n:">"===n?(l(),t=1):t&&("="===n?(t=5,_| TO parts.
    APPEND |=o,o=""):"/"===n&&(t<5\|\|">"===e[i][c+1])?(l(),3===t&&(u=u[0]),t=u,(u=u[0]).push(2,0,t),t=0):" "===n\|\|"\\t"===n\|\|"\\n"===n\|\|"\\r"===n?(l(),t=2):o+=n),3===t&&"!--"===o&&(t=4,| TO parts.
    APPEND |u=u[0])\}return l(),u\}(e)),n),arguments,[])).length>1?n:n[0]\}.bind(a);export\{a as h,fe as html,M as render,d as Component,F as createContext,G as useState,z as useReducer,J as u| TO parts.
    APPEND |seEffect,K as useLayoutEffect,Q as useRef,X as useImperativeHandle,Y as useMemo,Z as useCallback,ee as useContext,ne as useDebugValue,_e as useErrorBoundary\};\n| TO parts.
    result = concat_lines_of( parts ).
  ENDMETHOD.

ENDCLASS.